// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "reflect"

type RefToEnumJson struct {
	// mything corresponds to the JSON schema field "myThing".
	mything *Thing `json:"myThing,omitempty,omitzero" yaml:"myThing,omitempty" mapstructure:"myThing,omitempty"`
}

func (o *RefToEnumJson) MyThing() *Thing {
	return o.mything
}

type Thing string

const ThingX Thing = "x"
const ThingY Thing = "y"

var enumValues_Thing = []interface{}{
	"x",
	"y",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Thing) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Thing {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Thing, v)
	}
	*j = Thing(v)
	return nil
}
