// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "unicode/utf8"

type MinStr string

// UnmarshalJSON implements json.Unmarshaler.
func (j *MinStr) UnmarshalJSON(value []byte) error {
	type Plain MinStr
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain)) < 5 {
		return fmt.Errorf("field %s length: must be >= %d", "", 5)
	}
	*j = MinStr(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *MinStr) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
	}
	type Plain MinStr
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain = plain
	if utf8.RuneCountInString(string(plain)) < 5 {
		return fmt.Errorf("field %s length: must be >= %d", "", 5)
	}
	*j = MinStr(plain)
	return nil
}

func NewPrimitiveDefsBuilder(o *PrimitiveDefs) *PrimitiveDefsBuilder {
	if o == nil {
		return &PrimitiveDefsBuilder{}
	}
	return &PrimitiveDefsBuilder{
		mynullablestring: o.mynullablestring,
		mystring:         o.mystring,
	}
}

type PrimitiveDefs struct {
	// mynullablestring corresponds to the JSON schema field "myNullableString".
	mynullablestring *MinStr `json:"myNullableString,omitempty,omitzero" yaml:"myNullableString,omitempty" mapstructure:"myNullableString,omitempty"`

	// mystring corresponds to the JSON schema field "myString".
	mystring MinStr `json:"myString" yaml:"myString" mapstructure:"myString"`
}

type PrimitiveDefsBuilder struct {
	mynullablestring *MinStr

	mystring MinStr
}

func (b *PrimitiveDefsBuilder) Build() *PrimitiveDefs {
	return &PrimitiveDefs{
		mynullablestring: b.mynullablestring,
		mystring:         b.mystring,
	}
}

func (b *PrimitiveDefsBuilder) WithMyNullableString(v *MinStr) *PrimitiveDefsBuilder {
	b.mynullablestring = v
	return b
}

func (b *PrimitiveDefsBuilder) WithMyString(v MinStr) *PrimitiveDefsBuilder {
	b.mystring = v
	return b
}

func (o *PrimitiveDefs) Clone() *PrimitiveDefsBuilder {
	return NewPrimitiveDefsBuilder(o)
}

func (o *PrimitiveDefs) MyNullableString() *MinStr {
	return o.mynullablestring
}

func (o *PrimitiveDefs) MyString() MinStr {
	return o.mystring
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PrimitiveDefs) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myString"]; raw != nil && !ok {
		return fmt.Errorf("field myString in PrimitiveDefs: required")
	}
	type PrimitiveDefsHelper struct {
		Mynullablestring *MinStr `json:"myNullableString,omitempty,omitzero"`
		Mystring         MinStr  `json:"myString"`
	}
	type Plain PrimitiveDefs
	var helper PrimitiveDefsHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mynullablestring = helper.Mynullablestring
	plain.mystring = helper.Mystring
	*j = PrimitiveDefs(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *PrimitiveDefs) MarshalJSON() ([]byte, error) {
	type PrimitiveDefsMarshalHelper struct {
		Mynullablestring *MinStr `json:"myNullableString,omitempty,omitzero"`
		Mystring         MinStr  `json:"myString"`
	}
	helper := PrimitiveDefsMarshalHelper{
		Mynullablestring: j.mynullablestring,
		Mystring:         j.mystring,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *PrimitiveDefs) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["myString"]; raw != nil && !ok {
		return fmt.Errorf("field myString in PrimitiveDefs: required")
	}
	type PlainRaw struct {
		Mynullablestring *MinStr
		Mystring         MinStr
	}
	type Plain PrimitiveDefs
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.mynullablestring = rawStruct.Mynullablestring
	plain.mystring = rawStruct.Mystring
	plain = plain
	*j = PrimitiveDefs(plain)
	return nil
}
