// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

type ACase struct {
	// capitalcamelfield corresponds to the JSON schema field "CapitalCamelField".
	capitalcamelfield *string `json:"CapitalCamelField,omitempty,omitzero" yaml:"CapitalCamelField,omitempty" mapstructure:"CapitalCamelField,omitempty"`

	// uppercasefield corresponds to the JSON schema field "UPPERCASEFIELD".
	uppercasefield *string `json:"UPPERCASEFIELD,omitempty,omitzero" yaml:"UPPERCASEFIELD,omitempty" mapstructure:"UPPERCASEFIELD,omitempty"`

	// camelcase corresponds to the JSON schema field "camelCase".
	camelcase *string `json:"camelCase,omitempty,omitzero" yaml:"camelCase,omitempty" mapstructure:"camelCase,omitempty"`

	// lowercase corresponds to the JSON schema field "lowercase".
	lowercase *string `json:"lowercase,omitempty,omitzero" yaml:"lowercase,omitempty" mapstructure:"lowercase,omitempty"`

	// snakemixedcase corresponds to the JSON schema field "snake_Mixed_Case".
	snakemixedcase *string `json:"snake_Mixed_Case,omitempty,omitzero" yaml:"snake_Mixed_Case,omitempty" mapstructure:"snake_Mixed_Case,omitempty"`

	// snakecase corresponds to the JSON schema field "snake_case".
	snakecase *string `json:"snake_case,omitempty,omitzero" yaml:"snake_case,omitempty" mapstructure:"snake_case,omitempty"`
}

type ACaseBuilder struct {
	capitalcamelfield *string

	uppercasefield *string

	camelcase *string

	lowercase *string

	snakemixedcase *string

	snakecase *string
}

func (b *ACaseBuilder) Build() *ACase {
	return &ACase{
		capitalcamelfield: b.capitalcamelfield,
		uppercasefield:    b.uppercasefield,
		camelcase:         b.camelcase,
		lowercase:         b.lowercase,
		snakemixedcase:    b.snakemixedcase,
		snakecase:         b.snakecase,
	}
}

func (b *ACaseBuilder) WithCamelCase(v *string) *ACaseBuilder {
	b.camelcase = v
	return b
}

func (b *ACaseBuilder) WithCapitalCamelField(v *string) *ACaseBuilder {
	b.capitalcamelfield = v
	return b
}

func (b *ACaseBuilder) WithLowercase(v *string) *ACaseBuilder {
	b.lowercase = v
	return b
}

func (b *ACaseBuilder) WithSnakeCase(v *string) *ACaseBuilder {
	b.snakecase = v
	return b
}

func (b *ACaseBuilder) WithSnakeMixedCase(v *string) *ACaseBuilder {
	b.snakemixedcase = v
	return b
}

func (b *ACaseBuilder) WithUPPERCASEFIELD(v *string) *ACaseBuilder {
	b.uppercasefield = v
	return b
}

func (o *ACase) CamelCase() *string {
	return o.camelcase
}

func (o *ACase) CapitalCamelField() *string {
	return o.capitalcamelfield
}

func (o *ACase) Clone() *ACaseBuilder {
	return NewACaseBuilder(o)
}

func (o *ACase) Lowercase() *string {
	return o.lowercase
}

func (o *ACase) SnakeCase() *string {
	return o.snakecase
}

func (o *ACase) SnakeMixedCase() *string {
	return o.snakemixedcase
}

func (o *ACase) UPPERCASEFIELD() *string {
	return o.uppercasefield
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ACase) UnmarshalJSON(value []byte) error {
	type ACaseHelper struct {
		Capitalcamelfield *string `json:"CapitalCamelField,omitempty"`
		Uppercasefield    *string `json:"UPPERCASEFIELD,omitempty"`
		Camelcase         *string `json:"camelCase,omitempty"`
		Lowercase         *string `json:"lowercase,omitempty"`
		Snakemixedcase    *string `json:"snake_Mixed_Case,omitempty"`
		Snakecase         *string `json:"snake_case,omitempty"`
	}
	type Plain ACase
	var helper ACaseHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.capitalcamelfield = helper.Capitalcamelfield
	plain.uppercasefield = helper.Uppercasefield
	plain.camelcase = helper.Camelcase
	plain.lowercase = helper.Lowercase
	plain.snakemixedcase = helper.Snakemixedcase
	plain.snakecase = helper.Snakecase
	*j = ACase(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *ACase) MarshalJSON() ([]byte, error) {
	type ACaseMarshalHelper struct {
		Capitalcamelfield *string `json:"CapitalCamelField,omitempty"`
		Uppercasefield    *string `json:"UPPERCASEFIELD,omitempty"`
		Camelcase         *string `json:"camelCase,omitempty"`
		Lowercase         *string `json:"lowercase,omitempty"`
		Snakemixedcase    *string `json:"snake_Mixed_Case,omitempty"`
		Snakecase         *string `json:"snake_case,omitempty"`
	}
	helper := ACaseMarshalHelper{
		Capitalcamelfield: j.capitalcamelfield,
		Uppercasefield:    j.uppercasefield,
		Camelcase:         j.camelcase,
		Lowercase:         j.lowercase,
		Snakemixedcase:    j.snakemixedcase,
		Snakecase:         j.snakecase,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ACase) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Capitalcamelfield *string
		Uppercasefield    *string
		Camelcase         *string
		Lowercase         *string
		Snakemixedcase    *string
		Snakecase         *string
	}
	type Plain ACase
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.capitalcamelfield = rawStruct.Capitalcamelfield
	plain.uppercasefield = rawStruct.Uppercasefield
	plain.camelcase = rawStruct.Camelcase
	plain.lowercase = rawStruct.Lowercase
	plain.snakemixedcase = rawStruct.Snakemixedcase
	plain.snakecase = rawStruct.Snakecase
	plain = plain
	*j = ACase(plain)
	return nil
}

func NewACaseBuilder(o *ACase) *ACaseBuilder {
	if o == nil {
		return &ACaseBuilder{}
	}
	return &ACaseBuilder{
		capitalcamelfield: o.capitalcamelfield,
		uppercasefield:    o.uppercasefield,
		camelcase:         o.camelcase,
		lowercase:         o.lowercase,
		snakemixedcase:    o.snakemixedcase,
		snakecase:         o.snakecase,
	}
}
