// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"

type ReadOnlyAndRequiredJson struct {
	// myreadonlyrequiredstring corresponds to the JSON schema field
	// "myReadOnlyRequiredString".
	myreadonlyrequiredstring string `json:"myReadOnlyRequiredString" yaml:"myReadOnlyRequiredString" mapstructure:"myReadOnlyRequiredString"`
}

func (o *ReadOnlyAndRequiredJson) MyReadOnlyRequiredString() string {
	return o.myreadonlyrequiredstring
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReadOnlyAndRequiredJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myReadOnlyRequiredString"]; raw != nil && !ok {
		return fmt.Errorf("field myReadOnlyRequiredString in ReadOnlyAndRequiredJson: required")
	}
	if _, ok := raw["myReadOnlyRequiredString"]; raw != nil && ok {
		return fmt.Errorf("field myReadOnlyRequiredString in ReadOnlyAndRequiredJson: read only")
	}
	type ReadOnlyAndRequiredJsonHelper struct {
		Myreadonlyrequiredstring string `json:"myReadOnlyRequiredString"`
	}
	type Plain ReadOnlyAndRequiredJson
	var helper ReadOnlyAndRequiredJsonHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myreadonlyrequiredstring = helper.Myreadonlyrequiredstring
	*j = ReadOnlyAndRequiredJson(plain)
	return nil
}
