// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

func NewOmitZeroBuilder(o *OmitZero) *OmitZeroBuilder {
	if o == nil {
		return &OmitZeroBuilder{}
	}
	return &OmitZeroBuilder{
		myarray:       o.myarray,
		myboolean:     o.myboolean,
		myinteger:     o.myinteger,
		mymap:         o.mymap,
		mynull:        o.mynull,
		mynullarray:   o.mynullarray,
		mynumber:      o.mynumber,
		myobjectarray: o.myobjectarray,
		mystring:      o.mystring,
		mystringarray: o.mystringarray,
	}
}

type OmitZero struct {
	// myarray corresponds to the JSON schema field "myArray".
	myarray []interface{} `json:"myArray,omitzero"`

	// myboolean corresponds to the JSON schema field "myBoolean".
	myboolean *bool `json:"myBoolean,omitzero"`

	// myinteger corresponds to the JSON schema field "myInteger".
	myinteger *int `json:"myInteger,omitzero"`

	// mymap corresponds to the JSON schema field "myMap".
	mymap OmitZeromymap `json:"myMap,omitzero"`

	// mynull corresponds to the JSON schema field "myNull".
	mynull interface{} `json:"myNull,omitzero"`

	// mynullarray corresponds to the JSON schema field "myNullArray".
	mynullarray []interface{} `json:"myNullArray,omitzero"`

	// mynumber corresponds to the JSON schema field "myNumber".
	mynumber *float64 `json:"myNumber,omitzero"`

	// myobjectarray corresponds to the JSON schema field "myObjectArray".
	myobjectarray []OmitZeromyobjectarrayElem `json:"myObjectArray,omitzero"`

	// mystring corresponds to the JSON schema field "myString".
	mystring *string `json:"myString,omitzero"`

	// mystringarray corresponds to the JSON schema field "myStringArray".
	mystringarray []string `json:"myStringArray,omitzero"`
}

type OmitZeroBuilder struct {
	myarray []interface{}

	myboolean *bool

	myinteger *int

	mymap OmitZeromymap

	mynull interface{}

	mynullarray []interface{}

	mynumber *float64

	myobjectarray []OmitZeromyobjectarrayElem

	mystring *string

	mystringarray []string
}

func (b *OmitZeroBuilder) Build() *OmitZero {
	return &OmitZero{
		myarray:       b.myarray,
		myboolean:     b.myboolean,
		myinteger:     b.myinteger,
		mymap:         b.mymap,
		mynull:        b.mynull,
		mynullarray:   b.mynullarray,
		mynumber:      b.mynumber,
		myobjectarray: b.myobjectarray,
		mystring:      b.mystring,
		mystringarray: b.mystringarray,
	}
}

func (b *OmitZeroBuilder) WithMyArray(v []interface{}) *OmitZeroBuilder {
	b.myarray = v
	return b
}

func (b *OmitZeroBuilder) WithMyBoolean(v *bool) *OmitZeroBuilder {
	b.myboolean = v
	return b
}

func (b *OmitZeroBuilder) WithMyInteger(v *int) *OmitZeroBuilder {
	b.myinteger = v
	return b
}

func (b *OmitZeroBuilder) WithMyMap(v OmitZeromymap) *OmitZeroBuilder {
	b.mymap = v
	return b
}

func (b *OmitZeroBuilder) WithMyNull(v interface{}) *OmitZeroBuilder {
	b.mynull = v
	return b
}

func (b *OmitZeroBuilder) WithMyNullArray(v []interface{}) *OmitZeroBuilder {
	b.mynullarray = v
	return b
}

func (b *OmitZeroBuilder) WithMyNumber(v *float64) *OmitZeroBuilder {
	b.mynumber = v
	return b
}

func (b *OmitZeroBuilder) WithMyObjectArray(v []OmitZeromyobjectarrayElem) *OmitZeroBuilder {
	b.myobjectarray = v
	return b
}

func (b *OmitZeroBuilder) WithMyString(v *string) *OmitZeroBuilder {
	b.mystring = v
	return b
}

func (b *OmitZeroBuilder) WithMyStringArray(v []string) *OmitZeroBuilder {
	b.mystringarray = v
	return b
}

func (o *OmitZero) Clone() *OmitZeroBuilder {
	return NewOmitZeroBuilder(o)
}

func (o *OmitZero) MyArray() []interface{} {
	return o.myarray
}

func (o *OmitZero) MyBoolean() *bool {
	return o.myboolean
}

func (o *OmitZero) MyInteger() *int {
	return o.myinteger
}

func (o *OmitZero) MyMap() OmitZeromymap {
	return o.mymap
}

func (o *OmitZero) MyNull() interface{} {
	return o.mynull
}

func (o *OmitZero) MyNullArray() []interface{} {
	return o.mynullarray
}

func (o *OmitZero) MyNumber() *float64 {
	return o.mynumber
}

func (o *OmitZero) MyObjectArray() []OmitZeromyobjectarrayElem {
	return o.myobjectarray
}

func (o *OmitZero) MyString() *string {
	return o.mystring
}

func (o *OmitZero) MyStringArray() []string {
	return o.mystringarray
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OmitZero) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type OmitZeroHelper struct {
		Myarray       []interface{}               `json:"myArray",omitempty`
		Myboolean     *bool                       `json:"myBoolean",omitempty`
		Myinteger     *int                        `json:"myInteger",omitempty`
		Mymap         OmitZeromymap               `json:"myMap",omitempty`
		Mynull        interface{}                 `json:"myNull",omitempty`
		Mynullarray   []interface{}               `json:"myNullArray",omitempty`
		Mynumber      *float64                    `json:"myNumber",omitempty`
		Myobjectarray []OmitZeromyobjectarrayElem `json:"myObjectArray",omitempty`
		Mystring      *string                     `json:"myString",omitempty`
		Mystringarray []string                    `json:"myStringArray",omitempty`
	}
	type Plain OmitZero
	var helper OmitZeroHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myarray = helper.Myarray
	plain.myboolean = helper.Myboolean
	plain.myinteger = helper.Myinteger
	plain.mymap = helper.Mymap
	plain.mynull = helper.Mynull
	plain.mynullarray = helper.Mynullarray
	plain.mynumber = helper.Mynumber
	plain.myobjectarray = helper.Myobjectarray
	plain.mystring = helper.Mystring
	plain.mystringarray = helper.Mystringarray
	if plain.mynull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := range plain.mynullarray {
		if plain.mynullarray[i0] != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = OmitZero(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *OmitZero) MarshalJSON() ([]byte, error) {
	type OmitZeroMarshalHelper struct {
		Myarray       []interface{}               `json:"myArray",omitempty`
		Myboolean     *bool                       `json:"myBoolean",omitempty`
		Myinteger     *int                        `json:"myInteger",omitempty`
		Mymap         OmitZeromymap               `json:"myMap",omitempty`
		Mynull        interface{}                 `json:"myNull",omitempty`
		Mynullarray   []interface{}               `json:"myNullArray",omitempty`
		Mynumber      *float64                    `json:"myNumber",omitempty`
		Myobjectarray []OmitZeromyobjectarrayElem `json:"myObjectArray",omitempty`
		Mystring      *string                     `json:"myString",omitempty`
		Mystringarray []string                    `json:"myStringArray",omitempty`
	}
	helper := OmitZeroMarshalHelper{
		Myarray:       j.myarray,
		Myboolean:     j.myboolean,
		Myinteger:     j.myinteger,
		Mymap:         j.mymap,
		Mynull:        j.mynull,
		Mynullarray:   j.mynullarray,
		Mynumber:      j.mynumber,
		Myobjectarray: j.myobjectarray,
		Mystring:      j.mystring,
		Mystringarray: j.mystringarray,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *OmitZero) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type Plain OmitZero
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.mynull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := range plain.mynullarray {
		if plain.mynullarray[i0] != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = OmitZero(plain)
	return nil
}

type OmitZeromymap map[string]float64

type OmitZeromyobjectarrayElem map[string]interface{}
