// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

type Name string

type RefExternalFileAllOfNestedRefs struct {
	// name corresponds to the JSON schema field "name".
	name *Name `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

func (o *RefExternalFileAllOfNestedRefs) Name() *Name {
	return o.name
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RefExternalFileAllOfNestedRefs) UnmarshalYAML(value *yaml.Node) error {
	type Plain RefExternalFileAllOfNestedRefs
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = RefExternalFileAllOfNestedRefs(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RefExternalFileAllOfNestedRefs) UnmarshalJSON(value []byte) error {
	type RefExternalFileAllOfNestedRefsHelper struct {
		Name *Name `json:"name",omitempty`
	}
	type Plain RefExternalFileAllOfNestedRefs
	var helper RefExternalFileAllOfNestedRefsHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = RefExternalFileAllOfNestedRefs(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *RefExternalFileAllOfNestedRefs) MarshalJSON() ([]byte, error) {
	type RefExternalFileAllOfNestedRefsMarshalHelper struct {
		Name *Name `json:"name",omitempty`
	}
	helper := RefExternalFileAllOfNestedRefsMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}

type RefNested struct {
	// mything corresponds to the JSON schema field "myThing".
	mything *Thing `json:"myThing,omitempty,omitzero" yaml:"myThing,omitempty" mapstructure:"myThing,omitempty"`
}

func (o *RefNested) MyThing() *Thing {
	return o.mything
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RefNested) UnmarshalJSON(value []byte) error {
	type RefNestedHelper struct {
		Mything *Thing `json:"myThing",omitempty`
	}
	type Plain RefNested
	var helper RefNestedHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mything = helper.Mything
	*j = RefNested(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *RefNested) MarshalJSON() ([]byte, error) {
	type RefNestedMarshalHelper struct {
		Mything *Thing `json:"myThing",omitempty`
	}
	helper := RefNestedMarshalHelper{
		Mything: j.mything,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RefNested) UnmarshalYAML(value *yaml.Node) error {
	type Plain RefNested
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = RefNested(plain)
	return nil
}

type Thing struct {
	// name corresponds to the JSON schema field "name".
	name *Name `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

func (o *Thing) Name() *Name {
	return o.name
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Thing) UnmarshalYAML(value *yaml.Node) error {
	type Plain Thing
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Thing(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Thing) UnmarshalJSON(value []byte) error {
	type ThingHelper struct {
		Name *Name `json:"name",omitempty`
	}
	type Plain Thing
	var helper ThingHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = Thing(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Thing) MarshalJSON() ([]byte, error) {
	type ThingMarshalHelper struct {
		Name *Name `json:"name",omitempty`
	}
	helper := ThingMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}
