// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

func NewPeerNameBuilder(o *PeerName) *PeerNameBuilder {
	if o == nil {
		return &PeerNameBuilder{}
	}
	return &PeerNameBuilder{
		kind:  o.kind,
		value: o.value,
	}
}

func NewTestcaseBuilder(o *Testcase) *TestcaseBuilder {
	if o == nil {
		return &TestcaseBuilder{}
	}
	return &TestcaseBuilder{
		expectedpeername:    o.expectedpeername,
		notexpectedpeername: o.notexpectedpeername,
	}
}

func NewTestcaseexpectedpeernameBuilder(o *Testcaseexpectedpeername) *TestcaseexpectedpeernameBuilder {
	if o == nil {
		return &TestcaseexpectedpeernameBuilder{}
	}
	return &TestcaseexpectedpeernameBuilder{
		kind:  o.kind,
		value: o.value,
	}
}

func NewTestcasenotexpectedpeernameBuilder(o *Testcasenotexpectedpeername) *TestcasenotexpectedpeernameBuilder {
	if o == nil {
		return &TestcasenotexpectedpeernameBuilder{}
	}
	return &TestcasenotexpectedpeernameBuilder{
		kind:  o.kind,
		value: o.value,
	}
}

type PeerKind string

const PeerKindDNS PeerKind = "DNS"
const PeerKindIP PeerKind = "IP"
const PeerKindRFC822 PeerKind = "RFC822"

var enumValues_PeerKind = []interface{}{
	"RFC822",
	"DNS",
	"IP",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *PeerKind) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PeerKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PeerKind, v)
	}
	*j = PeerKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PeerKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PeerKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PeerKind, v)
	}
	*j = PeerKind(v)
	return nil
}

// Represents a peer (i.e., end entity) certificate's name (Subject or SAN).
type PeerName struct {
	// The kind of peer name
	kind PeerKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// The peer's name
	value string `json:"value" yaml:"value" mapstructure:"value"`
}

type PeerNameBuilder struct {
	kind PeerKind

	value string
}

func (b *PeerNameBuilder) Build() *PeerName {
	return &PeerName{
		kind:  b.kind,
		value: b.value,
	}
}

func (b *PeerNameBuilder) WithKind(v PeerKind) *PeerNameBuilder {
	b.kind = v
	return b
}

func (b *PeerNameBuilder) WithValue(v string) *PeerNameBuilder {
	b.value = v
	return b
}

func (o *PeerName) Clone() *PeerNameBuilder {
	return NewPeerNameBuilder(o)
}

func (o *PeerName) Kind() PeerKind {
	return o.kind
}

func (o *PeerName) Value() string {
	return o.value
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PeerName) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in PeerName: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in PeerName: required")
	}
	type PeerNameHelper struct {
		Kind  PeerKind `json:"kind"`
		Value string   `json:"value"`
	}
	type Plain PeerName
	var helper PeerNameHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.kind = helper.Kind
	plain.value = helper.Value
	*j = PeerName(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *PeerName) MarshalJSON() ([]byte, error) {
	type PeerNameMarshalHelper struct {
		Kind  PeerKind `json:"kind"`
		Value string   `json:"value"`
	}
	helper := PeerNameMarshalHelper{
		Kind:  j.kind,
		Value: j.value,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *PeerName) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in PeerName: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in PeerName: required")
	}
	type PlainRaw struct {
		Kind  PeerKind
		Value string
	}
	type Plain PeerName
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.kind = rawStruct.Kind
	plain.value = rawStruct.Value
	plain = plain
	*j = PeerName(plain)
	return nil
}

// Represents an individual Limbo testcase.
type Testcase struct {
	// For server (i.e. client-side) validation: the expected peer name, if any
	expectedpeername *Testcaseexpectedpeername `json:"expected_peer_name" yaml:"expected_peer_name" mapstructure:"expected_peer_name"`

	// For server (i.e. client-side) validation: the expected peer name, if any
	notexpectedpeername *Testcasenotexpectedpeername `json:"not_expected_peer_name,omitempty,omitzero" yaml:"not_expected_peer_name,omitempty" mapstructure:"not_expected_peer_name,omitempty"`
}

type TestcaseBuilder struct {
	expectedpeername *Testcaseexpectedpeername

	notexpectedpeername *Testcasenotexpectedpeername
}

func (b *TestcaseBuilder) Build() *Testcase {
	return &Testcase{
		expectedpeername:    b.expectedpeername,
		notexpectedpeername: b.notexpectedpeername,
	}
}

func (b *TestcaseBuilder) WithExpectedPeerName(v *Testcaseexpectedpeername) *TestcaseBuilder {
	b.expectedpeername = v
	return b
}

func (b *TestcaseBuilder) WithNotExpectedPeerName(v *Testcasenotexpectedpeername) *TestcaseBuilder {
	b.notexpectedpeername = v
	return b
}

func (o *Testcase) Clone() *TestcaseBuilder {
	return NewTestcaseBuilder(o)
}

func (o *Testcase) ExpectedPeerName() *Testcaseexpectedpeername {
	return o.expectedpeername
}

func (o *Testcase) NotExpectedPeerName() *Testcasenotexpectedpeername {
	return o.notexpectedpeername
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Testcase) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["expected_peer_name"]; raw != nil && !ok {
		return fmt.Errorf("field expected_peer_name in Testcase: required")
	}
	type PlainRaw struct {
		Expectedpeername    *Testcaseexpectedpeername
		Notexpectedpeername *Testcasenotexpectedpeername
	}
	type Plain Testcase
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.expectedpeername = rawStruct.Expectedpeername
	plain.notexpectedpeername = rawStruct.Notexpectedpeername
	plain = plain
	*j = Testcase(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Testcase) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["expected_peer_name"]; raw != nil && !ok {
		return fmt.Errorf("field expected_peer_name in Testcase: required")
	}
	type TestcaseHelper struct {
		Expectedpeername    *Testcaseexpectedpeername    `json:"expected_peer_name"`
		Notexpectedpeername *Testcasenotexpectedpeername `json:"not_expected_peer_name,omitempty"`
	}
	type Plain Testcase
	var helper TestcaseHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.expectedpeername = helper.Expectedpeername
	plain.notexpectedpeername = helper.Notexpectedpeername
	*j = Testcase(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Testcase) MarshalJSON() ([]byte, error) {
	type TestcaseMarshalHelper struct {
		Expectedpeername    *Testcaseexpectedpeername    `json:"expected_peer_name"`
		Notexpectedpeername *Testcasenotexpectedpeername `json:"not_expected_peer_name,omitempty"`
	}
	helper := TestcaseMarshalHelper{
		Expectedpeername:    j.expectedpeername,
		Notexpectedpeername: j.notexpectedpeername,
	}
	return json.Marshal(helper)
}

// For server (i.e. client-side) validation: the expected peer name, if any
type Testcaseexpectedpeername struct {
	// The kind of peer name
	kind PeerKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// The peer's name
	value string `json:"value" yaml:"value" mapstructure:"value"`
}

type TestcaseexpectedpeernameBuilder struct {
	kind PeerKind

	value string
}

func (b *TestcaseexpectedpeernameBuilder) Build() *Testcaseexpectedpeername {
	return &Testcaseexpectedpeername{
		kind:  b.kind,
		value: b.value,
	}
}

func (b *TestcaseexpectedpeernameBuilder) WithKind(v PeerKind) *TestcaseexpectedpeernameBuilder {
	b.kind = v
	return b
}

func (b *TestcaseexpectedpeernameBuilder) WithValue(v string) *TestcaseexpectedpeernameBuilder {
	b.value = v
	return b
}

func (o *Testcaseexpectedpeername) Clone() *TestcaseexpectedpeernameBuilder {
	return NewTestcaseexpectedpeernameBuilder(o)
}

func (o *Testcaseexpectedpeername) Kind() PeerKind {
	return o.kind
}

func (o *Testcaseexpectedpeername) Value() string {
	return o.value
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Testcaseexpectedpeername) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var testcaseexpectedpeername_0 Testcaseexpectedpeername_0
	var errs []error
	if err := testcaseexpectedpeername_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type PlainRaw struct {
		Kind  PeerKind
		Value string
	}
	type Plain Testcaseexpectedpeername
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.kind = rawStruct.Kind
	plain.value = rawStruct.Value
	plain = plain
	*j = Testcaseexpectedpeername(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Testcaseexpectedpeername) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var testcaseexpectedpeername_0 Testcaseexpectedpeername_0
	var errs []error
	if err := testcaseexpectedpeername_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type TestcaseexpectedpeernameHelper struct {
		Kind  PeerKind `json:"kind"`
		Value string   `json:"value"`
	}
	type Plain Testcaseexpectedpeername
	var helper TestcaseexpectedpeernameHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.kind = helper.Kind
	plain.value = helper.Value
	*j = Testcaseexpectedpeername(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Testcaseexpectedpeername) MarshalJSON() ([]byte, error) {
	type TestcaseexpectedpeernameMarshalHelper struct {
		Kind  PeerKind `json:"kind"`
		Value string   `json:"value"`
	}
	helper := TestcaseexpectedpeernameMarshalHelper{
		Kind:  j.kind,
		Value: j.value,
	}
	return json.Marshal(helper)
}

// For server (i.e. client-side) validation: the expected peer name, if any
type Testcasenotexpectedpeername struct {
	// The kind of peer name
	kind PeerKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// The peer's name
	value string `json:"value" yaml:"value" mapstructure:"value"`
}

type TestcasenotexpectedpeernameBuilder struct {
	kind PeerKind

	value string
}

func (b *TestcasenotexpectedpeernameBuilder) Build() *Testcasenotexpectedpeername {
	return &Testcasenotexpectedpeername{
		kind:  b.kind,
		value: b.value,
	}
}

func (b *TestcasenotexpectedpeernameBuilder) WithKind(v PeerKind) *TestcasenotexpectedpeernameBuilder {
	b.kind = v
	return b
}

func (b *TestcasenotexpectedpeernameBuilder) WithValue(v string) *TestcasenotexpectedpeernameBuilder {
	b.value = v
	return b
}

type Testcasenotexpectedpeername_0 = PeerName

func (o *Testcasenotexpectedpeername) Clone() *TestcasenotexpectedpeernameBuilder {
	return NewTestcasenotexpectedpeernameBuilder(o)
}

func (o *Testcasenotexpectedpeername) Kind() PeerKind {
	return o.kind
}

func (o *Testcasenotexpectedpeername) Value() string {
	return o.value
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Testcasenotexpectedpeername) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var testcasenotexpectedpeername_0 Testcasenotexpectedpeername_0
	var errs []error
	if err := testcasenotexpectedpeername_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type PlainRaw struct {
		Kind  PeerKind
		Value string
	}
	type Plain Testcasenotexpectedpeername
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.kind = rawStruct.Kind
	plain.value = rawStruct.Value
	plain = plain
	*j = Testcasenotexpectedpeername(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Testcasenotexpectedpeername) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var testcasenotexpectedpeername_0 Testcasenotexpectedpeername_0
	var errs []error
	if err := testcasenotexpectedpeername_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type TestcasenotexpectedpeernameHelper struct {
		Kind  PeerKind `json:"kind"`
		Value string   `json:"value"`
	}
	type Plain Testcasenotexpectedpeername
	var helper TestcasenotexpectedpeernameHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.kind = helper.Kind
	plain.value = helper.Value
	*j = Testcasenotexpectedpeername(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Testcasenotexpectedpeername) MarshalJSON() ([]byte, error) {
	type TestcasenotexpectedpeernameMarshalHelper struct {
		Kind  PeerKind `json:"kind"`
		Value string   `json:"value"`
	}
	helper := TestcasenotexpectedpeernameMarshalHelper{
		Kind:  j.kind,
		Value: j.value,
	}
	return json.Marshal(helper)
}

type Testcaseexpectedpeername_0 = PeerName
