// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "github.com/benbjohnson/immutable"
import yaml "gopkg.in/yaml.v3"
import "time"

func NewPointerBuilder(o *Pointer) *PointerBuilder {
	if o == nil {
		return &PointerBuilder{}
	}
	return &PointerBuilder{
		boolwithdefault:          o.boolwithdefault,
		durationwithdefault:      o.durationwithdefault,
		intwithdefault:           o.intwithdefault,
		normaldefault:            o.normaldefault,
		normaloptional:           o.normaloptional,
		optionalintnonpointer:    o.optionalintnonpointer,
		optionalstringnonpointer: o.optionalstringnonpointer,
		requiredintnonpointer:    o.requiredintnonpointer,
		requiredintpointer:       o.requiredintpointer,
		slicewithdefault:         o.slicewithdefault,
		stringwithdefault:        o.stringwithdefault,
	}
}

type Pointer struct {
	// boolwithdefault corresponds to the JSON schema field "boolWithDefault".
	boolwithdefault *bool `json:"boolWithDefault,omitempty,omitzero" yaml:"boolWithDefault,omitempty" mapstructure:"boolWithDefault,omitempty"`

	// durationwithdefault corresponds to the JSON schema field "durationWithDefault".
	durationwithdefault *time.Duration `json:"durationWithDefault,omitempty,omitzero" yaml:"durationWithDefault,omitempty" mapstructure:"durationWithDefault,omitempty"`

	// intwithdefault corresponds to the JSON schema field "intWithDefault".
	intwithdefault *int `json:"intWithDefault,omitempty,omitzero" yaml:"intWithDefault,omitempty" mapstructure:"intWithDefault,omitempty"`

	// normaldefault corresponds to the JSON schema field "normalDefault".
	normaldefault string `json:"normalDefault,omitempty,omitzero" yaml:"normalDefault,omitempty" mapstructure:"normalDefault,omitempty"`

	// normaloptional corresponds to the JSON schema field "normalOptional".
	normaloptional *string `json:"normalOptional,omitempty,omitzero" yaml:"normalOptional,omitempty" mapstructure:"normalOptional,omitempty"`

	// optionalintnonpointer corresponds to the JSON schema field
	// "optionalIntNonPointer".
	optionalintnonpointer int `json:"optionalIntNonPointer,omitempty,omitzero" yaml:"optionalIntNonPointer,omitempty" mapstructure:"optionalIntNonPointer,omitempty"`

	// optionalstringnonpointer corresponds to the JSON schema field
	// "optionalStringNonPointer".
	optionalstringnonpointer string `json:"optionalStringNonPointer,omitempty,omitzero" yaml:"optionalStringNonPointer,omitempty" mapstructure:"optionalStringNonPointer,omitempty"`

	// requiredintnonpointer corresponds to the JSON schema field
	// "requiredIntNonPointer".
	requiredintnonpointer int `json:"requiredIntNonPointer" yaml:"requiredIntNonPointer" mapstructure:"requiredIntNonPointer"`

	// requiredintpointer corresponds to the JSON schema field "requiredIntPointer".
	requiredintpointer *int `json:"requiredIntPointer" yaml:"requiredIntPointer" mapstructure:"requiredIntPointer"`

	// slicewithdefault corresponds to the JSON schema field "sliceWithDefault".
	slicewithdefault *immutable.List[string] `json:"sliceWithDefault,omitempty,omitzero" yaml:"sliceWithDefault,omitempty" mapstructure:"sliceWithDefault,omitempty"`

	// stringwithdefault corresponds to the JSON schema field "stringWithDefault".
	stringwithdefault *string `json:"stringWithDefault,omitempty,omitzero" yaml:"stringWithDefault,omitempty" mapstructure:"stringWithDefault,omitempty"`
}

type PointerBuilder struct {
	boolwithdefault *bool

	durationwithdefault *time.Duration

	intwithdefault *int

	normaldefault string

	normaloptional *string

	optionalintnonpointer int

	optionalstringnonpointer string

	requiredintnonpointer int

	requiredintpointer *int

	slicewithdefault *immutable.List[string]

	stringwithdefault *string
}

func (b *PointerBuilder) Build() *Pointer {
	return &Pointer{
		boolwithdefault:          b.boolwithdefault,
		durationwithdefault:      b.durationwithdefault,
		intwithdefault:           b.intwithdefault,
		normaldefault:            b.normaldefault,
		normaloptional:           b.normaloptional,
		optionalintnonpointer:    b.optionalintnonpointer,
		optionalstringnonpointer: b.optionalstringnonpointer,
		requiredintnonpointer:    b.requiredintnonpointer,
		requiredintpointer:       b.requiredintpointer,
		slicewithdefault:         b.slicewithdefault,
		stringwithdefault:        b.stringwithdefault,
	}
}

func (b *PointerBuilder) WithBoolWithDefault(v *bool) *PointerBuilder {
	b.boolwithdefault = v
	return b
}

func (b *PointerBuilder) WithDurationWithDefault(v *time.Duration) *PointerBuilder {
	b.durationwithdefault = v
	return b
}

func (b *PointerBuilder) WithIntWithDefault(v *int) *PointerBuilder {
	b.intwithdefault = v
	return b
}

func (b *PointerBuilder) WithNormalDefault(v string) *PointerBuilder {
	b.normaldefault = v
	return b
}

func (b *PointerBuilder) WithNormalOptional(v *string) *PointerBuilder {
	b.normaloptional = v
	return b
}

func (b *PointerBuilder) WithOptionalIntNonPointer(v int) *PointerBuilder {
	b.optionalintnonpointer = v
	return b
}

func (b *PointerBuilder) WithOptionalStringNonPointer(v string) *PointerBuilder {
	b.optionalstringnonpointer = v
	return b
}

func (b *PointerBuilder) WithRequiredIntNonPointer(v int) *PointerBuilder {
	b.requiredintnonpointer = v
	return b
}

func (b *PointerBuilder) WithRequiredIntPointer(v *int) *PointerBuilder {
	b.requiredintpointer = v
	return b
}

func (b *PointerBuilder) WithSliceWithDefault(v *immutable.List[string]) *PointerBuilder {
	b.slicewithdefault = v
	return b
}

func (b *PointerBuilder) WithStringWithDefault(v *string) *PointerBuilder {
	b.stringwithdefault = v
	return b
}

func (o *Pointer) BoolWithDefault() *bool {
	return o.boolwithdefault
}

func (o *Pointer) Clone() *PointerBuilder {
	return NewPointerBuilder(o)
}

func (o *Pointer) DurationWithDefault() *time.Duration {
	return o.durationwithdefault
}

func (o *Pointer) IntWithDefault() *int {
	return o.intwithdefault
}

func (o *Pointer) NormalDefault() string {
	return o.normaldefault
}

func (o *Pointer) NormalOptional() *string {
	return o.normaloptional
}

func (o *Pointer) OptionalIntNonPointer() int {
	return o.optionalintnonpointer
}

func (o *Pointer) OptionalStringNonPointer() string {
	return o.optionalstringnonpointer
}

func (o *Pointer) RequiredIntNonPointer() int {
	return o.requiredintnonpointer
}

func (o *Pointer) RequiredIntPointer() *int {
	return o.requiredintpointer
}

func (o *Pointer) SliceWithDefault() *immutable.List[string] {
	return o.slicewithdefault
}

func (o *Pointer) StringWithDefault() *string {
	return o.stringwithdefault
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Pointer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["requiredIntNonPointer"]; raw != nil && !ok {
		return fmt.Errorf("field requiredIntNonPointer in Pointer: required")
	}
	if _, ok := raw["requiredIntPointer"]; raw != nil && !ok {
		return fmt.Errorf("field requiredIntPointer in Pointer: required")
	}
	type PointerHelper struct {
		Boolwithdefault          *bool          `json:"boolWithDefault,omitempty,omitzero"`
		Durationwithdefault      *time.Duration `json:"durationWithDefault,omitempty,omitzero"`
		Intwithdefault           *int           `json:"intWithDefault,omitempty,omitzero"`
		Normaldefault            string         `json:"normalDefault,omitempty,omitzero"`
		Normaloptional           *string        `json:"normalOptional,omitempty,omitzero"`
		Optionalintnonpointer    int            `json:"optionalIntNonPointer,omitempty,omitzero"`
		Optionalstringnonpointer string         `json:"optionalStringNonPointer,omitempty,omitzero"`
		Requiredintnonpointer    int            `json:"requiredIntNonPointer"`
		Requiredintpointer       *int           `json:"requiredIntPointer"`
		Slicewithdefault         []string       `json:"sliceWithDefault,omitempty,omitzero"`
		Stringwithdefault        *string        `json:"stringWithDefault,omitempty,omitzero"`
	}
	type Plain Pointer
	var helper PointerHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.boolwithdefault = helper.Boolwithdefault
	plain.durationwithdefault = helper.Durationwithdefault
	plain.intwithdefault = helper.Intwithdefault
	plain.normaldefault = helper.Normaldefault
	plain.normaloptional = helper.Normaloptional
	plain.optionalintnonpointer = helper.Optionalintnonpointer
	plain.optionalstringnonpointer = helper.Optionalstringnonpointer
	plain.requiredintnonpointer = helper.Requiredintnonpointer
	plain.requiredintpointer = helper.Requiredintpointer
	plain.slicewithdefault = func() *immutable.List[string] {
		if helper.Slicewithdefault == nil {
			return nil
		}
		l := make([]string, 0, len(helper.Slicewithdefault))
		for _, v := range helper.Slicewithdefault {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.stringwithdefault = helper.Stringwithdefault
	if v, ok := raw["boolWithDefault"]; !ok || v == nil {
		var defaultboolwithdefault bool = true
		plain.boolwithdefault = &defaultboolwithdefault
	}
	if v, ok := raw["durationWithDefault"]; !ok || v == nil {
		defaultDuration, err := time.ParseDuration("20s")
		if err != nil {
			return fmt.Errorf("failed to parse the \"20s\" default value for field durationWithDefault: %w", err)
		}
		plain.durationwithdefault = &defaultDuration

	}
	if v, ok := raw["intWithDefault"]; !ok || v == nil {
		var defaultintwithdefault int = 42
		plain.intwithdefault = &defaultintwithdefault
	}
	if v, ok := raw["normalDefault"]; !ok || v == nil {
		plain.normaldefault = "world"
	}
	if v, ok := raw["sliceWithDefault"]; !ok || v == nil {
		plain.slicewithdefault = immutable.NewList[string]("a", "b")
	}
	if v, ok := raw["stringWithDefault"]; !ok || v == nil {
		var defaultstringwithdefault string = "hello"
		plain.stringwithdefault = &defaultstringwithdefault
	}
	*j = Pointer(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Pointer) MarshalJSON() ([]byte, error) {
	type PointerMarshalHelper struct {
		Boolwithdefault          *bool          `json:"boolWithDefault,omitempty,omitzero"`
		Durationwithdefault      *time.Duration `json:"durationWithDefault,omitempty,omitzero"`
		Intwithdefault           *int           `json:"intWithDefault,omitempty,omitzero"`
		Normaldefault            string         `json:"normalDefault,omitempty,omitzero"`
		Normaloptional           *string        `json:"normalOptional,omitempty,omitzero"`
		Optionalintnonpointer    int            `json:"optionalIntNonPointer,omitempty,omitzero"`
		Optionalstringnonpointer string         `json:"optionalStringNonPointer,omitempty,omitzero"`
		Requiredintnonpointer    int            `json:"requiredIntNonPointer"`
		Requiredintpointer       *int           `json:"requiredIntPointer"`
		Slicewithdefault         []string       `json:"sliceWithDefault,omitempty,omitzero"`
		Stringwithdefault        *string        `json:"stringWithDefault,omitempty,omitzero"`
	}
	helper := PointerMarshalHelper{
		Boolwithdefault:          j.boolwithdefault,
		Durationwithdefault:      j.durationwithdefault,
		Intwithdefault:           j.intwithdefault,
		Normaldefault:            j.normaldefault,
		Normaloptional:           j.normaloptional,
		Optionalintnonpointer:    j.optionalintnonpointer,
		Optionalstringnonpointer: j.optionalstringnonpointer,
		Requiredintnonpointer:    j.requiredintnonpointer,
		Requiredintpointer:       j.requiredintpointer,
		Slicewithdefault: func() []string {
			if j.slicewithdefault == nil {
				return nil
			}
			lst := (*immutable.List[string])(j.slicewithdefault)
			l := make([]string, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
		Stringwithdefault: j.stringwithdefault,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Pointer) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["requiredIntNonPointer"]; raw != nil && !ok {
		return fmt.Errorf("field requiredIntNonPointer in Pointer: required")
	}
	if _, ok := raw["requiredIntPointer"]; raw != nil && !ok {
		return fmt.Errorf("field requiredIntPointer in Pointer: required")
	}
	type PlainRaw struct {
		Boolwithdefault          *bool
		Durationwithdefault      *time.Duration
		Intwithdefault           *int
		Normaldefault            string
		Normaloptional           *string
		Optionalintnonpointer    int
		Optionalstringnonpointer string
		Requiredintnonpointer    int
		Requiredintpointer       *int
		Slicewithdefault         []string
		Stringwithdefault        *string
	}
	type Plain Pointer
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.boolwithdefault = rawStruct.Boolwithdefault
	plain.durationwithdefault = rawStruct.Durationwithdefault
	plain.intwithdefault = rawStruct.Intwithdefault
	plain.normaldefault = rawStruct.Normaldefault
	plain.normaloptional = rawStruct.Normaloptional
	plain.optionalintnonpointer = rawStruct.Optionalintnonpointer
	plain.optionalstringnonpointer = rawStruct.Optionalstringnonpointer
	plain.requiredintnonpointer = rawStruct.Requiredintnonpointer
	plain.requiredintpointer = rawStruct.Requiredintpointer
	plain.slicewithdefault = func() *immutable.List[string] {
		if rawStruct.Slicewithdefault == nil {
			return nil
		}
		l := make([]string, 0, len(rawStruct.Slicewithdefault))
		for _, v := range rawStruct.Slicewithdefault {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.stringwithdefault = rawStruct.Stringwithdefault
	plain = plain
	if v, ok := raw["boolWithDefault"]; !ok || v == nil {
		var defaultboolwithdefault bool = true
		plain.boolwithdefault = &defaultboolwithdefault
	}
	if v, ok := raw["durationWithDefault"]; !ok || v == nil {
		defaultDuration, err := time.ParseDuration("20s")
		if err != nil {
			return fmt.Errorf("failed to parse the \"20s\" default value for field durationWithDefault: %w", err)
		}
		plain.durationwithdefault = &defaultDuration

	}
	if v, ok := raw["intWithDefault"]; !ok || v == nil {
		var defaultintwithdefault int = 42
		plain.intwithdefault = &defaultintwithdefault
	}
	if v, ok := raw["normalDefault"]; !ok || v == nil {
		plain.normaldefault = "world"
	}
	if v, ok := raw["sliceWithDefault"]; !ok || v == nil {
		plain.slicewithdefault = immutable.NewList[string]("a", "b")
	}
	if v, ok := raw["stringWithDefault"]; !ok || v == nil {
		var defaultstringwithdefault string = "hello"
		plain.stringwithdefault = &defaultstringwithdefault
	}
	*j = Pointer(plain)
	return nil
}
