// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "time"

type PointerJson struct {
	// boolwithdefault corresponds to the JSON schema field "boolWithDefault".
	boolwithdefault *bool `json:"boolWithDefault,omitempty,omitzero" yaml:"boolWithDefault,omitempty" mapstructure:"boolWithDefault,omitempty"`

	// durationwithdefault corresponds to the JSON schema field "durationWithDefault".
	durationwithdefault *time.Duration `json:"durationWithDefault,omitempty,omitzero" yaml:"durationWithDefault,omitempty" mapstructure:"durationWithDefault,omitempty"`

	// intwithdefault corresponds to the JSON schema field "intWithDefault".
	intwithdefault *int `json:"intWithDefault,omitempty,omitzero" yaml:"intWithDefault,omitempty" mapstructure:"intWithDefault,omitempty"`

	// normaldefault corresponds to the JSON schema field "normalDefault".
	normaldefault string `json:"normalDefault,omitempty,omitzero" yaml:"normalDefault,omitempty" mapstructure:"normalDefault,omitempty"`

	// normaloptional corresponds to the JSON schema field "normalOptional".
	normaloptional *string `json:"normalOptional,omitempty,omitzero" yaml:"normalOptional,omitempty" mapstructure:"normalOptional,omitempty"`

	// optionalintnonpointer corresponds to the JSON schema field
	// "optionalIntNonPointer".
	optionalintnonpointer int `json:"optionalIntNonPointer,omitempty,omitzero" yaml:"optionalIntNonPointer,omitempty" mapstructure:"optionalIntNonPointer,omitempty"`

	// optionalstringnonpointer corresponds to the JSON schema field
	// "optionalStringNonPointer".
	optionalstringnonpointer string `json:"optionalStringNonPointer,omitempty,omitzero" yaml:"optionalStringNonPointer,omitempty" mapstructure:"optionalStringNonPointer,omitempty"`

	// requiredintnonpointer corresponds to the JSON schema field
	// "requiredIntNonPointer".
	requiredintnonpointer int `json:"requiredIntNonPointer" yaml:"requiredIntNonPointer" mapstructure:"requiredIntNonPointer"`

	// requiredintpointer corresponds to the JSON schema field "requiredIntPointer".
	requiredintpointer *int `json:"requiredIntPointer" yaml:"requiredIntPointer" mapstructure:"requiredIntPointer"`

	// slicewithdefault corresponds to the JSON schema field "sliceWithDefault".
	slicewithdefault []string `json:"sliceWithDefault,omitempty,omitzero" yaml:"sliceWithDefault,omitempty" mapstructure:"sliceWithDefault,omitempty"`

	// stringwithdefault corresponds to the JSON schema field "stringWithDefault".
	stringwithdefault *string `json:"stringWithDefault,omitempty,omitzero" yaml:"stringWithDefault,omitempty" mapstructure:"stringWithDefault,omitempty"`
}

func (o *PointerJson) BoolWithDefault() *bool {
	return o.boolwithdefault
}

func (o *PointerJson) DurationWithDefault() *time.Duration {
	return o.durationwithdefault
}

func (o *PointerJson) IntWithDefault() *int {
	return o.intwithdefault
}

func (o *PointerJson) NormalDefault() string {
	return o.normaldefault
}

func (o *PointerJson) NormalOptional() *string {
	return o.normaloptional
}

func (o *PointerJson) OptionalIntNonPointer() int {
	return o.optionalintnonpointer
}

func (o *PointerJson) OptionalStringNonPointer() string {
	return o.optionalstringnonpointer
}

func (o *PointerJson) RequiredIntNonPointer() int {
	return o.requiredintnonpointer
}

func (o *PointerJson) RequiredIntPointer() *int {
	return o.requiredintpointer
}

func (o *PointerJson) SliceWithDefault() []string {
	return o.slicewithdefault
}

func (o *PointerJson) StringWithDefault() *string {
	return o.stringwithdefault
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PointerJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["requiredIntNonPointer"]; raw != nil && !ok {
		return fmt.Errorf("field requiredIntNonPointer in PointerJson: required")
	}
	if _, ok := raw["requiredIntPointer"]; raw != nil && !ok {
		return fmt.Errorf("field requiredIntPointer in PointerJson: required")
	}
	type PointerJsonHelper struct {
		Boolwithdefault          *bool          `json:"boolWithDefault",omitempty`
		Durationwithdefault      *time.Duration `json:"durationWithDefault",omitempty`
		Intwithdefault           *int           `json:"intWithDefault",omitempty`
		Normaldefault            string         `json:"normalDefault",omitempty`
		Normaloptional           *string        `json:"normalOptional",omitempty`
		Optionalintnonpointer    int            `json:"optionalIntNonPointer",omitempty`
		Optionalstringnonpointer string         `json:"optionalStringNonPointer",omitempty`
		Requiredintnonpointer    int            `json:"requiredIntNonPointer"`
		Requiredintpointer       *int           `json:"requiredIntPointer"`
		Slicewithdefault         []string       `json:"sliceWithDefault",omitempty`
		Stringwithdefault        *string        `json:"stringWithDefault",omitempty`
	}
	type Plain PointerJson
	var helper PointerJsonHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.boolwithdefault = helper.Boolwithdefault
	plain.durationwithdefault = helper.Durationwithdefault
	plain.intwithdefault = helper.Intwithdefault
	plain.normaldefault = helper.Normaldefault
	plain.normaloptional = helper.Normaloptional
	plain.optionalintnonpointer = helper.Optionalintnonpointer
	plain.optionalstringnonpointer = helper.Optionalstringnonpointer
	plain.requiredintnonpointer = helper.Requiredintnonpointer
	plain.requiredintpointer = helper.Requiredintpointer
	plain.slicewithdefault = helper.Slicewithdefault
	plain.stringwithdefault = helper.Stringwithdefault
	if v, ok := raw["boolWithDefault"]; !ok || v == nil {
		var defaultboolwithdefault bool = true
		plain.boolwithdefault = &defaultboolwithdefault
	}
	if v, ok := raw["durationWithDefault"]; !ok || v == nil {
		defaultDuration, err := time.ParseDuration("20s")
		if err != nil {
			return fmt.Errorf("failed to parse the \"20s\" default value for field durationWithDefault: %w", err)
		}
		plain.durationwithdefault = &defaultDuration

	}
	if v, ok := raw["intWithDefault"]; !ok || v == nil {
		var defaultintwithdefault int = 42
		plain.intwithdefault = &defaultintwithdefault
	}
	if v, ok := raw["normalDefault"]; !ok || v == nil {
		plain.normaldefault = "world"
	}
	if v, ok := raw["sliceWithDefault"]; !ok || v == nil {
		plain.slicewithdefault = []string{
			"a",
			"b",
		}
	}
	if v, ok := raw["stringWithDefault"]; !ok || v == nil {
		var defaultstringwithdefault string = "hello"
		plain.stringwithdefault = &defaultstringwithdefault
	}
	*j = PointerJson(plain)
	return nil
}
