// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

func NewRefBuilder(o *Ref) *RefBuilder {
	if o == nil {
		return &RefBuilder{}
	}
	return &RefBuilder{
		mything:  o.mything,
		mything2: o.mything2,
	}
}

func NewRefExternalFileWithSchemeBuilder(o *RefExternalFileWithScheme) *RefExternalFileWithSchemeBuilder {
	if o == nil {
		return &RefExternalFileWithSchemeBuilder{}
	}
	return &RefExternalFileWithSchemeBuilder{
		myexternalthing:        o.myexternalthing,
		someotherexternalthing: o.someotherexternalthing,
	}
}

func NewThingBuilder(o *Thing) *ThingBuilder {
	if o == nil {
		return &ThingBuilder{}
	}
	return &ThingBuilder{
		name: o.name,
	}
}

type Ref struct {
	// mything corresponds to the JSON schema field "myThing".
	mything *Thing `json:"myThing,omitempty,omitzero" yaml:"myThing,omitempty" mapstructure:"myThing,omitempty"`

	// mything2 corresponds to the JSON schema field "myThing2".
	mything2 *Thing `json:"myThing2,omitempty,omitzero" yaml:"myThing2,omitempty" mapstructure:"myThing2,omitempty"`
}

type RefBuilder struct {
	mything *Thing

	mything2 *Thing
}

func (b *RefBuilder) Build() *Ref {
	return &Ref{
		mything:  b.mything,
		mything2: b.mything2,
	}
}

func (b *RefBuilder) WithMyThing(v *Thing) *RefBuilder {
	b.mything = v
	return b
}

func (b *RefBuilder) WithMyThing2(v *Thing) *RefBuilder {
	b.mything2 = v
	return b
}

type RefExternalFileWithScheme struct {
	// myexternalthing corresponds to the JSON schema field "myExternalThing".
	myexternalthing *Thing `json:"myExternalThing,omitempty,omitzero" yaml:"myExternalThing,omitempty" mapstructure:"myExternalThing,omitempty"`

	// someotherexternalthing corresponds to the JSON schema field
	// "someOtherExternalThing".
	someotherexternalthing *Thing `json:"someOtherExternalThing,omitempty,omitzero" yaml:"someOtherExternalThing,omitempty" mapstructure:"someOtherExternalThing,omitempty"`
}

type RefExternalFileWithSchemeBuilder struct {
	myexternalthing *Thing

	someotherexternalthing *Thing
}

func (b *RefExternalFileWithSchemeBuilder) Build() *RefExternalFileWithScheme {
	return &RefExternalFileWithScheme{
		myexternalthing:        b.myexternalthing,
		someotherexternalthing: b.someotherexternalthing,
	}
}

func (b *RefExternalFileWithSchemeBuilder) WithMyExternalThing(v *Thing) *RefExternalFileWithSchemeBuilder {
	b.myexternalthing = v
	return b
}

func (b *RefExternalFileWithSchemeBuilder) WithSomeOtherExternalThing(v *Thing) *RefExternalFileWithSchemeBuilder {
	b.someotherexternalthing = v
	return b
}

func (o *RefExternalFileWithScheme) Clone() *RefExternalFileWithSchemeBuilder {
	return NewRefExternalFileWithSchemeBuilder(o)
}

func (o *RefExternalFileWithScheme) MyExternalThing() *Thing {
	return o.myexternalthing
}

func (o *RefExternalFileWithScheme) SomeOtherExternalThing() *Thing {
	return o.someotherexternalthing
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RefExternalFileWithScheme) UnmarshalYAML(value *yaml.Node) error {
	type Plain RefExternalFileWithScheme
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = RefExternalFileWithScheme(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RefExternalFileWithScheme) UnmarshalJSON(value []byte) error {
	type RefExternalFileWithSchemeHelper struct {
		Myexternalthing        *Thing `json:"myExternalThing,omitempty"`
		Someotherexternalthing *Thing `json:"someOtherExternalThing,omitempty"`
	}
	type Plain RefExternalFileWithScheme
	var helper RefExternalFileWithSchemeHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myexternalthing = helper.Myexternalthing
	plain.someotherexternalthing = helper.Someotherexternalthing
	*j = RefExternalFileWithScheme(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *RefExternalFileWithScheme) MarshalJSON() ([]byte, error) {
	type RefExternalFileWithSchemeMarshalHelper struct {
		Myexternalthing        *Thing `json:"myExternalThing,omitempty"`
		Someotherexternalthing *Thing `json:"someOtherExternalThing,omitempty"`
	}
	helper := RefExternalFileWithSchemeMarshalHelper{
		Myexternalthing:        j.myexternalthing,
		Someotherexternalthing: j.someotherexternalthing,
	}
	return json.Marshal(helper)
}

func (o *Ref) Clone() *RefBuilder {
	return NewRefBuilder(o)
}

func (o *Ref) MyThing() *Thing {
	return o.mything
}

func (o *Ref) MyThing2() *Thing {
	return o.mything2
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Ref) UnmarshalYAML(value *yaml.Node) error {
	type Plain Ref
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Ref(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Ref) UnmarshalJSON(value []byte) error {
	type RefHelper struct {
		Mything  *Thing `json:"myThing,omitempty"`
		Mything2 *Thing `json:"myThing2,omitempty"`
	}
	type Plain Ref
	var helper RefHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mything = helper.Mything
	plain.mything2 = helper.Mything2
	*j = Ref(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Ref) MarshalJSON() ([]byte, error) {
	type RefMarshalHelper struct {
		Mything  *Thing `json:"myThing,omitempty"`
		Mything2 *Thing `json:"myThing2,omitempty"`
	}
	helper := RefMarshalHelper{
		Mything:  j.mything,
		Mything2: j.mything2,
	}
	return json.Marshal(helper)
}

type Thing struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type ThingBuilder struct {
	name *string
}

func (b *ThingBuilder) Build() *Thing {
	return &Thing{
		name: b.name,
	}
}

func (b *ThingBuilder) WithName(v *string) *ThingBuilder {
	b.name = v
	return b
}

func (o *Thing) Clone() *ThingBuilder {
	return NewThingBuilder(o)
}

func (o *Thing) Name() *string {
	return o.name
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Thing) UnmarshalYAML(value *yaml.Node) error {
	type Plain Thing
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Thing(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Thing) UnmarshalJSON(value []byte) error {
	type ThingHelper struct {
		Name *string `json:"name,omitempty"`
	}
	type Plain Thing
	var helper ThingHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = Thing(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Thing) MarshalJSON() ([]byte, error) {
	type ThingMarshalHelper struct {
		Name *string `json:"name,omitempty"`
	}
	helper := ThingMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}
