// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "github.com/benbjohnson/immutable"
import yaml "gopkg.in/yaml.v3"

func NewOmitEmptyBuilder(o *OmitEmpty) *OmitEmptyBuilder {
	if o == nil {
		return &OmitEmptyBuilder{}
	}
	return &OmitEmptyBuilder{
		myarray:       o.myarray,
		myboolean:     o.myboolean,
		myinteger:     o.myinteger,
		mymap:         o.mymap,
		mynull:        o.mynull,
		mynullarray:   o.mynullarray,
		mynumber:      o.mynumber,
		myobjectarray: o.myobjectarray,
		mystring:      o.mystring,
		mystringarray: o.mystringarray,
	}
}

type OmitEmpty struct {
	// myarray corresponds to the JSON schema field "myArray".
	myarray *immutable.List[interface{}] `json:"myArray,omitempty"`

	// myboolean corresponds to the JSON schema field "myBoolean".
	myboolean *bool `json:"myBoolean,omitempty"`

	// myinteger corresponds to the JSON schema field "myInteger".
	myinteger *int `json:"myInteger,omitempty"`

	// mymap corresponds to the JSON schema field "myMap".
	mymap OmitEmptymymap `json:"myMap,omitempty"`

	// mynull corresponds to the JSON schema field "myNull".
	mynull interface{} `json:"myNull,omitempty"`

	// mynullarray corresponds to the JSON schema field "myNullArray".
	mynullarray *immutable.List[interface{}] `json:"myNullArray,omitempty"`

	// mynumber corresponds to the JSON schema field "myNumber".
	mynumber *float64 `json:"myNumber,omitempty"`

	// myobjectarray corresponds to the JSON schema field "myObjectArray".
	myobjectarray *immutable.List[OmitEmptymyobjectarrayElem] `json:"myObjectArray,omitempty"`

	// mystring corresponds to the JSON schema field "myString".
	mystring *string `json:"myString,omitempty"`

	// mystringarray corresponds to the JSON schema field "myStringArray".
	mystringarray *immutable.List[string] `json:"myStringArray,omitempty"`
}

type OmitEmptyBuilder struct {
	myarray *immutable.List[interface{}]

	myboolean *bool

	myinteger *int

	mymap OmitEmptymymap

	mynull interface{}

	mynullarray *immutable.List[interface{}]

	mynumber *float64

	myobjectarray *immutable.List[OmitEmptymyobjectarrayElem]

	mystring *string

	mystringarray *immutable.List[string]
}

func (b *OmitEmptyBuilder) Build() *OmitEmpty {
	return &OmitEmpty{
		myarray:       b.myarray,
		myboolean:     b.myboolean,
		myinteger:     b.myinteger,
		mymap:         b.mymap,
		mynull:        b.mynull,
		mynullarray:   b.mynullarray,
		mynumber:      b.mynumber,
		myobjectarray: b.myobjectarray,
		mystring:      b.mystring,
		mystringarray: b.mystringarray,
	}
}

func (b *OmitEmptyBuilder) WithMyArray(v *immutable.List[interface{}]) *OmitEmptyBuilder {
	b.myarray = v
	return b
}

func (b *OmitEmptyBuilder) WithMyBoolean(v *bool) *OmitEmptyBuilder {
	b.myboolean = v
	return b
}

func (b *OmitEmptyBuilder) WithMyInteger(v *int) *OmitEmptyBuilder {
	b.myinteger = v
	return b
}

func (b *OmitEmptyBuilder) WithMyMap(v OmitEmptymymap) *OmitEmptyBuilder {
	b.mymap = v
	return b
}

func (b *OmitEmptyBuilder) WithMyNull(v interface{}) *OmitEmptyBuilder {
	b.mynull = v
	return b
}

func (b *OmitEmptyBuilder) WithMyNullArray(v *immutable.List[interface{}]) *OmitEmptyBuilder {
	b.mynullarray = v
	return b
}

func (b *OmitEmptyBuilder) WithMyNumber(v *float64) *OmitEmptyBuilder {
	b.mynumber = v
	return b
}

func (b *OmitEmptyBuilder) WithMyObjectArray(v *immutable.List[OmitEmptymyobjectarrayElem]) *OmitEmptyBuilder {
	b.myobjectarray = v
	return b
}

func (b *OmitEmptyBuilder) WithMyString(v *string) *OmitEmptyBuilder {
	b.mystring = v
	return b
}

func (b *OmitEmptyBuilder) WithMyStringArray(v *immutable.List[string]) *OmitEmptyBuilder {
	b.mystringarray = v
	return b
}

func (o *OmitEmpty) Clone() *OmitEmptyBuilder {
	return NewOmitEmptyBuilder(o)
}

func (o *OmitEmpty) MyArray() *immutable.List[interface{}] {
	return o.myarray
}

func (o *OmitEmpty) MyBoolean() *bool {
	return o.myboolean
}

func (o *OmitEmpty) MyInteger() *int {
	return o.myinteger
}

func (o *OmitEmpty) MyMap() OmitEmptymymap {
	return o.mymap
}

func (o *OmitEmpty) MyNull() interface{} {
	return o.mynull
}

func (o *OmitEmpty) MyNullArray() *immutable.List[interface{}] {
	return o.mynullarray
}

func (o *OmitEmpty) MyNumber() *float64 {
	return o.mynumber
}

func (o *OmitEmpty) MyObjectArray() *immutable.List[OmitEmptymyobjectarrayElem] {
	return o.myobjectarray
}

func (o *OmitEmpty) MyString() *string {
	return o.mystring
}

func (o *OmitEmpty) MyStringArray() *immutable.List[string] {
	return o.mystringarray
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OmitEmpty) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type OmitEmptyHelper struct {
		Myarray       []interface{}            `json:"myArray,omitempty"`
		Myboolean     *bool                    `json:"myBoolean,omitempty"`
		Myinteger     *int                     `json:"myInteger,omitempty"`
		Mymap         map[string]float64       `json:"myMap,omitempty"`
		Mynull        interface{}              `json:"myNull,omitempty"`
		Mynullarray   []interface{}            `json:"myNullArray,omitempty"`
		Mynumber      *float64                 `json:"myNumber,omitempty"`
		Myobjectarray []map[string]interface{} `json:"myObjectArray,omitempty"`
		Mystring      *string                  `json:"myString,omitempty"`
		Mystringarray []string                 `json:"myStringArray,omitempty"`
	}
	type Plain OmitEmpty
	var helper OmitEmptyHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myarray = func() *immutable.List[interface{}] {
		if helper.Myarray == nil {
			return nil
		}
		l := make([]interface{}, 0, len(helper.Myarray))
		for _, v := range helper.Myarray {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.myboolean = helper.Myboolean
	plain.myinteger = helper.Myinteger
	plain.mymap = (OmitEmptymymap)(*immutable.NewMapOf[string](nil, helper.Mymap))
	plain.mynull = helper.Mynull
	plain.mynullarray = func() *immutable.List[interface{}] {
		if helper.Mynullarray == nil {
			return nil
		}
		l := make([]interface{}, 0, len(helper.Mynullarray))
		for _, v := range helper.Mynullarray {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.mynumber = helper.Mynumber
	plain.myobjectarray = func() *immutable.List[OmitEmptymyobjectarrayElem] {
		if helper.Myobjectarray == nil {
			return nil
		}
		l := make([]OmitEmptymyobjectarrayElem, 0, len(helper.Myobjectarray))
		for _, v := range helper.Myobjectarray {
			l = append(l, (OmitEmptymyobjectarrayElem)((OmitEmptymyobjectarrayElem)(*immutable.NewMapOf[string](nil, v))))
		}
		return immutable.NewList(l...)
	}()
	plain.mystring = helper.Mystring
	plain.mystringarray = func() *immutable.List[string] {
		if helper.Mystringarray == nil {
			return nil
		}
		l := make([]string, 0, len(helper.Mystringarray))
		for _, v := range helper.Mystringarray {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	if plain.mynull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := 0; i0 < plain.mynullarray.Len(); i0++ {
		if plain.mynullarray.Get(i0) != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = OmitEmpty(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *OmitEmpty) MarshalJSON() ([]byte, error) {
	type OmitEmptyMarshalHelper struct {
		Myarray       []interface{}            `json:"myArray,omitempty"`
		Myboolean     *bool                    `json:"myBoolean,omitempty"`
		Myinteger     *int                     `json:"myInteger,omitempty"`
		Mymap         map[string]float64       `json:"myMap,omitempty"`
		Mynull        interface{}              `json:"myNull,omitempty"`
		Mynullarray   []interface{}            `json:"myNullArray,omitempty"`
		Mynumber      *float64                 `json:"myNumber,omitempty"`
		Myobjectarray []map[string]interface{} `json:"myObjectArray,omitempty"`
		Mystring      *string                  `json:"myString,omitempty"`
		Mystringarray []string                 `json:"myStringArray,omitempty"`
	}
	helper := OmitEmptyMarshalHelper{
		Myarray: func() []interface{} {
			if j.myarray == nil {
				return nil
			}
			lst := (*immutable.List[interface{}])(j.myarray)
			l := make([]interface{}, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
		Myboolean: j.myboolean,
		Myinteger: j.myinteger,
		Mymap: func() map[string]float64 {
			m := make(map[string]float64)
			iter := (*immutable.Map[string, float64])(&j.mymap).Iterator()
			for iter.First(); !iter.Done(); {
				k, v, ok := iter.Next()
				if !ok {
					break
				}
				m[k] = v
			}
			return m
		}(),
		Mynull: j.mynull,
		Mynullarray: func() []interface{} {
			if j.mynullarray == nil {
				return nil
			}
			lst := (*immutable.List[interface{}])(j.mynullarray)
			l := make([]interface{}, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
		Mynumber: j.mynumber,
		Myobjectarray: func() []map[string]interface{} {
			if j.myobjectarray == nil {
				return nil
			}
			lst := (*immutable.List[OmitEmptymyobjectarrayElem])(j.myobjectarray)
			l := make([]map[string]interface{}, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = func() map[string]interface{} {
					m := make(map[string]interface{})
					iter := (*immutable.Map[string, interface{}])(&__elem).Iterator()
					for iter.First(); !iter.Done(); {
						k, v, ok := iter.Next()
						if !ok {
							break
						}
						m[k] = v
					}
					return m
				}()
			}
			return l
		}(),
		Mystring: j.mystring,
		Mystringarray: func() []string {
			if j.mystringarray == nil {
				return nil
			}
			lst := (*immutable.List[string])(j.mystringarray)
			l := make([]string, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *OmitEmpty) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type PlainRaw struct {
		Myarray       []interface{}
		Myboolean     *bool
		Myinteger     *int
		Mymap         map[string]float64
		Mynull        interface{}
		Mynullarray   []interface{}
		Mynumber      *float64
		Myobjectarray []map[string]interface{}
		Mystring      *string
		Mystringarray []string
	}
	type Plain OmitEmpty
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.myarray = func() *immutable.List[interface{}] {
		if rawStruct.Myarray == nil {
			return nil
		}
		l := make([]interface{}, 0, len(rawStruct.Myarray))
		for _, v := range rawStruct.Myarray {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.myboolean = rawStruct.Myboolean
	plain.myinteger = rawStruct.Myinteger
	plain.mymap = (OmitEmptymymap)(*immutable.NewMapOf[string](nil, rawStruct.Mymap))
	plain.mynull = rawStruct.Mynull
	plain.mynullarray = func() *immutable.List[interface{}] {
		if rawStruct.Mynullarray == nil {
			return nil
		}
		l := make([]interface{}, 0, len(rawStruct.Mynullarray))
		for _, v := range rawStruct.Mynullarray {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.mynumber = rawStruct.Mynumber
	plain.myobjectarray = func() *immutable.List[OmitEmptymyobjectarrayElem] {
		if rawStruct.Myobjectarray == nil {
			return nil
		}
		l := make([]OmitEmptymyobjectarrayElem, 0, len(rawStruct.Myobjectarray))
		for _, v := range rawStruct.Myobjectarray {
			l = append(l, (OmitEmptymyobjectarrayElem)((OmitEmptymyobjectarrayElem)(*immutable.NewMapOf[string](nil, v))))
		}
		return immutable.NewList(l...)
	}()
	plain.mystring = rawStruct.Mystring
	plain.mystringarray = func() *immutable.List[string] {
		if rawStruct.Mystringarray == nil {
			return nil
		}
		l := make([]string, 0, len(rawStruct.Mystringarray))
		for _, v := range rawStruct.Mystringarray {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain = plain
	if plain.mynull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := 0; i0 < plain.mynullarray.Len(); i0++ {
		if plain.mynullarray.Get(i0) != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = OmitEmpty(plain)
	return nil
}

type OmitEmptymymap immutable.Map[string, float64]

func (m OmitEmptymymap) Items() []struct {
	Key   string
	Value float64
} {
	var items []struct {
		Key   string
		Value float64
	}
	iter := (&m).Iterator()
	for iter.First(); !iter.Done(); {
		k, v, ok := iter.Next()
		if !ok {
			break
		}
		items = append(items, struct {
			Key   string
			Value float64
		}{k, v})
	}
	return items
}

func (m OmitEmptymymap) Iterator() *immutable.MapIterator[string, float64] {
	return (*immutable.Map[string, float64])(&m).Iterator()
}

type OmitEmptymyobjectarrayElem immutable.Map[string, interface{}]

func (m OmitEmptymyobjectarrayElem) Items() []struct {
	Key   string
	Value interface{}
} {
	var items []struct {
		Key   string
		Value interface{}
	}
	iter := (&m).Iterator()
	for iter.First(); !iter.Done(); {
		k, v, ok := iter.Next()
		if !ok {
			break
		}
		items = append(items, struct {
			Key   string
			Value interface{}
		}{k, v})
	}
	return items
}

func (m OmitEmptymyobjectarrayElem) Iterator() *immutable.MapIterator[string, interface{}] {
	return (*immutable.Map[string, interface{}])(&m).Iterator()
}
