// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

func NewOmitEmptyBuilder(o *OmitEmpty) *OmitEmptyBuilder {
	if o == nil {
		return &OmitEmptyBuilder{}
	}
	return &OmitEmptyBuilder{
		myarray:       o.myarray,
		myboolean:     o.myboolean,
		myinteger:     o.myinteger,
		mymap:         o.mymap,
		mynull:        o.mynull,
		mynullarray:   o.mynullarray,
		mynumber:      o.mynumber,
		myobjectarray: o.myobjectarray,
		mystring:      o.mystring,
		mystringarray: o.mystringarray,
	}
}

type OmitEmpty struct {
	// myarray corresponds to the JSON schema field "myArray".
	myarray []interface{} `json:"myArray,omitempty"`

	// myboolean corresponds to the JSON schema field "myBoolean".
	myboolean *bool `json:"myBoolean,omitempty"`

	// myinteger corresponds to the JSON schema field "myInteger".
	myinteger *int `json:"myInteger,omitempty"`

	// mymap corresponds to the JSON schema field "myMap".
	mymap OmitEmptymymap `json:"myMap,omitempty"`

	// mynull corresponds to the JSON schema field "myNull".
	mynull interface{} `json:"myNull,omitempty"`

	// mynullarray corresponds to the JSON schema field "myNullArray".
	mynullarray []interface{} `json:"myNullArray,omitempty"`

	// mynumber corresponds to the JSON schema field "myNumber".
	mynumber *float64 `json:"myNumber,omitempty"`

	// myobjectarray corresponds to the JSON schema field "myObjectArray".
	myobjectarray []OmitEmptymyobjectarrayElem `json:"myObjectArray,omitempty"`

	// mystring corresponds to the JSON schema field "myString".
	mystring *string `json:"myString,omitempty"`

	// mystringarray corresponds to the JSON schema field "myStringArray".
	mystringarray []string `json:"myStringArray,omitempty"`
}

type OmitEmptyBuilder struct {
	myarray []interface{}

	myboolean *bool

	myinteger *int

	mymap OmitEmptymymap

	mynull interface{}

	mynullarray []interface{}

	mynumber *float64

	myobjectarray []OmitEmptymyobjectarrayElem

	mystring *string

	mystringarray []string
}

func (b *OmitEmptyBuilder) Build() *OmitEmpty {
	return &OmitEmpty{
		myarray:       b.myarray,
		myboolean:     b.myboolean,
		myinteger:     b.myinteger,
		mymap:         b.mymap,
		mynull:        b.mynull,
		mynullarray:   b.mynullarray,
		mynumber:      b.mynumber,
		myobjectarray: b.myobjectarray,
		mystring:      b.mystring,
		mystringarray: b.mystringarray,
	}
}

func (b *OmitEmptyBuilder) WithMyArray(v []interface{}) *OmitEmptyBuilder {
	b.myarray = v
	return b
}

func (b *OmitEmptyBuilder) WithMyBoolean(v *bool) *OmitEmptyBuilder {
	b.myboolean = v
	return b
}

func (b *OmitEmptyBuilder) WithMyInteger(v *int) *OmitEmptyBuilder {
	b.myinteger = v
	return b
}

func (b *OmitEmptyBuilder) WithMyMap(v OmitEmptymymap) *OmitEmptyBuilder {
	b.mymap = v
	return b
}

func (b *OmitEmptyBuilder) WithMyNull(v interface{}) *OmitEmptyBuilder {
	b.mynull = v
	return b
}

func (b *OmitEmptyBuilder) WithMyNullArray(v []interface{}) *OmitEmptyBuilder {
	b.mynullarray = v
	return b
}

func (b *OmitEmptyBuilder) WithMyNumber(v *float64) *OmitEmptyBuilder {
	b.mynumber = v
	return b
}

func (b *OmitEmptyBuilder) WithMyObjectArray(v []OmitEmptymyobjectarrayElem) *OmitEmptyBuilder {
	b.myobjectarray = v
	return b
}

func (b *OmitEmptyBuilder) WithMyString(v *string) *OmitEmptyBuilder {
	b.mystring = v
	return b
}

func (b *OmitEmptyBuilder) WithMyStringArray(v []string) *OmitEmptyBuilder {
	b.mystringarray = v
	return b
}

func (o *OmitEmpty) Clone() *OmitEmptyBuilder {
	return NewOmitEmptyBuilder(o)
}

func (o *OmitEmpty) MyArray() []interface{} {
	return o.myarray
}

func (o *OmitEmpty) MyBoolean() *bool {
	return o.myboolean
}

func (o *OmitEmpty) MyInteger() *int {
	return o.myinteger
}

func (o *OmitEmpty) MyMap() OmitEmptymymap {
	return o.mymap
}

func (o *OmitEmpty) MyNull() interface{} {
	return o.mynull
}

func (o *OmitEmpty) MyNullArray() []interface{} {
	return o.mynullarray
}

func (o *OmitEmpty) MyNumber() *float64 {
	return o.mynumber
}

func (o *OmitEmpty) MyObjectArray() []OmitEmptymyobjectarrayElem {
	return o.myobjectarray
}

func (o *OmitEmpty) MyString() *string {
	return o.mystring
}

func (o *OmitEmpty) MyStringArray() []string {
	return o.mystringarray
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OmitEmpty) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type OmitEmptyHelper struct {
		Myarray       []interface{}                `json:"myArray",omitempty`
		Myboolean     *bool                        `json:"myBoolean",omitempty`
		Myinteger     *int                         `json:"myInteger",omitempty`
		Mymap         OmitEmptymymap               `json:"myMap",omitempty`
		Mynull        interface{}                  `json:"myNull",omitempty`
		Mynullarray   []interface{}                `json:"myNullArray",omitempty`
		Mynumber      *float64                     `json:"myNumber",omitempty`
		Myobjectarray []OmitEmptymyobjectarrayElem `json:"myObjectArray",omitempty`
		Mystring      *string                      `json:"myString",omitempty`
		Mystringarray []string                     `json:"myStringArray",omitempty`
	}
	type Plain OmitEmpty
	var helper OmitEmptyHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myarray = helper.Myarray
	plain.myboolean = helper.Myboolean
	plain.myinteger = helper.Myinteger
	plain.mymap = helper.Mymap
	plain.mynull = helper.Mynull
	plain.mynullarray = helper.Mynullarray
	plain.mynumber = helper.Mynumber
	plain.myobjectarray = helper.Myobjectarray
	plain.mystring = helper.Mystring
	plain.mystringarray = helper.Mystringarray
	if plain.mynull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := range plain.mynullarray {
		if plain.mynullarray[i0] != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = OmitEmpty(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *OmitEmpty) MarshalJSON() ([]byte, error) {
	type OmitEmptyMarshalHelper struct {
		Myarray       []interface{}                `json:"myArray",omitempty`
		Myboolean     *bool                        `json:"myBoolean",omitempty`
		Myinteger     *int                         `json:"myInteger",omitempty`
		Mymap         OmitEmptymymap               `json:"myMap",omitempty`
		Mynull        interface{}                  `json:"myNull",omitempty`
		Mynullarray   []interface{}                `json:"myNullArray",omitempty`
		Mynumber      *float64                     `json:"myNumber",omitempty`
		Myobjectarray []OmitEmptymyobjectarrayElem `json:"myObjectArray",omitempty`
		Mystring      *string                      `json:"myString",omitempty`
		Mystringarray []string                     `json:"myStringArray",omitempty`
	}
	helper := OmitEmptyMarshalHelper{
		Myarray:       j.myarray,
		Myboolean:     j.myboolean,
		Myinteger:     j.myinteger,
		Mymap:         j.mymap,
		Mynull:        j.mynull,
		Mynullarray:   j.mynullarray,
		Mynumber:      j.mynumber,
		Myobjectarray: j.myobjectarray,
		Mystring:      j.mystring,
		Mystringarray: j.mystringarray,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *OmitEmpty) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type Plain OmitEmpty
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.mynull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := range plain.mynullarray {
		if plain.mynullarray[i0] != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = OmitEmpty(plain)
	return nil
}

type OmitEmptymymap map[string]float64

type OmitEmptymyobjectarrayElem map[string]interface{}
