// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

func NewObjectNestedBuilder(o *ObjectNested) *ObjectNestedBuilder {
	if o == nil {
		return &ObjectNestedBuilder{}
	}
	return &ObjectNestedBuilder{
		myobject: o.myobject,
	}
}

func NewObjectNestedmyobjectBuilder(o *ObjectNestedmyobject) *ObjectNestedmyobjectBuilder {
	if o == nil {
		return &ObjectNestedmyobjectBuilder{}
	}
	return &ObjectNestedmyobjectBuilder{
		myobject: o.myobject,
	}
}

func NewObjectNestedmyobjectmyobjectBuilder(o *ObjectNestedmyobjectmyobject) *ObjectNestedmyobjectmyobjectBuilder {
	if o == nil {
		return &ObjectNestedmyobjectmyobjectBuilder{}
	}
	return &ObjectNestedmyobjectmyobjectBuilder{
		mystring: o.mystring,
	}
}

type ObjectNested struct {
	// myobject corresponds to the JSON schema field "myObject".
	myobject *ObjectNestedmyobject `json:"myObject,omitempty,omitzero" yaml:"myObject,omitempty" mapstructure:"myObject,omitempty"`
}

type ObjectNestedBuilder struct {
	myobject *ObjectNestedmyobject
}

func (b *ObjectNestedBuilder) Build() *ObjectNested {
	return &ObjectNested{
		myobject: b.myobject,
	}
}

func (b *ObjectNestedBuilder) WithMyObject(v *ObjectNestedmyobject) *ObjectNestedBuilder {
	b.myobject = v
	return b
}

func (o *ObjectNested) Clone() *ObjectNestedBuilder {
	return NewObjectNestedBuilder(o)
}

func (o *ObjectNested) MyObject() *ObjectNestedmyobject {
	return o.myobject
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ObjectNested) UnmarshalYAML(value *yaml.Node) error {
	type Plain ObjectNested
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = ObjectNested(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ObjectNested) UnmarshalJSON(value []byte) error {
	type ObjectNestedHelper struct {
		Myobject *ObjectNestedmyobject `json:"myObject,omitempty"`
	}
	type Plain ObjectNested
	var helper ObjectNestedHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myobject = helper.Myobject
	*j = ObjectNested(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *ObjectNested) MarshalJSON() ([]byte, error) {
	type ObjectNestedMarshalHelper struct {
		Myobject *ObjectNestedmyobject `json:"myObject,omitempty"`
	}
	helper := ObjectNestedMarshalHelper{
		Myobject: j.myobject,
	}
	return json.Marshal(helper)
}

type ObjectNestedmyobject struct {
	// myobject corresponds to the JSON schema field "myObject".
	myobject *ObjectNestedmyobjectmyobject `json:"myObject,omitempty,omitzero" yaml:"myObject,omitempty" mapstructure:"myObject,omitempty"`
}

type ObjectNestedmyobjectBuilder struct {
	myobject *ObjectNestedmyobjectmyobject
}

func (b *ObjectNestedmyobjectBuilder) Build() *ObjectNestedmyobject {
	return &ObjectNestedmyobject{
		myobject: b.myobject,
	}
}

func (b *ObjectNestedmyobjectBuilder) WithMyObject(v *ObjectNestedmyobjectmyobject) *ObjectNestedmyobjectBuilder {
	b.myobject = v
	return b
}

func (o *ObjectNestedmyobject) Clone() *ObjectNestedmyobjectBuilder {
	return NewObjectNestedmyobjectBuilder(o)
}

func (o *ObjectNestedmyobject) MyObject() *ObjectNestedmyobjectmyobject {
	return o.myobject
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ObjectNestedmyobject) UnmarshalJSON(value []byte) error {
	type ObjectNestedmyobjectHelper struct {
		Myobject *ObjectNestedmyobjectmyobject `json:"myObject,omitempty"`
	}
	type Plain ObjectNestedmyobject
	var helper ObjectNestedmyobjectHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myobject = helper.Myobject
	*j = ObjectNestedmyobject(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *ObjectNestedmyobject) MarshalJSON() ([]byte, error) {
	type ObjectNestedmyobjectMarshalHelper struct {
		Myobject *ObjectNestedmyobjectmyobject `json:"myObject,omitempty"`
	}
	helper := ObjectNestedmyobjectMarshalHelper{
		Myobject: j.myobject,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ObjectNestedmyobject) UnmarshalYAML(value *yaml.Node) error {
	type Plain ObjectNestedmyobject
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = ObjectNestedmyobject(plain)
	return nil
}

type ObjectNestedmyobjectmyobject struct {
	// mystring corresponds to the JSON schema field "myString".
	mystring *string `json:"myString,omitempty,omitzero" yaml:"myString,omitempty" mapstructure:"myString,omitempty"`
}

type ObjectNestedmyobjectmyobjectBuilder struct {
	mystring *string
}

func (b *ObjectNestedmyobjectmyobjectBuilder) Build() *ObjectNestedmyobjectmyobject {
	return &ObjectNestedmyobjectmyobject{
		mystring: b.mystring,
	}
}

func (b *ObjectNestedmyobjectmyobjectBuilder) WithMyString(v *string) *ObjectNestedmyobjectmyobjectBuilder {
	b.mystring = v
	return b
}

func (o *ObjectNestedmyobjectmyobject) Clone() *ObjectNestedmyobjectmyobjectBuilder {
	return NewObjectNestedmyobjectmyobjectBuilder(o)
}

func (o *ObjectNestedmyobjectmyobject) MyString() *string {
	return o.mystring
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ObjectNestedmyobjectmyobject) UnmarshalYAML(value *yaml.Node) error {
	type Plain ObjectNestedmyobjectmyobject
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = ObjectNestedmyobjectmyobject(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ObjectNestedmyobjectmyobject) UnmarshalJSON(value []byte) error {
	type ObjectNestedmyobjectmyobjectHelper struct {
		Mystring *string `json:"myString,omitempty"`
	}
	type Plain ObjectNestedmyobjectmyobject
	var helper ObjectNestedmyobjectmyobjectHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mystring = helper.Mystring
	*j = ObjectNestedmyobjectmyobject(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *ObjectNestedmyobjectmyobject) MarshalJSON() ([]byte, error) {
	type ObjectNestedmyobjectmyobjectMarshalHelper struct {
		Mystring *string `json:"myString,omitempty"`
	}
	helper := ObjectNestedmyobjectmyobjectMarshalHelper{
		Mystring: j.mystring,
	}
	return json.Marshal(helper)
}
