// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "dt"
import "encoding/json"
import "fmt"
import "github.com/benbjohnson/immutable"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type DomainState struct {
	// allchanges corresponds to the JSON schema field "allChanges".
	allchanges DomainStateallchanges `json:"allChanges,omitempty,omitzero" yaml:"allChanges,omitempty" mapstructure:"allChanges,omitempty"`

	// architecture corresponds to the JSON schema field "architecture".
	architecture *dt.Arch `json:"architecture,omitempty,omitzero" yaml:"architecture,omitempty" mapstructure:"architecture,omitempty"`

	// codeoutputs corresponds to the JSON schema field "codeOutputs".
	codeoutputs *immutable.List[dt.Coder] `json:"codeOutputs,omitempty,omitzero" yaml:"codeOutputs,omitempty" mapstructure:"codeOutputs,omitempty"`

	// codesummaries corresponds to the JSON schema field "codeSummaries".
	codesummaries *immutable.List[string] `json:"codeSummaries,omitempty,omitzero" yaml:"codeSummaries,omitempty" mapstructure:"codeSummaries,omitempty"`

	// codesummary corresponds to the JSON schema field "codeSummary".
	codesummary string `json:"codeSummary,omitempty,omitzero" yaml:"codeSummary,omitempty" mapstructure:"codeSummary,omitempty"`

	// finalfeedback corresponds to the JSON schema field "finalFeedback".
	finalfeedback *dt.ArchFinal `json:"finalFeedback,omitempty,omitzero" yaml:"finalFeedback,omitempty" mapstructure:"finalFeedback,omitempty"`

	// finalreviewpassed corresponds to the JSON schema field "finalReviewPassed".
	finalreviewpassed bool `json:"finalReviewPassed,omitempty,omitzero" yaml:"finalReviewPassed,omitempty" mapstructure:"finalReviewPassed,omitempty"`

	// mergedsummaries corresponds to the JSON schema field "mergedSummaries".
	mergedsummaries string `json:"mergedSummaries,omitempty,omitzero" yaml:"mergedSummaries,omitempty" mapstructure:"mergedSummaries,omitempty"`

	// plan corresponds to the JSON schema field "plan".
	plan *dt.Plan `json:"plan,omitempty,omitzero" yaml:"plan,omitempty" mapstructure:"plan,omitempty"`

	// pmfilepath corresponds to the JSON schema field "pmFilepath".
	pmfilepath string `json:"pmFilepath,omitempty,omitzero" yaml:"pmFilepath,omitempty" mapstructure:"pmFilepath,omitempty"`

	// techleadreviewiter corresponds to the JSON schema field "techLeadReviewIter".
	techleadreviewiter int `json:"techLeadReviewIter,omitempty,omitzero" yaml:"techLeadReviewIter,omitempty" mapstructure:"techLeadReviewIter,omitempty"`

	// techleadreviewresult corresponds to the JSON schema field
	// "techLeadReviewResult".
	techleadreviewresult *dt.TechLeadFinal `json:"techLeadReviewResult,omitempty,omitzero" yaml:"techLeadReviewResult,omitempty" mapstructure:"techLeadReviewResult,omitempty"`

	// techleadrevisioncycle corresponds to the JSON schema field
	// "techLeadRevisionCycle".
	techleadrevisioncycle bool `json:"techLeadRevisionCycle,omitempty,omitzero" yaml:"techLeadRevisionCycle,omitempty" mapstructure:"techLeadRevisionCycle,omitempty"`

	// wrappedcodertask corresponds to the JSON schema field "wrappedCoderTask".
	wrappedcodertask string `json:"wrappedCoderTask,omitempty,omitzero" yaml:"wrappedCoderTask,omitempty" mapstructure:"wrappedCoderTask,omitempty"`

	// wrappedtask corresponds to the JSON schema field "wrappedTask".
	wrappedtask string `json:"wrappedTask,omitempty,omitzero" yaml:"wrappedTask,omitempty" mapstructure:"wrappedTask,omitempty"`
}

type DomainStateBuilder struct {
	allchanges DomainStateallchanges

	architecture *dt.Arch

	codeoutputs *immutable.List[dt.Coder]

	codesummaries *immutable.List[string]

	codesummary string

	finalfeedback *dt.ArchFinal

	finalreviewpassed bool

	mergedsummaries string

	plan *dt.Plan

	pmfilepath string

	techleadreviewiter int

	techleadreviewresult *dt.TechLeadFinal

	techleadrevisioncycle bool

	wrappedcodertask string

	wrappedtask string
}

func (b *DomainStateBuilder) Build() *DomainState {
	return &DomainState{
		allchanges:            b.allchanges,
		architecture:          b.architecture,
		codeoutputs:           b.codeoutputs,
		codesummaries:         b.codesummaries,
		codesummary:           b.codesummary,
		finalfeedback:         b.finalfeedback,
		finalreviewpassed:     b.finalreviewpassed,
		mergedsummaries:       b.mergedsummaries,
		plan:                  b.plan,
		pmfilepath:            b.pmfilepath,
		techleadreviewiter:    b.techleadreviewiter,
		techleadreviewresult:  b.techleadreviewresult,
		techleadrevisioncycle: b.techleadrevisioncycle,
		wrappedcodertask:      b.wrappedcodertask,
		wrappedtask:           b.wrappedtask,
	}
}

func (b *DomainStateBuilder) WithAllChanges(v DomainStateallchanges) *DomainStateBuilder {
	b.allchanges = v
	return b
}

func (b *DomainStateBuilder) WithArchitecture(v *dt.Arch) *DomainStateBuilder {
	b.architecture = v
	return b
}

func (b *DomainStateBuilder) WithCodeOutputs(v *immutable.List[dt.Coder]) *DomainStateBuilder {
	b.codeoutputs = v
	return b
}

func (b *DomainStateBuilder) WithCodeSummaries(v *immutable.List[string]) *DomainStateBuilder {
	b.codesummaries = v
	return b
}

func (b *DomainStateBuilder) WithCodeSummary(v string) *DomainStateBuilder {
	b.codesummary = v
	return b
}

func (b *DomainStateBuilder) WithFinalFeedback(v *dt.ArchFinal) *DomainStateBuilder {
	b.finalfeedback = v
	return b
}

func (b *DomainStateBuilder) WithFinalReviewPassed(v bool) *DomainStateBuilder {
	b.finalreviewpassed = v
	return b
}

func (b *DomainStateBuilder) WithMergedSummaries(v string) *DomainStateBuilder {
	b.mergedsummaries = v
	return b
}

func (b *DomainStateBuilder) WithPlan(v *dt.Plan) *DomainStateBuilder {
	b.plan = v
	return b
}

func (b *DomainStateBuilder) WithPmFilepath(v string) *DomainStateBuilder {
	b.pmfilepath = v
	return b
}

func (b *DomainStateBuilder) WithTechLeadReviewIter(v int) *DomainStateBuilder {
	b.techleadreviewiter = v
	return b
}

func (b *DomainStateBuilder) WithTechLeadReviewResult(v *dt.TechLeadFinal) *DomainStateBuilder {
	b.techleadreviewresult = v
	return b
}

func (b *DomainStateBuilder) WithTechLeadRevisionCycle(v bool) *DomainStateBuilder {
	b.techleadrevisioncycle = v
	return b
}

func (b *DomainStateBuilder) WithWrappedCoderTask(v string) *DomainStateBuilder {
	b.wrappedcodertask = v
	return b
}

func (b *DomainStateBuilder) WithWrappedTask(v string) *DomainStateBuilder {
	b.wrappedtask = v
	return b
}

func (o *DomainState) AllChanges() DomainStateallchanges {
	return o.allchanges
}

func (o *DomainState) Architecture() *dt.Arch {
	return o.architecture
}

func (o *DomainState) Clone() *DomainStateBuilder {
	return NewDomainStateBuilder(o)
}

func (o *DomainState) CodeOutputs() *immutable.List[dt.Coder] {
	return o.codeoutputs
}

func (o *DomainState) CodeSummaries() *immutable.List[string] {
	return o.codesummaries
}

func (o *DomainState) CodeSummary() string {
	return o.codesummary
}

func (o *DomainState) FinalFeedback() *dt.ArchFinal {
	return o.finalfeedback
}

func (o *DomainState) FinalReviewPassed() bool {
	return o.finalreviewpassed
}

func (o *DomainState) MergedSummaries() string {
	return o.mergedsummaries
}

func (o *DomainState) Plan() *dt.Plan {
	return o.plan
}

func (o *DomainState) PmFilepath() string {
	return o.pmfilepath
}

func (o *DomainState) TechLeadReviewIter() int {
	return o.techleadreviewiter
}

func (o *DomainState) TechLeadReviewResult() *dt.TechLeadFinal {
	return o.techleadreviewresult
}

func (o *DomainState) TechLeadRevisionCycle() bool {
	return o.techleadrevisioncycle
}

func (o *DomainState) WrappedCoderTask() string {
	return o.wrappedcodertask
}

func (o *DomainState) WrappedTask() string {
	return o.wrappedtask
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *DomainState) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Allchanges            map[string]string
		Architecture          *dt.Arch
		Codeoutputs           []dt.Coder
		Codesummaries         []string
		Codesummary           string
		Finalfeedback         *dt.ArchFinal
		Finalreviewpassed     bool
		Mergedsummaries       string
		Plan                  *dt.Plan
		Pmfilepath            string
		Techleadreviewiter    int
		Techleadreviewresult  *dt.TechLeadFinal
		Techleadrevisioncycle bool
		Wrappedcodertask      string
		Wrappedtask           string
	}
	type Plain DomainState
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.allchanges = (DomainStateallchanges)(*immutable.NewMapOf[string](nil, rawStruct.Allchanges))
	plain.architecture = rawStruct.Architecture
	plain.codeoutputs = func() *immutable.List[dt.Coder] {
		if rawStruct.Codeoutputs == nil {
			return nil
		}
		l := make([]dt.Coder, 0, len(rawStruct.Codeoutputs))
		for _, v := range rawStruct.Codeoutputs {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.codesummaries = func() *immutable.List[string] {
		if rawStruct.Codesummaries == nil {
			return nil
		}
		l := make([]string, 0, len(rawStruct.Codesummaries))
		for _, v := range rawStruct.Codesummaries {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.codesummary = rawStruct.Codesummary
	plain.finalfeedback = rawStruct.Finalfeedback
	plain.finalreviewpassed = rawStruct.Finalreviewpassed
	plain.mergedsummaries = rawStruct.Mergedsummaries
	plain.plan = rawStruct.Plan
	plain.pmfilepath = rawStruct.Pmfilepath
	plain.techleadreviewiter = rawStruct.Techleadreviewiter
	plain.techleadreviewresult = rawStruct.Techleadreviewresult
	plain.techleadrevisioncycle = rawStruct.Techleadrevisioncycle
	plain.wrappedcodertask = rawStruct.Wrappedcodertask
	plain.wrappedtask = rawStruct.Wrappedtask
	plain = plain
	*j = DomainState(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DomainState) UnmarshalJSON(value []byte) error {
	type DomainStateHelper struct {
		Allchanges            map[string]string `json:"allChanges,omitempty,omitzero"`
		Architecture          *dt.Arch          `json:"architecture,omitempty,omitzero"`
		Codeoutputs           []dt.Coder        `json:"codeOutputs,omitempty,omitzero"`
		Codesummaries         []string          `json:"codeSummaries,omitempty,omitzero"`
		Codesummary           string            `json:"codeSummary,omitempty,omitzero"`
		Finalfeedback         *dt.ArchFinal     `json:"finalFeedback,omitempty,omitzero"`
		Finalreviewpassed     bool              `json:"finalReviewPassed,omitempty,omitzero"`
		Mergedsummaries       string            `json:"mergedSummaries,omitempty,omitzero"`
		Plan                  *dt.Plan          `json:"plan,omitempty,omitzero"`
		Pmfilepath            string            `json:"pmFilepath,omitempty,omitzero"`
		Techleadreviewiter    int               `json:"techLeadReviewIter,omitempty,omitzero"`
		Techleadreviewresult  *dt.TechLeadFinal `json:"techLeadReviewResult,omitempty,omitzero"`
		Techleadrevisioncycle bool              `json:"techLeadRevisionCycle,omitempty,omitzero"`
		Wrappedcodertask      string            `json:"wrappedCoderTask,omitempty,omitzero"`
		Wrappedtask           string            `json:"wrappedTask,omitempty,omitzero"`
	}
	type Plain DomainState
	var helper DomainStateHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.allchanges = (DomainStateallchanges)(*immutable.NewMapOf[string](nil, helper.Allchanges))
	plain.architecture = helper.Architecture
	plain.codeoutputs = func() *immutable.List[dt.Coder] {
		if helper.Codeoutputs == nil {
			return nil
		}
		l := make([]dt.Coder, 0, len(helper.Codeoutputs))
		for _, v := range helper.Codeoutputs {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.codesummaries = func() *immutable.List[string] {
		if helper.Codesummaries == nil {
			return nil
		}
		l := make([]string, 0, len(helper.Codesummaries))
		for _, v := range helper.Codesummaries {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.codesummary = helper.Codesummary
	plain.finalfeedback = helper.Finalfeedback
	plain.finalreviewpassed = helper.Finalreviewpassed
	plain.mergedsummaries = helper.Mergedsummaries
	plain.plan = helper.Plan
	plain.pmfilepath = helper.Pmfilepath
	plain.techleadreviewiter = helper.Techleadreviewiter
	plain.techleadreviewresult = helper.Techleadreviewresult
	plain.techleadrevisioncycle = helper.Techleadrevisioncycle
	plain.wrappedcodertask = helper.Wrappedcodertask
	plain.wrappedtask = helper.Wrappedtask
	*j = DomainState(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *DomainState) MarshalJSON() ([]byte, error) {
	type DomainStateMarshalHelper struct {
		Allchanges            map[string]string `json:"allChanges,omitempty,omitzero"`
		Architecture          *dt.Arch          `json:"architecture,omitempty,omitzero"`
		Codeoutputs           []dt.Coder        `json:"codeOutputs,omitempty,omitzero"`
		Codesummaries         []string          `json:"codeSummaries,omitempty,omitzero"`
		Codesummary           string            `json:"codeSummary,omitempty,omitzero"`
		Finalfeedback         *dt.ArchFinal     `json:"finalFeedback,omitempty,omitzero"`
		Finalreviewpassed     bool              `json:"finalReviewPassed,omitempty,omitzero"`
		Mergedsummaries       string            `json:"mergedSummaries,omitempty,omitzero"`
		Plan                  *dt.Plan          `json:"plan,omitempty,omitzero"`
		Pmfilepath            string            `json:"pmFilepath,omitempty,omitzero"`
		Techleadreviewiter    int               `json:"techLeadReviewIter,omitempty,omitzero"`
		Techleadreviewresult  *dt.TechLeadFinal `json:"techLeadReviewResult,omitempty,omitzero"`
		Techleadrevisioncycle bool              `json:"techLeadRevisionCycle,omitempty,omitzero"`
		Wrappedcodertask      string            `json:"wrappedCoderTask,omitempty,omitzero"`
		Wrappedtask           string            `json:"wrappedTask,omitempty,omitzero"`
	}
	helper := DomainStateMarshalHelper{
		Allchanges: func() map[string]string {
			m := make(map[string]string)
			iter := (*immutable.Map[string, string])(&j.allchanges).Iterator()
			for iter.First(); !iter.Done(); {
				k, v, ok := iter.Next()
				if !ok {
					break
				}
				m[k] = v
			}
			return m
		}(),
		Architecture: j.architecture,
		Codeoutputs: func() []dt.Coder {
			if j.codeoutputs == nil {
				return nil
			}
			lst := (*immutable.List[dt.Coder])(j.codeoutputs)
			l := make([]dt.Coder, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
		Codesummaries: func() []string {
			if j.codesummaries == nil {
				return nil
			}
			lst := (*immutable.List[string])(j.codesummaries)
			l := make([]string, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
		Codesummary:           j.codesummary,
		Finalfeedback:         j.finalfeedback,
		Finalreviewpassed:     j.finalreviewpassed,
		Mergedsummaries:       j.mergedsummaries,
		Plan:                  j.plan,
		Pmfilepath:            j.pmfilepath,
		Techleadreviewiter:    j.techleadreviewiter,
		Techleadreviewresult:  j.techleadreviewresult,
		Techleadrevisioncycle: j.techleadrevisioncycle,
		Wrappedcodertask:      j.wrappedcodertask,
		Wrappedtask:           j.wrappedtask,
	}
	return json.Marshal(helper)
}

type DomainStateallchanges immutable.Map[string, string]

func (m DomainStateallchanges) Items() []struct {
	Key   string
	Value string
} {
	var items []struct {
		Key   string
		Value string
	}
	iter := (&m).Iterator()
	for iter.First(); !iter.Done(); {
		k, v, ok := iter.Next()
		if !ok {
			break
		}
		items = append(items, struct {
			Key   string
			Value string
		}{k, v})
	}
	return items
}

func (m DomainStateallchanges) Iterator() *immutable.MapIterator[string, string] {
	return (*immutable.Map[string, string])(&m).Iterator()
}

func NewDomainStateBuilder(o *DomainState) *DomainStateBuilder {
	if o == nil {
		return &DomainStateBuilder{}
	}
	return &DomainStateBuilder{
		allchanges:            o.allchanges,
		architecture:          o.architecture,
		codeoutputs:           o.codeoutputs,
		codesummaries:         o.codesummaries,
		codesummary:           o.codesummary,
		finalfeedback:         o.finalfeedback,
		finalreviewpassed:     o.finalreviewpassed,
		mergedsummaries:       o.mergedsummaries,
		plan:                  o.plan,
		pmfilepath:            o.pmfilepath,
		techleadreviewiter:    o.techleadreviewiter,
		techleadreviewresult:  o.techleadreviewresult,
		techleadrevisioncycle: o.techleadrevisioncycle,
		wrappedcodertask:      o.wrappedcodertask,
		wrappedtask:           o.wrappedtask,
	}
}

func NewPayloadDataBuilder(o *PayloadData) *PayloadDataBuilder {
	if o == nil {
		return &PayloadDataBuilder{}
	}
	return &PayloadDataBuilder{
		allchanges:                     o.allchanges,
		archfinal:                      o.archfinal,
		archreview:                     o.archreview,
		codereview:                     o.codereview,
		coderoutputs:                   o.coderoutputs,
		consistencyreview:              o.consistencyreview,
		decompositionreview:            o.decompositionreview,
		docsuffix:                      o.docsuffix,
		factreview:                     o.factreview,
		findingslist:                   o.findingslist,
		gapanalysisreview:              o.gapanalysisreview,
		hastechleadfinalreview:         o.hastechleadfinalreview,
		initialpromptcontext:           o.initialpromptcontext,
		investigationplanqualityreview: o.investigationplanqualityreview,
		investigationreport:            o.investigationreport,
		investigatorfindings:           o.investigatorfindings,
		itercount:                      o.itercount,
		planreview:                     o.planreview,
		revisioninvprefix:              o.revisioninvprefix,
		revisionprompt:                 o.revisionprompt,
		techleadfinalreview:            o.techleadfinalreview,
		tliter:                         o.tliter,
		workstreamelem:                 o.workstreamelem,
	}
}

func NewTestSchemaBuilder(o *TestSchema) *TestSchemaBuilder {
	if o == nil {
		return &TestSchemaBuilder{}
	}
	return &TestSchemaBuilder{
		codereviewiteration: o.codereviewiteration,
		domainid:            o.domainid,
		domainindex:         o.domainindex,
		iteration:           o.iteration,
		payload:             o.payload,
		reviewiteration:     o.reviewiteration,
		state:               o.state,
		steptype:            o.steptype,
		workstreamid:        o.workstreamid,
		workstreamindex:     o.workstreamindex,
	}
}

func NewWorkflowStateBuilder(o *WorkflowState) *WorkflowStateBuilder {
	if o == nil {
		return &WorkflowStateBuilder{}
	}
	return &WorkflowStateBuilder{
		choices:                o.choices,
		completedworkstreams:   o.completedworkstreams,
		decompositionresult:    o.decompositionresult,
		domaincurrentstage:     o.domaincurrentstage,
		domainiterationindex:   o.domainiterationindex,
		domainiterationtotal:   o.domainiterationtotal,
		domains:                o.domains,
		finalinvestigationtask: o.finalinvestigationtask,
		investigationplan:      o.investigationplan,
		investigationresults:   o.investigationresults,
		out:                    o.out,
		pmfilepath:             o.pmfilepath,
		rephrasedtask:          o.rephrasedtask,
		speculativeexpansions:  o.speculativeexpansions,
		subdir:                 o.subdir,
		task:                   o.task,
		techleaddocsuffix:      o.techleaddocsuffix,
		workstreams:            o.workstreams,
	}
}

type PayloadData struct {
	// allchanges corresponds to the JSON schema field "allChanges".
	allchanges PayloadDataallchanges `json:"allChanges,omitempty,omitzero" yaml:"allChanges,omitempty" mapstructure:"allChanges,omitempty"`

	// archfinal corresponds to the JSON schema field "archFinal".
	archfinal *dt.ArchFinal `json:"archFinal,omitempty,omitzero" yaml:"archFinal,omitempty" mapstructure:"archFinal,omitempty"`

	// archreview corresponds to the JSON schema field "archReview".
	archreview *dt.ArchReview `json:"archReview,omitempty,omitzero" yaml:"archReview,omitempty" mapstructure:"archReview,omitempty"`

	// codereview corresponds to the JSON schema field "codeReview".
	codereview *dt.CodeReview `json:"codeReview,omitempty,omitzero" yaml:"codeReview,omitempty" mapstructure:"codeReview,omitempty"`

	// coderoutputs corresponds to the JSON schema field "coderOutputs".
	coderoutputs *immutable.List[dt.Coder] `json:"coderOutputs,omitempty,omitzero" yaml:"coderOutputs,omitempty" mapstructure:"coderOutputs,omitempty"`

	// consistencyreview corresponds to the JSON schema field "consistencyReview".
	consistencyreview *dt.SynthesisConsistencyReview `json:"consistencyReview,omitempty,omitzero" yaml:"consistencyReview,omitempty" mapstructure:"consistencyReview,omitempty"`

	// decompositionreview corresponds to the JSON schema field "decompositionReview".
	decompositionreview *dt.SystemDecompositionReview `json:"decompositionReview,omitempty,omitzero" yaml:"decompositionReview,omitempty" mapstructure:"decompositionReview,omitempty"`

	// docsuffix corresponds to the JSON schema field "docSuffix".
	docsuffix string `json:"docSuffix,omitempty,omitzero" yaml:"docSuffix,omitempty" mapstructure:"docSuffix,omitempty"`

	// factreview corresponds to the JSON schema field "factReview".
	factreview *dt.FactCheckingReview `json:"factReview,omitempty,omitzero" yaml:"factReview,omitempty" mapstructure:"factReview,omitempty"`

	// findingslist corresponds to the JSON schema field "findingsList".
	findingslist *immutable.List[dt.InvestigatorFindings] `json:"findingsList,omitempty,omitzero" yaml:"findingsList,omitempty" mapstructure:"findingsList,omitempty"`

	// gapanalysisreview corresponds to the JSON schema field "gapAnalysisReview".
	gapanalysisreview *dt.GapAnalysisReview `json:"gapAnalysisReview,omitempty,omitzero" yaml:"gapAnalysisReview,omitempty" mapstructure:"gapAnalysisReview,omitempty"`

	// hastechleadfinalreview corresponds to the JSON schema field
	// "hasTechLeadFinalReview".
	hastechleadfinalreview bool `json:"hasTechLeadFinalReview,omitempty,omitzero" yaml:"hasTechLeadFinalReview,omitempty" mapstructure:"hasTechLeadFinalReview,omitempty"`

	// initialpromptcontext corresponds to the JSON schema field
	// "initialPromptContext".
	initialpromptcontext string `json:"initialPromptContext,omitempty,omitzero" yaml:"initialPromptContext,omitempty" mapstructure:"initialPromptContext,omitempty"`

	// investigationplanqualityreview corresponds to the JSON schema field
	// "investigationPlanQualityReview".
	investigationplanqualityreview *dt.InvestigationPlanQualityReview `json:"investigationPlanQualityReview,omitempty,omitzero" yaml:"investigationPlanQualityReview,omitempty" mapstructure:"investigationPlanQualityReview,omitempty"`

	// investigationreport corresponds to the JSON schema field "investigationReport".
	investigationreport *dt.InvestigationReport `json:"investigationReport,omitempty,omitzero" yaml:"investigationReport,omitempty" mapstructure:"investigationReport,omitempty"`

	// investigatorfindings corresponds to the JSON schema field
	// "investigatorFindings".
	investigatorfindings *dt.InvestigatorFindings `json:"investigatorFindings,omitempty,omitzero" yaml:"investigatorFindings,omitempty" mapstructure:"investigatorFindings,omitempty"`

	// itercount corresponds to the JSON schema field "iterCount".
	itercount int `json:"iterCount,omitempty,omitzero" yaml:"iterCount,omitempty" mapstructure:"iterCount,omitempty"`

	// planreview corresponds to the JSON schema field "planReview".
	planreview *dt.PlanReview `json:"planReview,omitempty,omitzero" yaml:"planReview,omitempty" mapstructure:"planReview,omitempty"`

	// revisioninvprefix corresponds to the JSON schema field "revisionInvPrefix".
	revisioninvprefix string `json:"revisionInvPrefix,omitempty,omitzero" yaml:"revisionInvPrefix,omitempty" mapstructure:"revisionInvPrefix,omitempty"`

	// revisionprompt corresponds to the JSON schema field "revisionPrompt".
	revisionprompt string `json:"revisionPrompt,omitempty,omitzero" yaml:"revisionPrompt,omitempty" mapstructure:"revisionPrompt,omitempty"`

	// techleadfinalreview corresponds to the JSON schema field "techLeadFinalReview".
	techleadfinalreview *dt.TechLeadFinal `json:"techLeadFinalReview,omitempty,omitzero" yaml:"techLeadFinalReview,omitempty" mapstructure:"techLeadFinalReview,omitempty"`

	// tliter corresponds to the JSON schema field "tlIter".
	tliter int `json:"tlIter,omitempty,omitzero" yaml:"tlIter,omitempty" mapstructure:"tlIter,omitempty"`

	// workstreamelem corresponds to the JSON schema field "workstreamElem".
	workstreamelem *dt.InvestigatorPlanworkstreamsElem `json:"workstreamElem,omitempty,omitzero" yaml:"workstreamElem,omitempty" mapstructure:"workstreamElem,omitempty"`
}

type PayloadDataBuilder struct {
	allchanges PayloadDataallchanges

	archfinal *dt.ArchFinal

	archreview *dt.ArchReview

	codereview *dt.CodeReview

	coderoutputs *immutable.List[dt.Coder]

	consistencyreview *dt.SynthesisConsistencyReview

	decompositionreview *dt.SystemDecompositionReview

	docsuffix string

	factreview *dt.FactCheckingReview

	findingslist *immutable.List[dt.InvestigatorFindings]

	gapanalysisreview *dt.GapAnalysisReview

	hastechleadfinalreview bool

	initialpromptcontext string

	investigationplanqualityreview *dt.InvestigationPlanQualityReview

	investigationreport *dt.InvestigationReport

	investigatorfindings *dt.InvestigatorFindings

	itercount int

	planreview *dt.PlanReview

	revisioninvprefix string

	revisionprompt string

	techleadfinalreview *dt.TechLeadFinal

	tliter int

	workstreamelem *dt.InvestigatorPlanworkstreamsElem
}

func (b *PayloadDataBuilder) Build() *PayloadData {
	return &PayloadData{
		allchanges:                     b.allchanges,
		archfinal:                      b.archfinal,
		archreview:                     b.archreview,
		codereview:                     b.codereview,
		coderoutputs:                   b.coderoutputs,
		consistencyreview:              b.consistencyreview,
		decompositionreview:            b.decompositionreview,
		docsuffix:                      b.docsuffix,
		factreview:                     b.factreview,
		findingslist:                   b.findingslist,
		gapanalysisreview:              b.gapanalysisreview,
		hastechleadfinalreview:         b.hastechleadfinalreview,
		initialpromptcontext:           b.initialpromptcontext,
		investigationplanqualityreview: b.investigationplanqualityreview,
		investigationreport:            b.investigationreport,
		investigatorfindings:           b.investigatorfindings,
		itercount:                      b.itercount,
		planreview:                     b.planreview,
		revisioninvprefix:              b.revisioninvprefix,
		revisionprompt:                 b.revisionprompt,
		techleadfinalreview:            b.techleadfinalreview,
		tliter:                         b.tliter,
		workstreamelem:                 b.workstreamelem,
	}
}

func (b *PayloadDataBuilder) WithAllChanges(v PayloadDataallchanges) *PayloadDataBuilder {
	b.allchanges = v
	return b
}

func (b *PayloadDataBuilder) WithArchFinal(v *dt.ArchFinal) *PayloadDataBuilder {
	b.archfinal = v
	return b
}

func (b *PayloadDataBuilder) WithArchReview(v *dt.ArchReview) *PayloadDataBuilder {
	b.archreview = v
	return b
}

func (b *PayloadDataBuilder) WithCodeReview(v *dt.CodeReview) *PayloadDataBuilder {
	b.codereview = v
	return b
}

func (b *PayloadDataBuilder) WithCoderOutputs(v *immutable.List[dt.Coder]) *PayloadDataBuilder {
	b.coderoutputs = v
	return b
}

func (b *PayloadDataBuilder) WithConsistencyReview(v *dt.SynthesisConsistencyReview) *PayloadDataBuilder {
	b.consistencyreview = v
	return b
}

func (b *PayloadDataBuilder) WithDecompositionReview(v *dt.SystemDecompositionReview) *PayloadDataBuilder {
	b.decompositionreview = v
	return b
}

func (b *PayloadDataBuilder) WithDocSuffix(v string) *PayloadDataBuilder {
	b.docsuffix = v
	return b
}

func (b *PayloadDataBuilder) WithFactReview(v *dt.FactCheckingReview) *PayloadDataBuilder {
	b.factreview = v
	return b
}

func (b *PayloadDataBuilder) WithFindingsList(v *immutable.List[dt.InvestigatorFindings]) *PayloadDataBuilder {
	b.findingslist = v
	return b
}

func (b *PayloadDataBuilder) WithGapAnalysisReview(v *dt.GapAnalysisReview) *PayloadDataBuilder {
	b.gapanalysisreview = v
	return b
}

func (b *PayloadDataBuilder) WithHasTechLeadFinalReview(v bool) *PayloadDataBuilder {
	b.hastechleadfinalreview = v
	return b
}

func (b *PayloadDataBuilder) WithInitialPromptContext(v string) *PayloadDataBuilder {
	b.initialpromptcontext = v
	return b
}

func (b *PayloadDataBuilder) WithInvestigationPlanQualityReview(v *dt.InvestigationPlanQualityReview) *PayloadDataBuilder {
	b.investigationplanqualityreview = v
	return b
}

func (b *PayloadDataBuilder) WithInvestigationReport(v *dt.InvestigationReport) *PayloadDataBuilder {
	b.investigationreport = v
	return b
}

func (b *PayloadDataBuilder) WithInvestigatorFindings(v *dt.InvestigatorFindings) *PayloadDataBuilder {
	b.investigatorfindings = v
	return b
}

func (b *PayloadDataBuilder) WithIterCount(v int) *PayloadDataBuilder {
	b.itercount = v
	return b
}

func (b *PayloadDataBuilder) WithPlanReview(v *dt.PlanReview) *PayloadDataBuilder {
	b.planreview = v
	return b
}

func (b *PayloadDataBuilder) WithRevisionInvPrefix(v string) *PayloadDataBuilder {
	b.revisioninvprefix = v
	return b
}

func (b *PayloadDataBuilder) WithRevisionPrompt(v string) *PayloadDataBuilder {
	b.revisionprompt = v
	return b
}

func (b *PayloadDataBuilder) WithTechLeadFinalReview(v *dt.TechLeadFinal) *PayloadDataBuilder {
	b.techleadfinalreview = v
	return b
}

func (b *PayloadDataBuilder) WithTlIter(v int) *PayloadDataBuilder {
	b.tliter = v
	return b
}

func (b *PayloadDataBuilder) WithWorkstreamElem(v *dt.InvestigatorPlanworkstreamsElem) *PayloadDataBuilder {
	b.workstreamelem = v
	return b
}

func (o *PayloadData) AllChanges() PayloadDataallchanges {
	return o.allchanges
}

func (o *PayloadData) ArchFinal() *dt.ArchFinal {
	return o.archfinal
}

func (o *PayloadData) ArchReview() *dt.ArchReview {
	return o.archreview
}

func (o *PayloadData) Clone() *PayloadDataBuilder {
	return NewPayloadDataBuilder(o)
}

func (o *PayloadData) CodeReview() *dt.CodeReview {
	return o.codereview
}

func (o *PayloadData) CoderOutputs() *immutable.List[dt.Coder] {
	return o.coderoutputs
}

func (o *PayloadData) ConsistencyReview() *dt.SynthesisConsistencyReview {
	return o.consistencyreview
}

func (o *PayloadData) DecompositionReview() *dt.SystemDecompositionReview {
	return o.decompositionreview
}

func (o *PayloadData) DocSuffix() string {
	return o.docsuffix
}

func (o *PayloadData) FactReview() *dt.FactCheckingReview {
	return o.factreview
}

func (o *PayloadData) FindingsList() *immutable.List[dt.InvestigatorFindings] {
	return o.findingslist
}

func (o *PayloadData) GapAnalysisReview() *dt.GapAnalysisReview {
	return o.gapanalysisreview
}

func (o *PayloadData) HasTechLeadFinalReview() bool {
	return o.hastechleadfinalreview
}

func (o *PayloadData) InitialPromptContext() string {
	return o.initialpromptcontext
}

func (o *PayloadData) InvestigationPlanQualityReview() *dt.InvestigationPlanQualityReview {
	return o.investigationplanqualityreview
}

func (o *PayloadData) InvestigationReport() *dt.InvestigationReport {
	return o.investigationreport
}

func (o *PayloadData) InvestigatorFindings() *dt.InvestigatorFindings {
	return o.investigatorfindings
}

func (o *PayloadData) IterCount() int {
	return o.itercount
}

func (o *PayloadData) PlanReview() *dt.PlanReview {
	return o.planreview
}

func (o *PayloadData) RevisionInvPrefix() string {
	return o.revisioninvprefix
}

func (o *PayloadData) RevisionPrompt() string {
	return o.revisionprompt
}

func (o *PayloadData) TechLeadFinalReview() *dt.TechLeadFinal {
	return o.techleadfinalreview
}

func (o *PayloadData) TlIter() int {
	return o.tliter
}

func (o *PayloadData) WorkstreamElem() *dt.InvestigatorPlanworkstreamsElem {
	return o.workstreamelem
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PayloadData) UnmarshalJSON(value []byte) error {
	type PayloadDataHelper struct {
		Allchanges                     map[string]string                   `json:"allChanges,omitempty,omitzero"`
		Archfinal                      *dt.ArchFinal                       `json:"archFinal,omitempty,omitzero"`
		Archreview                     *dt.ArchReview                      `json:"archReview,omitempty,omitzero"`
		Codereview                     *dt.CodeReview                      `json:"codeReview,omitempty,omitzero"`
		Coderoutputs                   []dt.Coder                          `json:"coderOutputs,omitempty,omitzero"`
		Consistencyreview              *dt.SynthesisConsistencyReview      `json:"consistencyReview,omitempty,omitzero"`
		Decompositionreview            *dt.SystemDecompositionReview       `json:"decompositionReview,omitempty,omitzero"`
		Docsuffix                      string                              `json:"docSuffix,omitempty,omitzero"`
		Factreview                     *dt.FactCheckingReview              `json:"factReview,omitempty,omitzero"`
		Findingslist                   []dt.InvestigatorFindings           `json:"findingsList,omitempty,omitzero"`
		Gapanalysisreview              *dt.GapAnalysisReview               `json:"gapAnalysisReview,omitempty,omitzero"`
		Hastechleadfinalreview         bool                                `json:"hasTechLeadFinalReview,omitempty,omitzero"`
		Initialpromptcontext           string                              `json:"initialPromptContext,omitempty,omitzero"`
		Investigationplanqualityreview *dt.InvestigationPlanQualityReview  `json:"investigationPlanQualityReview,omitempty,omitzero"`
		Investigationreport            *dt.InvestigationReport             `json:"investigationReport,omitempty,omitzero"`
		Investigatorfindings           *dt.InvestigatorFindings            `json:"investigatorFindings,omitempty,omitzero"`
		Itercount                      int                                 `json:"iterCount,omitempty,omitzero"`
		Planreview                     *dt.PlanReview                      `json:"planReview,omitempty,omitzero"`
		Revisioninvprefix              string                              `json:"revisionInvPrefix,omitempty,omitzero"`
		Revisionprompt                 string                              `json:"revisionPrompt,omitempty,omitzero"`
		Techleadfinalreview            *dt.TechLeadFinal                   `json:"techLeadFinalReview,omitempty,omitzero"`
		Tliter                         int                                 `json:"tlIter,omitempty,omitzero"`
		Workstreamelem                 *dt.InvestigatorPlanworkstreamsElem `json:"workstreamElem,omitempty,omitzero"`
	}
	type Plain PayloadData
	var helper PayloadDataHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.allchanges = (PayloadDataallchanges)(*immutable.NewMapOf[string](nil, helper.Allchanges))
	plain.archfinal = helper.Archfinal
	plain.archreview = helper.Archreview
	plain.codereview = helper.Codereview
	plain.coderoutputs = func() *immutable.List[dt.Coder] {
		if helper.Coderoutputs == nil {
			return nil
		}
		l := make([]dt.Coder, 0, len(helper.Coderoutputs))
		for _, v := range helper.Coderoutputs {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.consistencyreview = helper.Consistencyreview
	plain.decompositionreview = helper.Decompositionreview
	plain.docsuffix = helper.Docsuffix
	plain.factreview = helper.Factreview
	plain.findingslist = func() *immutable.List[dt.InvestigatorFindings] {
		if helper.Findingslist == nil {
			return nil
		}
		l := make([]dt.InvestigatorFindings, 0, len(helper.Findingslist))
		for _, v := range helper.Findingslist {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.gapanalysisreview = helper.Gapanalysisreview
	plain.hastechleadfinalreview = helper.Hastechleadfinalreview
	plain.initialpromptcontext = helper.Initialpromptcontext
	plain.investigationplanqualityreview = helper.Investigationplanqualityreview
	plain.investigationreport = helper.Investigationreport
	plain.investigatorfindings = helper.Investigatorfindings
	plain.itercount = helper.Itercount
	plain.planreview = helper.Planreview
	plain.revisioninvprefix = helper.Revisioninvprefix
	plain.revisionprompt = helper.Revisionprompt
	plain.techleadfinalreview = helper.Techleadfinalreview
	plain.tliter = helper.Tliter
	plain.workstreamelem = helper.Workstreamelem
	*j = PayloadData(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *PayloadData) MarshalJSON() ([]byte, error) {
	type PayloadDataMarshalHelper struct {
		Allchanges                     map[string]string                   `json:"allChanges,omitempty,omitzero"`
		Archfinal                      *dt.ArchFinal                       `json:"archFinal,omitempty,omitzero"`
		Archreview                     *dt.ArchReview                      `json:"archReview,omitempty,omitzero"`
		Codereview                     *dt.CodeReview                      `json:"codeReview,omitempty,omitzero"`
		Coderoutputs                   []dt.Coder                          `json:"coderOutputs,omitempty,omitzero"`
		Consistencyreview              *dt.SynthesisConsistencyReview      `json:"consistencyReview,omitempty,omitzero"`
		Decompositionreview            *dt.SystemDecompositionReview       `json:"decompositionReview,omitempty,omitzero"`
		Docsuffix                      string                              `json:"docSuffix,omitempty,omitzero"`
		Factreview                     *dt.FactCheckingReview              `json:"factReview,omitempty,omitzero"`
		Findingslist                   []dt.InvestigatorFindings           `json:"findingsList,omitempty,omitzero"`
		Gapanalysisreview              *dt.GapAnalysisReview               `json:"gapAnalysisReview,omitempty,omitzero"`
		Hastechleadfinalreview         bool                                `json:"hasTechLeadFinalReview,omitempty,omitzero"`
		Initialpromptcontext           string                              `json:"initialPromptContext,omitempty,omitzero"`
		Investigationplanqualityreview *dt.InvestigationPlanQualityReview  `json:"investigationPlanQualityReview,omitempty,omitzero"`
		Investigationreport            *dt.InvestigationReport             `json:"investigationReport,omitempty,omitzero"`
		Investigatorfindings           *dt.InvestigatorFindings            `json:"investigatorFindings,omitempty,omitzero"`
		Itercount                      int                                 `json:"iterCount,omitempty,omitzero"`
		Planreview                     *dt.PlanReview                      `json:"planReview,omitempty,omitzero"`
		Revisioninvprefix              string                              `json:"revisionInvPrefix,omitempty,omitzero"`
		Revisionprompt                 string                              `json:"revisionPrompt,omitempty,omitzero"`
		Techleadfinalreview            *dt.TechLeadFinal                   `json:"techLeadFinalReview,omitempty,omitzero"`
		Tliter                         int                                 `json:"tlIter,omitempty,omitzero"`
		Workstreamelem                 *dt.InvestigatorPlanworkstreamsElem `json:"workstreamElem,omitempty,omitzero"`
	}
	helper := PayloadDataMarshalHelper{
		Allchanges: func() map[string]string {
			m := make(map[string]string)
			iter := (*immutable.Map[string, string])(&j.allchanges).Iterator()
			for iter.First(); !iter.Done(); {
				k, v, ok := iter.Next()
				if !ok {
					break
				}
				m[k] = v
			}
			return m
		}(),
		Archfinal:  j.archfinal,
		Archreview: j.archreview,
		Codereview: j.codereview,
		Coderoutputs: func() []dt.Coder {
			if j.coderoutputs == nil {
				return nil
			}
			lst := (*immutable.List[dt.Coder])(j.coderoutputs)
			l := make([]dt.Coder, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
		Consistencyreview:   j.consistencyreview,
		Decompositionreview: j.decompositionreview,
		Docsuffix:           j.docsuffix,
		Factreview:          j.factreview,
		Findingslist: func() []dt.InvestigatorFindings {
			if j.findingslist == nil {
				return nil
			}
			lst := (*immutable.List[dt.InvestigatorFindings])(j.findingslist)
			l := make([]dt.InvestigatorFindings, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
		Gapanalysisreview:              j.gapanalysisreview,
		Hastechleadfinalreview:         j.hastechleadfinalreview,
		Initialpromptcontext:           j.initialpromptcontext,
		Investigationplanqualityreview: j.investigationplanqualityreview,
		Investigationreport:            j.investigationreport,
		Investigatorfindings:           j.investigatorfindings,
		Itercount:                      j.itercount,
		Planreview:                     j.planreview,
		Revisioninvprefix:              j.revisioninvprefix,
		Revisionprompt:                 j.revisionprompt,
		Techleadfinalreview:            j.techleadfinalreview,
		Tliter:                         j.tliter,
		Workstreamelem:                 j.workstreamelem,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *PayloadData) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Allchanges                     map[string]string
		Archfinal                      *dt.ArchFinal
		Archreview                     *dt.ArchReview
		Codereview                     *dt.CodeReview
		Coderoutputs                   []dt.Coder
		Consistencyreview              *dt.SynthesisConsistencyReview
		Decompositionreview            *dt.SystemDecompositionReview
		Docsuffix                      string
		Factreview                     *dt.FactCheckingReview
		Findingslist                   []dt.InvestigatorFindings
		Gapanalysisreview              *dt.GapAnalysisReview
		Hastechleadfinalreview         bool
		Initialpromptcontext           string
		Investigationplanqualityreview *dt.InvestigationPlanQualityReview
		Investigationreport            *dt.InvestigationReport
		Investigatorfindings           *dt.InvestigatorFindings
		Itercount                      int
		Planreview                     *dt.PlanReview
		Revisioninvprefix              string
		Revisionprompt                 string
		Techleadfinalreview            *dt.TechLeadFinal
		Tliter                         int
		Workstreamelem                 *dt.InvestigatorPlanworkstreamsElem
	}
	type Plain PayloadData
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.allchanges = (PayloadDataallchanges)(*immutable.NewMapOf[string](nil, rawStruct.Allchanges))
	plain.archfinal = rawStruct.Archfinal
	plain.archreview = rawStruct.Archreview
	plain.codereview = rawStruct.Codereview
	plain.coderoutputs = func() *immutable.List[dt.Coder] {
		if rawStruct.Coderoutputs == nil {
			return nil
		}
		l := make([]dt.Coder, 0, len(rawStruct.Coderoutputs))
		for _, v := range rawStruct.Coderoutputs {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.consistencyreview = rawStruct.Consistencyreview
	plain.decompositionreview = rawStruct.Decompositionreview
	plain.docsuffix = rawStruct.Docsuffix
	plain.factreview = rawStruct.Factreview
	plain.findingslist = func() *immutable.List[dt.InvestigatorFindings] {
		if rawStruct.Findingslist == nil {
			return nil
		}
		l := make([]dt.InvestigatorFindings, 0, len(rawStruct.Findingslist))
		for _, v := range rawStruct.Findingslist {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.gapanalysisreview = rawStruct.Gapanalysisreview
	plain.hastechleadfinalreview = rawStruct.Hastechleadfinalreview
	plain.initialpromptcontext = rawStruct.Initialpromptcontext
	plain.investigationplanqualityreview = rawStruct.Investigationplanqualityreview
	plain.investigationreport = rawStruct.Investigationreport
	plain.investigatorfindings = rawStruct.Investigatorfindings
	plain.itercount = rawStruct.Itercount
	plain.planreview = rawStruct.Planreview
	plain.revisioninvprefix = rawStruct.Revisioninvprefix
	plain.revisionprompt = rawStruct.Revisionprompt
	plain.techleadfinalreview = rawStruct.Techleadfinalreview
	plain.tliter = rawStruct.Tliter
	plain.workstreamelem = rawStruct.Workstreamelem
	plain = plain
	*j = PayloadData(plain)
	return nil
}

type PayloadDataallchanges immutable.Map[string, string]

func (m PayloadDataallchanges) Items() []struct {
	Key   string
	Value string
} {
	var items []struct {
		Key   string
		Value string
	}
	iter := (&m).Iterator()
	for iter.First(); !iter.Done(); {
		k, v, ok := iter.Next()
		if !ok {
			break
		}
		items = append(items, struct {
			Key   string
			Value string
		}{k, v})
	}
	return items
}

func (m PayloadDataallchanges) Iterator() *immutable.MapIterator[string, string] {
	return (*immutable.Map[string, string])(&m).Iterator()
}

type TestSchema struct {
	// codereviewiteration corresponds to the JSON schema field "codeReviewIteration".
	codereviewiteration int `json:"codeReviewIteration,omitempty,omitzero" yaml:"codeReviewIteration,omitempty" mapstructure:"codeReviewIteration,omitempty"`

	// domainid corresponds to the JSON schema field "domainID".
	domainid string `json:"domainID,omitempty,omitzero" yaml:"domainID,omitempty" mapstructure:"domainID,omitempty"`

	// domainindex corresponds to the JSON schema field "domainIndex".
	domainindex int `json:"domainIndex,omitempty,omitzero" yaml:"domainIndex,omitempty" mapstructure:"domainIndex,omitempty"`

	// iteration corresponds to the JSON schema field "iteration".
	iteration int `json:"iteration,omitempty,omitzero" yaml:"iteration,omitempty" mapstructure:"iteration,omitempty"`

	// payload corresponds to the JSON schema field "payload".
	payload *PayloadData `json:"payload,omitempty,omitzero" yaml:"payload,omitempty" mapstructure:"payload,omitempty"`

	// reviewiteration corresponds to the JSON schema field "reviewIteration".
	reviewiteration int `json:"reviewIteration,omitempty,omitzero" yaml:"reviewIteration,omitempty" mapstructure:"reviewIteration,omitempty"`

	// state corresponds to the JSON schema field "state".
	state *WorkflowState `json:"state,omitempty,omitzero" yaml:"state,omitempty" mapstructure:"state,omitempty"`

	// steptype corresponds to the JSON schema field "stepType".
	steptype TestSchemasteptype `json:"stepType,omitempty,omitzero" yaml:"stepType,omitempty" mapstructure:"stepType,omitempty"`

	// workstreamid corresponds to the JSON schema field "workstreamID".
	workstreamid string `json:"workstreamID,omitempty,omitzero" yaml:"workstreamID,omitempty" mapstructure:"workstreamID,omitempty"`

	// workstreamindex corresponds to the JSON schema field "workstreamIndex".
	workstreamindex int `json:"workstreamIndex,omitempty,omitzero" yaml:"workstreamIndex,omitempty" mapstructure:"workstreamIndex,omitempty"`
}

type TestSchemaBuilder struct {
	codereviewiteration int

	domainid string

	domainindex int

	iteration int

	payload *PayloadData

	reviewiteration int

	state *WorkflowState

	steptype TestSchemasteptype

	workstreamid string

	workstreamindex int
}

func (b *TestSchemaBuilder) Build() *TestSchema {
	return &TestSchema{
		codereviewiteration: b.codereviewiteration,
		domainid:            b.domainid,
		domainindex:         b.domainindex,
		iteration:           b.iteration,
		payload:             b.payload,
		reviewiteration:     b.reviewiteration,
		state:               b.state,
		steptype:            b.steptype,
		workstreamid:        b.workstreamid,
		workstreamindex:     b.workstreamindex,
	}
}

func (b *TestSchemaBuilder) WithCodeReviewIteration(v int) *TestSchemaBuilder {
	b.codereviewiteration = v
	return b
}

func (b *TestSchemaBuilder) WithDomainID(v string) *TestSchemaBuilder {
	b.domainid = v
	return b
}

func (b *TestSchemaBuilder) WithDomainIndex(v int) *TestSchemaBuilder {
	b.domainindex = v
	return b
}

func (b *TestSchemaBuilder) WithIteration(v int) *TestSchemaBuilder {
	b.iteration = v
	return b
}

func (b *TestSchemaBuilder) WithPayload(v *PayloadData) *TestSchemaBuilder {
	b.payload = v
	return b
}

func (b *TestSchemaBuilder) WithReviewIteration(v int) *TestSchemaBuilder {
	b.reviewiteration = v
	return b
}

func (b *TestSchemaBuilder) WithState(v *WorkflowState) *TestSchemaBuilder {
	b.state = v
	return b
}

func (b *TestSchemaBuilder) WithStepType(v TestSchemasteptype) *TestSchemaBuilder {
	b.steptype = v
	return b
}

func (b *TestSchemaBuilder) WithWorkstreamID(v string) *TestSchemaBuilder {
	b.workstreamid = v
	return b
}

func (b *TestSchemaBuilder) WithWorkstreamIndex(v int) *TestSchemaBuilder {
	b.workstreamindex = v
	return b
}

func (o *TestSchema) Clone() *TestSchemaBuilder {
	return NewTestSchemaBuilder(o)
}

func (o *TestSchema) CodeReviewIteration() int {
	return o.codereviewiteration
}

func (o *TestSchema) DomainID() string {
	return o.domainid
}

func (o *TestSchema) DomainIndex() int {
	return o.domainindex
}

func (o *TestSchema) Iteration() int {
	return o.iteration
}

func (o *TestSchema) Payload() *PayloadData {
	return o.payload
}

func (o *TestSchema) ReviewIteration() int {
	return o.reviewiteration
}

func (o *TestSchema) State() *WorkflowState {
	return o.state
}

func (o *TestSchema) StepType() TestSchemasteptype {
	return o.steptype
}

func (o *TestSchema) WorkstreamID() string {
	return o.workstreamid
}

func (o *TestSchema) WorkstreamIndex() int {
	return o.workstreamindex
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TestSchema) UnmarshalJSON(value []byte) error {
	type TestSchemaHelper struct {
		Codereviewiteration int                `json:"codeReviewIteration,omitempty,omitzero"`
		Domainid            string             `json:"domainID,omitempty,omitzero"`
		Domainindex         int                `json:"domainIndex,omitempty,omitzero"`
		Iteration           int                `json:"iteration,omitempty,omitzero"`
		Payload             *PayloadData       `json:"payload,omitempty,omitzero"`
		Reviewiteration     int                `json:"reviewIteration,omitempty,omitzero"`
		State               *WorkflowState     `json:"state,omitempty,omitzero"`
		Steptype            TestSchemasteptype `json:"stepType,omitempty,omitzero"`
		Workstreamid        string             `json:"workstreamID,omitempty,omitzero"`
		Workstreamindex     int                `json:"workstreamIndex,omitempty,omitzero"`
	}
	type Plain TestSchema
	var helper TestSchemaHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.codereviewiteration = helper.Codereviewiteration
	plain.domainid = helper.Domainid
	plain.domainindex = helper.Domainindex
	plain.iteration = helper.Iteration
	plain.payload = helper.Payload
	plain.reviewiteration = helper.Reviewiteration
	plain.state = helper.State
	plain.steptype = helper.Steptype
	plain.workstreamid = helper.Workstreamid
	plain.workstreamindex = helper.Workstreamindex
	*j = TestSchema(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *TestSchema) MarshalJSON() ([]byte, error) {
	type TestSchemaMarshalHelper struct {
		Codereviewiteration int                `json:"codeReviewIteration,omitempty,omitzero"`
		Domainid            string             `json:"domainID,omitempty,omitzero"`
		Domainindex         int                `json:"domainIndex,omitempty,omitzero"`
		Iteration           int                `json:"iteration,omitempty,omitzero"`
		Payload             *PayloadData       `json:"payload,omitempty,omitzero"`
		Reviewiteration     int                `json:"reviewIteration,omitempty,omitzero"`
		State               *WorkflowState     `json:"state,omitempty,omitzero"`
		Steptype            TestSchemasteptype `json:"stepType,omitempty,omitzero"`
		Workstreamid        string             `json:"workstreamID,omitempty,omitzero"`
		Workstreamindex     int                `json:"workstreamIndex,omitempty,omitzero"`
	}
	helper := TestSchemaMarshalHelper{
		Codereviewiteration: j.codereviewiteration,
		Domainid:            j.domainid,
		Domainindex:         j.domainindex,
		Iteration:           j.iteration,
		Payload:             j.payload,
		Reviewiteration:     j.reviewiteration,
		State:               j.state,
		Steptype:            j.steptype,
		Workstreamid:        j.workstreamid,
		Workstreamindex:     j.workstreamindex,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *TestSchema) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Codereviewiteration int
		Domainid            string
		Domainindex         int
		Iteration           int
		Payload             *PayloadData
		Reviewiteration     int
		State               *WorkflowState
		Steptype            TestSchemasteptype
		Workstreamid        string
		Workstreamindex     int
	}
	type Plain TestSchema
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.codereviewiteration = rawStruct.Codereviewiteration
	plain.domainid = rawStruct.Domainid
	plain.domainindex = rawStruct.Domainindex
	plain.iteration = rawStruct.Iteration
	plain.payload = rawStruct.Payload
	plain.reviewiteration = rawStruct.Reviewiteration
	plain.state = rawStruct.State
	plain.steptype = rawStruct.Steptype
	plain.workstreamid = rawStruct.Workstreamid
	plain.workstreamindex = rawStruct.Workstreamindex
	plain = plain
	*j = TestSchema(plain)
	return nil
}

type TestSchemasteptype string

const TestSchemasteptypeArchitecture TestSchemasteptype = "Architecture"
const TestSchemasteptypeArchitectureFinalReview TestSchemasteptype = "ArchitectureFinalReview"
const TestSchemasteptypeArchitectureFinalReviewOrchestrator TestSchemasteptype = "ArchitectureFinalReviewOrchestrator"
const TestSchemasteptypeArchitectureOrchestrator TestSchemasteptype = "ArchitectureOrchestrator"
const TestSchemasteptypeArchitectureReview TestSchemasteptype = "ArchitectureReview"
const TestSchemasteptypeBoundary TestSchemasteptype = "Boundary"
const TestSchemasteptypeClassification TestSchemasteptype = "Classification"
const TestSchemasteptypeCodeImplementation TestSchemasteptype = "CodeImplementation"
const TestSchemasteptypeCodeReview TestSchemasteptype = "CodeReview"
const TestSchemasteptypeCodeReviewOrchestrator TestSchemasteptype = "CodeReviewOrchestrator"
const TestSchemasteptypeDecomposition TestSchemasteptype = "Decomposition"
const TestSchemasteptypeDecompositionOrchestrator TestSchemasteptype = "DecompositionOrchestrator"
const TestSchemasteptypeDecompositionReview TestSchemasteptype = "DecompositionReview"
const TestSchemasteptypeDomainStart TestSchemasteptype = "DomainStart"
const TestSchemasteptypeFinalInvestigation TestSchemasteptype = "FinalInvestigation"
const TestSchemasteptypeInvestigationConsistencyReview TestSchemasteptype = "InvestigationConsistencyReview"
const TestSchemasteptypeInvestigationConsistencyReviewOrchestrator TestSchemasteptype = "InvestigationConsistencyReviewOrchestrator"
const TestSchemasteptypeInvestigationFactReview TestSchemasteptype = "InvestigationFactReview"
const TestSchemasteptypeInvestigationFactReviewOrchestrator TestSchemasteptype = "InvestigationFactReviewOrchestrator"
const TestSchemasteptypeInvestigationPlanGenerate TestSchemasteptype = "InvestigationPlanGenerate"
const TestSchemasteptypeInvestigationPlanReview TestSchemasteptype = "InvestigationPlanReview"
const TestSchemasteptypeInvestigationPlanStructuralReview TestSchemasteptype = "InvestigationPlanStructuralReview"
const TestSchemasteptypeInvestigationSynthesis TestSchemasteptype = "InvestigationSynthesis"
const TestSchemasteptypeInvestigationWorkstream TestSchemasteptype = "InvestigationWorkstream"
const TestSchemasteptypeInvestigationWorkstreamReview TestSchemasteptype = "InvestigationWorkstreamReview"
const TestSchemasteptypePMCandidateGenerate TestSchemasteptype = "PMCandidateGenerate"
const TestSchemasteptypePMExpansionCleanup TestSchemasteptype = "PMExpansionCleanup"
const TestSchemasteptypePMReview TestSchemasteptype = "PMReview"
const TestSchemasteptypePMSynthesize TestSchemasteptype = "PMSynthesize"
const TestSchemasteptypePlan TestSchemasteptype = "Plan"
const TestSchemasteptypePlanOrchestrator TestSchemasteptype = "PlanOrchestrator"
const TestSchemasteptypePlanReview TestSchemasteptype = "PlanReview"
const TestSchemasteptypeTechLeadEnd TestSchemasteptype = "TechLeadEnd"
const TestSchemasteptypeTechLeadReview TestSchemasteptype = "TechLeadReview"
const TestSchemasteptypeTechLeadReviewOrchestrator TestSchemasteptype = "TechLeadReviewOrchestrator"

var enumValues_TestSchemasteptype = []interface{}{
	"PMCandidateGenerate",
	"PMSynthesize",
	"PMReview",
	"Classification",
	"Decomposition",
	"DecompositionReview",
	"DomainStart",
	"InvestigationPlanGenerate",
	"InvestigationPlanReview",
	"InvestigationWorkstream",
	"InvestigationWorkstreamReview",
	"InvestigationSynthesis",
	"InvestigationConsistencyReview",
	"Architecture",
	"ArchitectureReview",
	"Plan",
	"PlanReview",
	"CodeImplementation",
	"CodeReview",
	"TechLeadReview",
	"ArchitectureFinalReview",
	"FinalInvestigation",
	"PMExpansionCleanup",
	"InvestigationPlanStructuralReview",
	"InvestigationFactReview",
	"DecompositionOrchestrator",
	"ArchitectureOrchestrator",
	"PlanOrchestrator",
	"CodeReviewOrchestrator",
	"TechLeadReviewOrchestrator",
	"ArchitectureFinalReviewOrchestrator",
	"InvestigationFactReviewOrchestrator",
	"InvestigationConsistencyReviewOrchestrator",
	"TechLeadEnd",
	"Boundary",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TestSchemasteptype) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TestSchemasteptype {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TestSchemasteptype, v)
	}
	*j = TestSchemasteptype(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *TestSchemasteptype) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TestSchemasteptype {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TestSchemasteptype, v)
	}
	*j = TestSchemasteptype(v)
	return nil
}

type WorkflowState struct {
	// choices corresponds to the JSON schema field "choices".
	choices string `json:"choices,omitempty,omitzero" yaml:"choices,omitempty" mapstructure:"choices,omitempty"`

	// completedworkstreams corresponds to the JSON schema field
	// "completedWorkstreams".
	completedworkstreams WorkflowStatecompletedworkstreams `json:"completedWorkstreams,omitempty,omitzero" yaml:"completedWorkstreams,omitempty" mapstructure:"completedWorkstreams,omitempty"`

	// decompositionresult corresponds to the JSON schema field "decompositionResult".
	decompositionresult *dt.SystemDecomposition `json:"decompositionResult,omitempty,omitzero" yaml:"decompositionResult,omitempty" mapstructure:"decompositionResult,omitempty"`

	// domaincurrentstage corresponds to the JSON schema field "domainCurrentStage".
	domaincurrentstage string `json:"domainCurrentStage,omitempty,omitzero" yaml:"domainCurrentStage,omitempty" mapstructure:"domainCurrentStage,omitempty"`

	// domainiterationindex corresponds to the JSON schema field
	// "domainIterationIndex".
	domainiterationindex int `json:"domainIterationIndex,omitempty,omitzero" yaml:"domainIterationIndex,omitempty" mapstructure:"domainIterationIndex,omitempty"`

	// domainiterationtotal corresponds to the JSON schema field
	// "domainIterationTotal".
	domainiterationtotal int `json:"domainIterationTotal,omitempty,omitzero" yaml:"domainIterationTotal,omitempty" mapstructure:"domainIterationTotal,omitempty"`

	// domains corresponds to the JSON schema field "domains".
	domains WorkflowStatedomains `json:"domains,omitempty,omitzero" yaml:"domains,omitempty" mapstructure:"domains,omitempty"`

	// finalinvestigationtask corresponds to the JSON schema field
	// "finalInvestigationTask".
	finalinvestigationtask string `json:"finalInvestigationTask,omitempty,omitzero" yaml:"finalInvestigationTask,omitempty" mapstructure:"finalInvestigationTask,omitempty"`

	// investigationplan corresponds to the JSON schema field "investigationPlan".
	investigationplan *dt.InvestigatorPlan `json:"investigationPlan,omitempty,omitzero" yaml:"investigationPlan,omitempty" mapstructure:"investigationPlan,omitempty"`

	// investigationresults corresponds to the JSON schema field
	// "investigationResults".
	investigationresults *dt.InvestigationReport `json:"investigationResults,omitempty,omitzero" yaml:"investigationResults,omitempty" mapstructure:"investigationResults,omitempty"`

	// out corresponds to the JSON schema field "out".
	out string `json:"out,omitempty,omitzero" yaml:"out,omitempty" mapstructure:"out,omitempty"`

	// pmfilepath corresponds to the JSON schema field "pmFilepath".
	pmfilepath string `json:"pmFilepath,omitempty,omitzero" yaml:"pmFilepath,omitempty" mapstructure:"pmFilepath,omitempty"`

	// rephrasedtask corresponds to the JSON schema field "rephrasedTask".
	rephrasedtask *dt.PmSynthesizer `json:"rephrasedTask,omitempty,omitzero" yaml:"rephrasedTask,omitempty" mapstructure:"rephrasedTask,omitempty"`

	// speculativeexpansions corresponds to the JSON schema field
	// "speculativeExpansions".
	speculativeexpansions *immutable.List[string] `json:"speculativeExpansions,omitempty,omitzero" yaml:"speculativeExpansions,omitempty" mapstructure:"speculativeExpansions,omitempty"`

	// subdir corresponds to the JSON schema field "subdir".
	subdir string `json:"subdir,omitempty,omitzero" yaml:"subdir,omitempty" mapstructure:"subdir,omitempty"`

	// task corresponds to the JSON schema field "task".
	task string `json:"task,omitempty,omitzero" yaml:"task,omitempty" mapstructure:"task,omitempty"`

	// techleaddocsuffix corresponds to the JSON schema field "techLeadDocSuffix".
	techleaddocsuffix string `json:"techLeadDocSuffix,omitempty,omitzero" yaml:"techLeadDocSuffix,omitempty" mapstructure:"techLeadDocSuffix,omitempty"`

	// workstreams corresponds to the JSON schema field "workstreams".
	workstreams *immutable.List[dt.InvestigatorPlanworkstreamsElem] `json:"workstreams,omitempty,omitzero" yaml:"workstreams,omitempty" mapstructure:"workstreams,omitempty"`
}

type WorkflowStateBuilder struct {
	choices string

	completedworkstreams WorkflowStatecompletedworkstreams

	decompositionresult *dt.SystemDecomposition

	domaincurrentstage string

	domainiterationindex int

	domainiterationtotal int

	domains WorkflowStatedomains

	finalinvestigationtask string

	investigationplan *dt.InvestigatorPlan

	investigationresults *dt.InvestigationReport

	out string

	pmfilepath string

	rephrasedtask *dt.PmSynthesizer

	speculativeexpansions *immutable.List[string]

	subdir string

	task string

	techleaddocsuffix string

	workstreams *immutable.List[dt.InvestigatorPlanworkstreamsElem]
}

func (b *WorkflowStateBuilder) Build() *WorkflowState {
	return &WorkflowState{
		choices:                b.choices,
		completedworkstreams:   b.completedworkstreams,
		decompositionresult:    b.decompositionresult,
		domaincurrentstage:     b.domaincurrentstage,
		domainiterationindex:   b.domainiterationindex,
		domainiterationtotal:   b.domainiterationtotal,
		domains:                b.domains,
		finalinvestigationtask: b.finalinvestigationtask,
		investigationplan:      b.investigationplan,
		investigationresults:   b.investigationresults,
		out:                    b.out,
		pmfilepath:             b.pmfilepath,
		rephrasedtask:          b.rephrasedtask,
		speculativeexpansions:  b.speculativeexpansions,
		subdir:                 b.subdir,
		task:                   b.task,
		techleaddocsuffix:      b.techleaddocsuffix,
		workstreams:            b.workstreams,
	}
}

func (b *WorkflowStateBuilder) WithChoices(v string) *WorkflowStateBuilder {
	b.choices = v
	return b
}

func (b *WorkflowStateBuilder) WithCompletedWorkstreams(v WorkflowStatecompletedworkstreams) *WorkflowStateBuilder {
	b.completedworkstreams = v
	return b
}

func (b *WorkflowStateBuilder) WithDecompositionResult(v *dt.SystemDecomposition) *WorkflowStateBuilder {
	b.decompositionresult = v
	return b
}

func (b *WorkflowStateBuilder) WithDomainCurrentStage(v string) *WorkflowStateBuilder {
	b.domaincurrentstage = v
	return b
}

func (b *WorkflowStateBuilder) WithDomainIterationIndex(v int) *WorkflowStateBuilder {
	b.domainiterationindex = v
	return b
}

func (b *WorkflowStateBuilder) WithDomainIterationTotal(v int) *WorkflowStateBuilder {
	b.domainiterationtotal = v
	return b
}

func (b *WorkflowStateBuilder) WithDomains(v WorkflowStatedomains) *WorkflowStateBuilder {
	b.domains = v
	return b
}

func (b *WorkflowStateBuilder) WithFinalInvestigationTask(v string) *WorkflowStateBuilder {
	b.finalinvestigationtask = v
	return b
}

func (b *WorkflowStateBuilder) WithInvestigationPlan(v *dt.InvestigatorPlan) *WorkflowStateBuilder {
	b.investigationplan = v
	return b
}

func (b *WorkflowStateBuilder) WithInvestigationResults(v *dt.InvestigationReport) *WorkflowStateBuilder {
	b.investigationresults = v
	return b
}

func (b *WorkflowStateBuilder) WithOut(v string) *WorkflowStateBuilder {
	b.out = v
	return b
}

func (b *WorkflowStateBuilder) WithPmFilepath(v string) *WorkflowStateBuilder {
	b.pmfilepath = v
	return b
}

func (b *WorkflowStateBuilder) WithRephrasedTask(v *dt.PmSynthesizer) *WorkflowStateBuilder {
	b.rephrasedtask = v
	return b
}

func (b *WorkflowStateBuilder) WithSpeculativeExpansions(v *immutable.List[string]) *WorkflowStateBuilder {
	b.speculativeexpansions = v
	return b
}

func (b *WorkflowStateBuilder) WithSubdir(v string) *WorkflowStateBuilder {
	b.subdir = v
	return b
}

func (b *WorkflowStateBuilder) WithTask(v string) *WorkflowStateBuilder {
	b.task = v
	return b
}

func (b *WorkflowStateBuilder) WithTechLeadDocSuffix(v string) *WorkflowStateBuilder {
	b.techleaddocsuffix = v
	return b
}

func (b *WorkflowStateBuilder) WithWorkstreams(v *immutable.List[dt.InvestigatorPlanworkstreamsElem]) *WorkflowStateBuilder {
	b.workstreams = v
	return b
}

func (o *WorkflowState) Choices() string {
	return o.choices
}

func (o *WorkflowState) Clone() *WorkflowStateBuilder {
	return NewWorkflowStateBuilder(o)
}

func (o *WorkflowState) CompletedWorkstreams() WorkflowStatecompletedworkstreams {
	return o.completedworkstreams
}

func (o *WorkflowState) DecompositionResult() *dt.SystemDecomposition {
	return o.decompositionresult
}

func (o *WorkflowState) DomainCurrentStage() string {
	return o.domaincurrentstage
}

func (o *WorkflowState) DomainIterationIndex() int {
	return o.domainiterationindex
}

func (o *WorkflowState) DomainIterationTotal() int {
	return o.domainiterationtotal
}

func (o *WorkflowState) Domains() WorkflowStatedomains {
	return o.domains
}

func (o *WorkflowState) FinalInvestigationTask() string {
	return o.finalinvestigationtask
}

func (o *WorkflowState) InvestigationPlan() *dt.InvestigatorPlan {
	return o.investigationplan
}

func (o *WorkflowState) InvestigationResults() *dt.InvestigationReport {
	return o.investigationresults
}

func (o *WorkflowState) Out() string {
	return o.out
}

func (o *WorkflowState) PmFilepath() string {
	return o.pmfilepath
}

func (o *WorkflowState) RephrasedTask() *dt.PmSynthesizer {
	return o.rephrasedtask
}

func (o *WorkflowState) SpeculativeExpansions() *immutable.List[string] {
	return o.speculativeexpansions
}

func (o *WorkflowState) Subdir() string {
	return o.subdir
}

func (o *WorkflowState) Task() string {
	return o.task
}

func (o *WorkflowState) TechLeadDocSuffix() string {
	return o.techleaddocsuffix
}

func (o *WorkflowState) Workstreams() *immutable.List[dt.InvestigatorPlanworkstreamsElem] {
	return o.workstreams
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *WorkflowState) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Choices                string
		Completedworkstreams   map[string]dt.InvestigatorFindings
		Decompositionresult    *dt.SystemDecomposition
		Domaincurrentstage     string
		Domainiterationindex   int
		Domainiterationtotal   int
		Domains                map[string]*DomainState
		Finalinvestigationtask string
		Investigationplan      *dt.InvestigatorPlan
		Investigationresults   *dt.InvestigationReport
		Out                    string
		Pmfilepath             string
		Rephrasedtask          *dt.PmSynthesizer
		Speculativeexpansions  []string
		Subdir                 string
		Task                   string
		Techleaddocsuffix      string
		Workstreams            []dt.InvestigatorPlanworkstreamsElem
	}
	type Plain WorkflowState
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.choices = rawStruct.Choices
	plain.completedworkstreams = (WorkflowStatecompletedworkstreams)(*immutable.NewMapOf[string](nil, rawStruct.Completedworkstreams))
	plain.decompositionresult = rawStruct.Decompositionresult
	plain.domaincurrentstage = rawStruct.Domaincurrentstage
	plain.domainiterationindex = rawStruct.Domainiterationindex
	plain.domainiterationtotal = rawStruct.Domainiterationtotal
	plain.domains = (WorkflowStatedomains)(*immutable.NewMapOf[string](nil, func() map[string]DomainState {
		m := make(map[string]DomainState)
		for k, v := range rawStruct.Domains {
			m[k] = *v
		}
		return m
	}()))
	plain.finalinvestigationtask = rawStruct.Finalinvestigationtask
	plain.investigationplan = rawStruct.Investigationplan
	plain.investigationresults = rawStruct.Investigationresults
	plain.out = rawStruct.Out
	plain.pmfilepath = rawStruct.Pmfilepath
	plain.rephrasedtask = rawStruct.Rephrasedtask
	plain.speculativeexpansions = func() *immutable.List[string] {
		if rawStruct.Speculativeexpansions == nil {
			return nil
		}
		l := make([]string, 0, len(rawStruct.Speculativeexpansions))
		for _, v := range rawStruct.Speculativeexpansions {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.subdir = rawStruct.Subdir
	plain.task = rawStruct.Task
	plain.techleaddocsuffix = rawStruct.Techleaddocsuffix
	plain.workstreams = func() *immutable.List[dt.InvestigatorPlanworkstreamsElem] {
		if rawStruct.Workstreams == nil {
			return nil
		}
		l := make([]dt.InvestigatorPlanworkstreamsElem, 0, len(rawStruct.Workstreams))
		for _, v := range rawStruct.Workstreams {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain = plain
	*j = WorkflowState(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkflowState) UnmarshalJSON(value []byte) error {
	type WorkflowStateHelper struct {
		Choices                string                               `json:"choices,omitempty,omitzero"`
		Completedworkstreams   map[string]dt.InvestigatorFindings   `json:"completedWorkstreams,omitempty,omitzero"`
		Decompositionresult    *dt.SystemDecomposition              `json:"decompositionResult,omitempty,omitzero"`
		Domaincurrentstage     string                               `json:"domainCurrentStage,omitempty,omitzero"`
		Domainiterationindex   int                                  `json:"domainIterationIndex,omitempty,omitzero"`
		Domainiterationtotal   int                                  `json:"domainIterationTotal,omitempty,omitzero"`
		Domains                map[string]*DomainState              `json:"domains,omitempty,omitzero"`
		Finalinvestigationtask string                               `json:"finalInvestigationTask,omitempty,omitzero"`
		Investigationplan      *dt.InvestigatorPlan                 `json:"investigationPlan,omitempty,omitzero"`
		Investigationresults   *dt.InvestigationReport              `json:"investigationResults,omitempty,omitzero"`
		Out                    string                               `json:"out,omitempty,omitzero"`
		Pmfilepath             string                               `json:"pmFilepath,omitempty,omitzero"`
		Rephrasedtask          *dt.PmSynthesizer                    `json:"rephrasedTask,omitempty,omitzero"`
		Speculativeexpansions  []string                             `json:"speculativeExpansions,omitempty,omitzero"`
		Subdir                 string                               `json:"subdir,omitempty,omitzero"`
		Task                   string                               `json:"task,omitempty,omitzero"`
		Techleaddocsuffix      string                               `json:"techLeadDocSuffix,omitempty,omitzero"`
		Workstreams            []dt.InvestigatorPlanworkstreamsElem `json:"workstreams,omitempty,omitzero"`
	}
	type Plain WorkflowState
	var helper WorkflowStateHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.choices = helper.Choices
	plain.completedworkstreams = (WorkflowStatecompletedworkstreams)(*immutable.NewMapOf[string](nil, helper.Completedworkstreams))
	plain.decompositionresult = helper.Decompositionresult
	plain.domaincurrentstage = helper.Domaincurrentstage
	plain.domainiterationindex = helper.Domainiterationindex
	plain.domainiterationtotal = helper.Domainiterationtotal
	plain.domains = (WorkflowStatedomains)(*immutable.NewMapOf[string](nil, func() map[string]DomainState {
		m := make(map[string]DomainState)
		for k, v := range helper.Domains {
			m[k] = *v
		}
		return m
	}()))
	plain.finalinvestigationtask = helper.Finalinvestigationtask
	plain.investigationplan = helper.Investigationplan
	plain.investigationresults = helper.Investigationresults
	plain.out = helper.Out
	plain.pmfilepath = helper.Pmfilepath
	plain.rephrasedtask = helper.Rephrasedtask
	plain.speculativeexpansions = func() *immutable.List[string] {
		if helper.Speculativeexpansions == nil {
			return nil
		}
		l := make([]string, 0, len(helper.Speculativeexpansions))
		for _, v := range helper.Speculativeexpansions {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	plain.subdir = helper.Subdir
	plain.task = helper.Task
	plain.techleaddocsuffix = helper.Techleaddocsuffix
	plain.workstreams = func() *immutable.List[dt.InvestigatorPlanworkstreamsElem] {
		if helper.Workstreams == nil {
			return nil
		}
		l := make([]dt.InvestigatorPlanworkstreamsElem, 0, len(helper.Workstreams))
		for _, v := range helper.Workstreams {
			l = append(l, v)
		}
		return immutable.NewList(l...)
	}()
	*j = WorkflowState(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *WorkflowState) MarshalJSON() ([]byte, error) {
	type WorkflowStateMarshalHelper struct {
		Choices                string                               `json:"choices,omitempty,omitzero"`
		Completedworkstreams   map[string]dt.InvestigatorFindings   `json:"completedWorkstreams,omitempty,omitzero"`
		Decompositionresult    *dt.SystemDecomposition              `json:"decompositionResult,omitempty,omitzero"`
		Domaincurrentstage     string                               `json:"domainCurrentStage,omitempty,omitzero"`
		Domainiterationindex   int                                  `json:"domainIterationIndex,omitempty,omitzero"`
		Domainiterationtotal   int                                  `json:"domainIterationTotal,omitempty,omitzero"`
		Domains                map[string]*DomainState              `json:"domains,omitempty,omitzero"`
		Finalinvestigationtask string                               `json:"finalInvestigationTask,omitempty,omitzero"`
		Investigationplan      *dt.InvestigatorPlan                 `json:"investigationPlan,omitempty,omitzero"`
		Investigationresults   *dt.InvestigationReport              `json:"investigationResults,omitempty,omitzero"`
		Out                    string                               `json:"out,omitempty,omitzero"`
		Pmfilepath             string                               `json:"pmFilepath,omitempty,omitzero"`
		Rephrasedtask          *dt.PmSynthesizer                    `json:"rephrasedTask,omitempty,omitzero"`
		Speculativeexpansions  []string                             `json:"speculativeExpansions,omitempty,omitzero"`
		Subdir                 string                               `json:"subdir,omitempty,omitzero"`
		Task                   string                               `json:"task,omitempty,omitzero"`
		Techleaddocsuffix      string                               `json:"techLeadDocSuffix,omitempty,omitzero"`
		Workstreams            []dt.InvestigatorPlanworkstreamsElem `json:"workstreams,omitempty,omitzero"`
	}
	helper := WorkflowStateMarshalHelper{
		Choices: j.choices,
		Completedworkstreams: func() map[string]dt.InvestigatorFindings {
			m := make(map[string]dt.InvestigatorFindings)
			iter := (*immutable.Map[string, dt.InvestigatorFindings])(&j.completedworkstreams).Iterator()
			for iter.First(); !iter.Done(); {
				k, v, ok := iter.Next()
				if !ok {
					break
				}
				m[k] = v
			}
			return m
		}(),
		Decompositionresult:  j.decompositionresult,
		Domaincurrentstage:   j.domaincurrentstage,
		Domainiterationindex: j.domainiterationindex,
		Domainiterationtotal: j.domainiterationtotal,
		Domains: func() map[string]*DomainState {
			m := make(map[string]*DomainState)
			iter := (*immutable.Map[string, DomainState])(&j.domains).Iterator()
			for iter.First(); !iter.Done(); {
				k, v, ok := iter.Next()
				if !ok {
					break
				}
				m[k] = &v
			}
			return m
		}(),
		Finalinvestigationtask: j.finalinvestigationtask,
		Investigationplan:      j.investigationplan,
		Investigationresults:   j.investigationresults,
		Out:                    j.out,
		Pmfilepath:             j.pmfilepath,
		Rephrasedtask:          j.rephrasedtask,
		Speculativeexpansions: func() []string {
			if j.speculativeexpansions == nil {
				return nil
			}
			lst := (*immutable.List[string])(j.speculativeexpansions)
			l := make([]string, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
		Subdir:            j.subdir,
		Task:              j.task,
		Techleaddocsuffix: j.techleaddocsuffix,
		Workstreams: func() []dt.InvestigatorPlanworkstreamsElem {
			if j.workstreams == nil {
				return nil
			}
			lst := (*immutable.List[dt.InvestigatorPlanworkstreamsElem])(j.workstreams)
			l := make([]dt.InvestigatorPlanworkstreamsElem, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
	}
	return json.Marshal(helper)
}

type WorkflowStatecompletedworkstreams immutable.Map[string, dt.InvestigatorFindings]

func (m WorkflowStatecompletedworkstreams) Items() []struct {
	Key   string
	Value dt.InvestigatorFindings
} {
	var items []struct {
		Key   string
		Value dt.InvestigatorFindings
	}
	iter := (&m).Iterator()
	for iter.First(); !iter.Done(); {
		k, v, ok := iter.Next()
		if !ok {
			break
		}
		items = append(items, struct {
			Key   string
			Value dt.InvestigatorFindings
		}{k, v})
	}
	return items
}

func (m WorkflowStatecompletedworkstreams) Iterator() *immutable.MapIterator[string, dt.InvestigatorFindings] {
	return (*immutable.Map[string, dt.InvestigatorFindings])(&m).Iterator()
}

type WorkflowStatedomains immutable.Map[string, DomainState]

func (m WorkflowStatedomains) Items() []struct {
	Key   string
	Value DomainState
} {
	var items []struct {
		Key   string
		Value DomainState
	}
	iter := (&m).Iterator()
	for iter.First(); !iter.Done(); {
		k, v, ok := iter.Next()
		if !ok {
			break
		}
		items = append(items, struct {
			Key   string
			Value DomainState
		}{k, v})
	}
	return items
}

func (m WorkflowStatedomains) Iterator() *immutable.MapIterator[string, DomainState] {
	return (*immutable.Map[string, DomainState])(&m).Iterator()
}
