// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

type Name string

func NewRefNestedBuilder(o *RefNested) *RefNestedBuilder {
	if o == nil {
		return &RefNestedBuilder{}
	}
	return &RefNestedBuilder{
		mything: o.mything,
	}
}

func NewThingBuilder(o *Thing) *ThingBuilder {
	if o == nil {
		return &ThingBuilder{}
	}
	return &ThingBuilder{
		name: o.name,
	}
}

type RefNested struct {
	// mything corresponds to the JSON schema field "myThing".
	mything *Thing `json:"myThing,omitempty,omitzero" yaml:"myThing,omitempty" mapstructure:"myThing,omitempty"`
}

type RefNestedBuilder struct {
	mything *Thing
}

func (b *RefNestedBuilder) Build() *RefNested {
	return &RefNested{
		mything: b.mything,
	}
}

func (b *RefNestedBuilder) WithMyThing(v *Thing) *RefNestedBuilder {
	b.mything = v
	return b
}

func (o *RefNested) MyThing() *Thing {
	return o.mything
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RefNested) UnmarshalYAML(value *yaml.Node) error {
	type Plain RefNested
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = RefNested(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RefNested) UnmarshalJSON(value []byte) error {
	type RefNestedHelper struct {
		Mything *Thing `json:"myThing",omitempty`
	}
	type Plain RefNested
	var helper RefNestedHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mything = helper.Mything
	*j = RefNested(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *RefNested) MarshalJSON() ([]byte, error) {
	type RefNestedMarshalHelper struct {
		Mything *Thing `json:"myThing",omitempty`
	}
	helper := RefNestedMarshalHelper{
		Mything: j.mything,
	}
	return json.Marshal(helper)
}

type Thing struct {
	// name corresponds to the JSON schema field "name".
	name *Name `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type ThingBuilder struct {
	name *Name
}

func (b *ThingBuilder) Build() *Thing {
	return &Thing{
		name: b.name,
	}
}

func (b *ThingBuilder) WithName(v *Name) *ThingBuilder {
	b.name = v
	return b
}

func (o *Thing) Name() *Name {
	return o.name
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Thing) UnmarshalYAML(value *yaml.Node) error {
	type Plain Thing
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Thing(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Thing) UnmarshalJSON(value []byte) error {
	type ThingHelper struct {
		Name *Name `json:"name",omitempty`
	}
	type Plain Thing
	var helper ThingHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = Thing(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Thing) MarshalJSON() ([]byte, error) {
	type ThingMarshalHelper struct {
		Name *Name `json:"name",omitempty`
	}
	helper := ThingMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}
