// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import "reflect"
import "strings"

type Alpha struct {
	// beta corresponds to the JSON schema field "beta".
	beta Beta `json:"beta,omitempty,omitzero" yaml:"beta,omitempty" mapstructure:"beta,omitempty"`

	// eta corresponds to the JSON schema field "eta".
	eta *Eta `json:"eta,omitempty,omitzero" yaml:"eta,omitempty" mapstructure:"eta,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

func (o *Alpha) Beta() Beta {
	return o.beta
}

func (o *Alpha) Eta() *Eta {
	return o.eta
}

type Beta interface{}

type Eta struct {
	// epsilon corresponds to the JSON schema field "epsilon".
	epsilon string `json:"epsilon" yaml:"epsilon" mapstructure:"epsilon"`

	// theta corresponds to the JSON schema field "theta".
	theta Theta `json:"theta" yaml:"theta" mapstructure:"theta"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

func (o *Eta) Epsilon() string {
	return o.epsilon
}

func (o *Eta) Theta() Theta {
	return o.theta
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Eta) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["epsilon"]; raw != nil && !ok {
		return fmt.Errorf("field epsilon in Eta: required")
	}
	if _, ok := raw["theta"]; raw != nil && !ok {
		return fmt.Errorf("field theta in Eta: required")
	}
	type EtaHelper struct {
		Epsilon string `json:"epsilon"`
		Theta   Theta  `json:"theta"`
	}
	type Plain Eta
	var helper EtaHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.epsilon = helper.Epsilon
	plain.theta = helper.Theta
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = Eta(plain)
	return nil
}

type Iota struct {
	// DESCRIPTION
	kappa *Iotakappa `json:"kappa,omitempty,omitzero" yaml:"kappa,omitempty" mapstructure:"kappa,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

func (o *Iota) Kappa() *Iotakappa {
	return o.kappa
}

// DESCRIPTION
type Iotakappa struct {
	// lambda corresponds to the JSON schema field "lambda".
	lambda []IotakappalambdaElem `json:"lambda,omitempty,omitzero" yaml:"lambda,omitempty" mapstructure:"lambda,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

func (o *Iotakappa) Lambda() []IotakappalambdaElem {
	return o.lambda
}

type IotakappalambdaElem struct {
	// sigma corresponds to the JSON schema field "sigma".
	sigma *Alpha `json:"sigma,omitempty,omitzero" yaml:"sigma,omitempty" mapstructure:"sigma,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

func (o *IotakappalambdaElem) Sigma() *Alpha {
	return o.sigma
}

type PropertiesJson struct {
	// iota corresponds to the JSON schema field "iota".
	iota Iota `json:"iota" yaml:"iota" mapstructure:"iota"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

func (o *PropertiesJson) Iota() Iota {
	return o.iota
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PropertiesJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["iota"]; raw != nil && !ok {
		return fmt.Errorf("field iota in PropertiesJson: required")
	}
	type PropertiesJsonHelper struct {
		Iota Iota `json:"iota"`
	}
	type Plain PropertiesJson
	var helper PropertiesJsonHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.iota = helper.Iota
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = PropertiesJson(plain)
	return nil
}

type Theta int

// UnmarshalJSON implements json.Unmarshaler.
func (j *Theta) UnmarshalJSON(value []byte) error {
	type Plain Theta
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 65535 < plain {
		return fmt.Errorf("field %s: must be <= %v", "", 65535)
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = Theta(plain)
	return nil
}
