// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

func NewNillabilityBuilder(o *Nillability) *NillabilityBuilder {
	if o == nil {
		return &NillabilityBuilder{}
	}
	return &NillabilityBuilder{
		name: o.name,
	}
}

type Nillability struct {
	// name corresponds to the JSON schema field "name".
	name *map[bool]string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type NillabilityBuilder struct {
	name *map[bool]string
}

func (b *NillabilityBuilder) Build() *Nillability {
	return &Nillability{
		name: b.name,
	}
}

func (b *NillabilityBuilder) WithName(v *map[bool]string) *NillabilityBuilder {
	b.name = v
	return b
}

func (o *Nillability) Clone() *NillabilityBuilder {
	return NewNillabilityBuilder(o)
}

func (o *Nillability) Name() *map[bool]string {
	return o.name
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Nillability) UnmarshalJSON(value []byte) error {
	type NillabilityHelper struct {
		Name *map[bool]string `json:"name",omitempty`
	}
	type Plain Nillability
	var helper NillabilityHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = Nillability(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Nillability) MarshalJSON() ([]byte, error) {
	type NillabilityMarshalHelper struct {
		Name *map[bool]string `json:"name",omitempty`
	}
	helper := NillabilityMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Nillability) UnmarshalYAML(value *yaml.Node) error {
	type Plain Nillability
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Nillability(plain)
	return nil
}
