// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"

type MaxItemsJson struct {
	// mynestedarray corresponds to the JSON schema field "myNestedArray".
	mynestedarray [][]interface{} `json:"myNestedArray,omitempty,omitzero" yaml:"myNestedArray,omitempty" mapstructure:"myNestedArray,omitempty"`

	// mystringarray corresponds to the JSON schema field "myStringArray".
	mystringarray []string `json:"myStringArray,omitempty,omitzero" yaml:"myStringArray,omitempty" mapstructure:"myStringArray,omitempty"`
}

func (o *MaxItemsJson) MyNestedArray() [][]interface{} {
	return o.mynestedarray
}

func (o *MaxItemsJson) MyStringArray() []string {
	return o.mystringarray
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MaxItemsJson) UnmarshalJSON(value []byte) error {
	type MaxItemsJsonHelper struct {
		Mynestedarray [][]interface{} `json:"myNestedArray",omitempty`
		Mystringarray []string        `json:"myStringArray",omitempty`
	}
	type Plain MaxItemsJson
	var helper MaxItemsJsonHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mynestedarray = helper.Mynestedarray
	plain.mystringarray = helper.Mystringarray
	if len(plain.mynestedarray) > 5 {
		return fmt.Errorf("field %s length: must be <= %d", "myNestedArray", 5)
	}
	for i1 := range plain.mynestedarray {
		if len(plain.mynestedarray[i1]) > 5 {
			return fmt.Errorf("field %s length: must be <= %d", fmt.Sprintf("myNestedArray[%d]", i1), 5)
		}
	}
	if len(plain.mystringarray) > 5 {
		return fmt.Errorf("field %s length: must be <= %d", "myStringArray", 5)
	}
	*j = MaxItemsJson(plain)
	return nil
}
