// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type IntegerDefault struct {
	// count corresponds to the JSON schema field "count".
	count int `json:"count" yaml:"count" mapstructure:"count"`

	// nullablecount corresponds to the JSON schema field "nullableCount".
	nullablecount IntegerDefaultnullablecount `json:"nullableCount" yaml:"nullableCount" mapstructure:"nullableCount"`

	// programid corresponds to the JSON schema field "programId".
	programid int `json:"programId" yaml:"programId" mapstructure:"programId"`
}

type IntegerDefaultBuilder struct {
	count int

	nullablecount IntegerDefaultnullablecount

	programid int
}

func (b *IntegerDefaultBuilder) Build() *IntegerDefault {
	return &IntegerDefault{
		count:         b.count,
		nullablecount: b.nullablecount,
		programid:     b.programid,
	}
}

func (b *IntegerDefaultBuilder) WithCount(v int) *IntegerDefaultBuilder {
	b.count = v
	return b
}

func (b *IntegerDefaultBuilder) WithNullableCount(v IntegerDefaultnullablecount) *IntegerDefaultBuilder {
	b.nullablecount = v
	return b
}

func (b *IntegerDefaultBuilder) WithProgramId(v int) *IntegerDefaultBuilder {
	b.programid = v
	return b
}

func (o *IntegerDefault) Count() int {
	return o.count
}

func (o *IntegerDefault) NullableCount() IntegerDefaultnullablecount {
	return o.nullablecount
}

func (o *IntegerDefault) ProgramId() int {
	return o.programid
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IntegerDefault) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["count"]; raw != nil && !ok {
		return fmt.Errorf("field count in IntegerDefault: required")
	}
	if _, ok := raw["nullableCount"]; raw != nil && !ok {
		return fmt.Errorf("field nullableCount in IntegerDefault: required")
	}
	if _, ok := raw["programId"]; raw != nil && !ok {
		return fmt.Errorf("field programId in IntegerDefault: required")
	}
	type IntegerDefaultHelper struct {
		Count         int                         `json:"count"`
		Nullablecount IntegerDefaultnullablecount `json:"nullableCount"`
		Programid     int                         `json:"programId"`
	}
	type Plain IntegerDefault
	var helper IntegerDefaultHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.count = helper.Count
	plain.nullablecount = helper.Nullablecount
	plain.programid = helper.Programid
	if v, ok := raw["count"]; !ok || v == nil {
		plain.count = 42
	}
	if v, ok := raw["nullableCount"]; !ok || v == nil {
		defaultInt := 0
		plain.nullablecount = &defaultInt

	}
	if v, ok := raw["programId"]; !ok || v == nil {
		plain.programid = 0
	}
	*j = IntegerDefault(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *IntegerDefault) MarshalJSON() ([]byte, error) {
	type IntegerDefaultMarshalHelper struct {
		Count         int                         `json:"count"`
		Nullablecount IntegerDefaultnullablecount `json:"nullableCount"`
		Programid     int                         `json:"programId"`
	}
	helper := IntegerDefaultMarshalHelper{
		Count:         j.count,
		Nullablecount: j.nullablecount,
		Programid:     j.programid,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *IntegerDefault) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["count"]; raw != nil && !ok {
		return fmt.Errorf("field count in IntegerDefault: required")
	}
	if _, ok := raw["nullableCount"]; raw != nil && !ok {
		return fmt.Errorf("field nullableCount in IntegerDefault: required")
	}
	if _, ok := raw["programId"]; raw != nil && !ok {
		return fmt.Errorf("field programId in IntegerDefault: required")
	}
	type Plain IntegerDefault
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if v, ok := raw["count"]; !ok || v == nil {
		plain.count = 42
	}
	if v, ok := raw["nullableCount"]; !ok || v == nil {
		defaultInt := 0
		plain.nullablecount = &defaultInt

	}
	if v, ok := raw["programId"]; !ok || v == nil {
		plain.programid = 0
	}
	*j = IntegerDefault(plain)
	return nil
}

type IntegerDefaultnullablecount *int

func NewIntegerDefaultBuilder(o *IntegerDefault) *IntegerDefaultBuilder {
	if o == nil {
		return &IntegerDefaultBuilder{}
	}
	return &IntegerDefaultBuilder{
		count:         o.count,
		nullablecount: o.nullablecount,
		programid:     o.programid,
	}
}
