// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

func NewReadOnlyBuilder(o *ReadOnly) *ReadOnlyBuilder {
	if o == nil {
		return &ReadOnlyBuilder{}
	}
	return &ReadOnlyBuilder{
		myreadonlystring: o.myreadonlystring,
		mystring:         o.mystring,
	}
}

type ReadOnly struct {
	// myreadonlystring corresponds to the JSON schema field "myReadOnlyString".
	myreadonlystring *string `json:"myReadOnlyString,omitempty,omitzero" yaml:"myReadOnlyString,omitempty" mapstructure:"myReadOnlyString,omitempty"`

	// mystring corresponds to the JSON schema field "myString".
	mystring string `json:"myString" yaml:"myString" mapstructure:"myString"`
}

type ReadOnlyBuilder struct {
	myreadonlystring *string

	mystring string
}

func (b *ReadOnlyBuilder) Build() *ReadOnly {
	return &ReadOnly{
		myreadonlystring: b.myreadonlystring,
		mystring:         b.mystring,
	}
}

func (b *ReadOnlyBuilder) WithMyReadOnlyString(v *string) *ReadOnlyBuilder {
	b.myreadonlystring = v
	return b
}

func (b *ReadOnlyBuilder) WithMyString(v string) *ReadOnlyBuilder {
	b.mystring = v
	return b
}

func (o *ReadOnly) MyReadOnlyString() *string {
	return o.myreadonlystring
}

func (o *ReadOnly) MyString() string {
	return o.mystring
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReadOnly) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myString"]; raw != nil && !ok {
		return fmt.Errorf("field myString in ReadOnly: required")
	}
	if _, ok := raw["myReadOnlyString"]; raw != nil && ok {
		return fmt.Errorf("field myReadOnlyString in ReadOnly: read only")
	}
	type ReadOnlyHelper struct {
		Myreadonlystring *string `json:"myReadOnlyString",omitempty`
		Mystring         string  `json:"myString"`
	}
	type Plain ReadOnly
	var helper ReadOnlyHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myreadonlystring = helper.Myreadonlystring
	plain.mystring = helper.Mystring
	*j = ReadOnly(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *ReadOnly) MarshalJSON() ([]byte, error) {
	type ReadOnlyMarshalHelper struct {
		Myreadonlystring *string `json:"myReadOnlyString",omitempty`
		Mystring         string  `json:"myString"`
	}
	helper := ReadOnlyMarshalHelper{
		Myreadonlystring: j.myreadonlystring,
		Mystring:         j.mystring,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ReadOnly) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["myString"]; raw != nil && !ok {
		return fmt.Errorf("field myString in ReadOnly: required")
	}
	if _, ok := raw["myReadOnlyString"]; raw != nil && ok {
		return fmt.Errorf("field myReadOnlyString in ReadOnly: read only")
	}
	type Plain ReadOnly
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = ReadOnly(plain)
	return nil
}
