// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "reflect"

type License string

const LicenseGPL30 License = "GPL-3.0"
const LicenseMIT License = "MIT"
const LicenseWildcard License = "*"

type License_1 string

const License_1_GPL30 License_1 = "GPL-3.0+"
const License_1_MIT License_1 = "MIT+"
const License_1_Wildcard License_1 = "*"

var enumValues_License_1 = []interface{}{
	"GPL-3.0+",
	"MIT+",
	"*",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *License_1) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_License_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_License_1, v)
	}
	*j = License_1(v)
	return nil
}

var enumValues_License = []interface{}{
	"GPL-3.0",
	"MIT",
	"*",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *License) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_License {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_License, v)
	}
	*j = License(v)
	return nil
}

type SpecialCharactersJson struct {
	// plainlicenses corresponds to the JSON schema field "plainLicenses".
	plainlicenses *SpecialCharactersJsonplainlicenses `json:"plainLicenses,omitempty,omitzero" yaml:"plainLicenses,omitempty" mapstructure:"plainLicenses,omitempty"`

	// plainlicensesref corresponds to the JSON schema field "plainLicensesRef".
	plainlicensesref []License `json:"plainLicensesRef,omitempty,omitzero" yaml:"plainLicensesRef,omitempty" mapstructure:"plainLicensesRef,omitempty"`

	// pluslicenses corresponds to the JSON schema field "plusLicenses".
	pluslicenses *SpecialCharactersJsonpluslicenses `json:"plusLicenses,omitempty,omitzero" yaml:"plusLicenses,omitempty" mapstructure:"plusLicenses,omitempty"`

	// pluslicensesref corresponds to the JSON schema field "plusLicensesRef".
	pluslicensesref []License_1 `json:"plusLicensesRef,omitempty,omitzero" yaml:"plusLicensesRef,omitempty" mapstructure:"plusLicensesRef,omitempty"`
}

func (o *SpecialCharactersJson) PlainLicenses() *SpecialCharactersJsonplainlicenses {
	return o.plainlicenses
}

func (o *SpecialCharactersJson) PlainLicensesRef() []License {
	return o.plainlicensesref
}

func (o *SpecialCharactersJson) PlusLicenses() *SpecialCharactersJsonpluslicenses {
	return o.pluslicenses
}

func (o *SpecialCharactersJson) PlusLicensesRef() []License_1 {
	return o.pluslicensesref
}

type SpecialCharactersJsonplainlicenses string

const SpecialCharactersJsonplainlicensesGPL30 SpecialCharactersJsonplainlicenses = "GPL-3.0"
const SpecialCharactersJsonplainlicensesMIT SpecialCharactersJsonplainlicenses = "MIT"
const SpecialCharactersJsonplainlicensesWildcard SpecialCharactersJsonplainlicenses = "*"

var enumValues_SpecialCharactersJsonplainlicenses = []interface{}{
	"GPL-3.0",
	"MIT",
	"*",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecialCharactersJsonplainlicenses) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SpecialCharactersJsonplainlicenses {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SpecialCharactersJsonplainlicenses, v)
	}
	*j = SpecialCharactersJsonplainlicenses(v)
	return nil
}

type SpecialCharactersJsonpluslicenses string

const SpecialCharactersJsonpluslicensesGPL30 SpecialCharactersJsonpluslicenses = "GPL-3.0+"
const SpecialCharactersJsonpluslicensesMIT SpecialCharactersJsonpluslicenses = "MIT+"
const SpecialCharactersJsonpluslicensesWildcard SpecialCharactersJsonpluslicenses = "*"

var enumValues_SpecialCharactersJsonpluslicenses = []interface{}{
	"GPL-3.0+",
	"MIT+",
	"*",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecialCharactersJsonpluslicenses) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SpecialCharactersJsonpluslicenses {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SpecialCharactersJsonpluslicenses, v)
	}
	*j = SpecialCharactersJsonpluslicenses(v)
	return nil
}
