// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "regexp"
import "unicode/utf8"

func NewRolloutSpecificationBuilder(o *RolloutSpecification) *RolloutSpecificationBuilder {
	if o == nil {
		return &RolloutSpecificationBuilder{}
	}
	return &RolloutSpecificationBuilder{
		contentversion:    o.contentversion,
		orchestratedsteps: o.orchestratedsteps,
		rolloutmetadata:   o.rolloutmetadata,
	}
}

func NewapplicationsBuilder(o *applications) *applicationsBuilder {
	if o == nil {
		return &applicationsBuilder{}
	}
	return &applicationsBuilder{
		actions:                     o.actions,
		applyacrossserviceresources: o.applyacrossserviceresources,
		names:                       o.names,
	}
}

func NewapplyacrossserviceresourcesBuilder(o *applyacrossserviceresources) *applyacrossserviceresourcesBuilder {
	if o == nil {
		return &applyacrossserviceresourcesBuilder{}
	}
	return &applyacrossserviceresourcesBuilder{
		definitionname:     o.definitionname,
		deployarmresources: o.deployarmresources,
		names:              o.names,
	}
}

func NewbuildsourceBuilder(o *buildsource) *buildsourceBuilder {
	if o == nil {
		return &buildsourceBuilder{}
	}
	return &buildsourceBuilder{
		parameters: o.parameters,
	}
}

func NewconfigurationBuilder(o *configuration) *configurationBuilder {
	if o == nil {
		return &configurationBuilder{}
	}
	return &configurationBuilder{
		servicescope: o.servicescope,
	}
}

func NewemailBuilder(o *email) *emailBuilder {
	if o == nil {
		return &emailBuilder{}
	}
	return &emailBuilder{
		cc:      o.cc,
		options: o.options,
		to:      o.to,
	}
}

func NewincidentBuilder(o *incident) *incidentBuilder {
	if o == nil {
		return &incidentBuilder{}
	}
	return &incidentBuilder{
		options:      o.options,
		properties:   o.properties,
		providertype: o.providertype,
	}
}

func NewincidentoptionsBuilder(o *incidentoptions) *incidentoptionsBuilder {
	if o == nil {
		return &incidentoptionsBuilder{}
	}
	return &incidentoptionsBuilder{
		when: o.when,
	}
}

func NewnotificationBuilder(o *notification) *notificationBuilder {
	if o == nil {
		return &notificationBuilder{}
	}
	return &notificationBuilder{
		email:    o.email,
		incident: o.incident,
	}
}

func NewoptionsBuilder(o *options) *optionsBuilder {
	if o == nil {
		return &optionsBuilder{}
	}
	return &optionsBuilder{
		verbosity: o.verbosity,
		when:      o.when,
	}
}

func NeworchestratedstepBuilder(o *orchestratedstep) *orchestratedstepBuilder {
	if o == nil {
		return &orchestratedstepBuilder{}
	}
	return &orchestratedstepBuilder{
		actions:      o.actions,
		applications: o.applications,
		dependson:    o.dependson,
		name:         o.name,
		targetname:   o.targetname,
		targettype:   o.targettype,
	}
}

func NewparametersBuilder(o *parameters) *parametersBuilder {
	if o == nil {
		return &parametersBuilder{}
	}
	return &parametersBuilder{
		versionfile: o.versionfile,
	}
}

func NewpropertiesBuilder(o *properties) *propertiesBuilder {
	if o == nil {
		return &propertiesBuilder{}
	}
	return &propertiesBuilder{
		connectorid: o.connectorid,
		correlateby: o.correlateby,
		environment: o.environment,
		routingid:   o.routingid,
	}
}

func NewrolloutmetadataBuilder(o *rolloutmetadata) *rolloutmetadataBuilder {
	if o == nil {
		return &rolloutmetadataBuilder{}
	}
	return &rolloutmetadataBuilder{
		buildsource:               o.buildsource,
		configuration:             o.configuration,
		name:                      o.name,
		notification:              o.notification,
		parameterreplacementspath: o.parameterreplacementspath,
		rolloutpolicyreferences:   o.rolloutpolicyreferences,
		rollouttype:               o.rollouttype,
		servicemodelpath:          o.servicemodelpath,
	}
}

func NewrolloutpolicyreferenceBuilder(o *rolloutpolicyreference) *rolloutpolicyreferenceBuilder {
	if o == nil {
		return &rolloutpolicyreferenceBuilder{}
	}
	return &rolloutpolicyreferenceBuilder{
		name:    o.name,
		version: o.version,
	}
}

func NewservicescopeBuilder(o *servicescope) *servicescopeBuilder {
	if o == nil {
		return &servicescopeBuilder{}
	}
	return &servicescopeBuilder{
		specpath: o.specpath,
	}
}

// A document that declares what actions are to be taken as part of an update to an
// Azure Service.
type RolloutSpecification struct {
	// The version of the schema that a document conforms to.
	contentversion string `json:"contentVersion" yaml:"contentVersion" mapstructure:"contentVersion"`

	// The exact sequence of steps that must be executed as part of this rollout.
	orchestratedsteps []orchestratedstep `json:"orchestratedSteps" yaml:"orchestratedSteps" mapstructure:"orchestratedSteps"`

	// The metadata associated with this particular rollout.
	rolloutmetadata rolloutmetadata `json:"rolloutMetadata" yaml:"rolloutMetadata" mapstructure:"rolloutMetadata"`
}

type RolloutSpecificationBuilder struct {
	contentversion string

	orchestratedsteps []orchestratedstep

	rolloutmetadata rolloutmetadata
}

func (b *RolloutSpecificationBuilder) Build() *RolloutSpecification {
	return &RolloutSpecification{
		contentversion:    b.contentversion,
		orchestratedsteps: b.orchestratedsteps,
		rolloutmetadata:   b.rolloutmetadata,
	}
}

func (b *RolloutSpecificationBuilder) WithContentVersion(v string) *RolloutSpecificationBuilder {
	b.contentversion = v
	return b
}

func (b *RolloutSpecificationBuilder) WithOrchestratedSteps(v []orchestratedstep) *RolloutSpecificationBuilder {
	b.orchestratedsteps = v
	return b
}

func (b *RolloutSpecificationBuilder) WithRolloutMetadata(v rolloutmetadata) *RolloutSpecificationBuilder {
	b.rolloutmetadata = v
	return b
}

func (o *RolloutSpecification) Clone() *RolloutSpecificationBuilder {
	return NewRolloutSpecificationBuilder(o)
}

func (o *RolloutSpecification) ContentVersion() string {
	return o.contentversion
}

func (o *RolloutSpecification) OrchestratedSteps() []orchestratedstep {
	return o.orchestratedsteps
}

func (o *RolloutSpecification) RolloutMetadata() rolloutmetadata {
	return o.rolloutmetadata
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RolloutSpecification) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["contentVersion"]; raw != nil && !ok {
		return fmt.Errorf("field contentVersion in RolloutSpecification: required")
	}
	if _, ok := raw["orchestratedSteps"]; raw != nil && !ok {
		return fmt.Errorf("field orchestratedSteps in RolloutSpecification: required")
	}
	if _, ok := raw["rolloutMetadata"]; raw != nil && !ok {
		return fmt.Errorf("field rolloutMetadata in RolloutSpecification: required")
	}
	type Plain RolloutSpecification
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^([0-9]+\.)?([0-9]+\.)?([0-9]+\.)?([0-9]+){1}$`, string(plain.contentversion)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "contentversion", `^([0-9]+\.)?([0-9]+\.)?([0-9]+\.)?([0-9]+){1}$`)
	}
	*j = RolloutSpecification(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RolloutSpecification) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["contentVersion"]; raw != nil && !ok {
		return fmt.Errorf("field contentVersion in RolloutSpecification: required")
	}
	if _, ok := raw["orchestratedSteps"]; raw != nil && !ok {
		return fmt.Errorf("field orchestratedSteps in RolloutSpecification: required")
	}
	if _, ok := raw["rolloutMetadata"]; raw != nil && !ok {
		return fmt.Errorf("field rolloutMetadata in RolloutSpecification: required")
	}
	type RolloutSpecificationHelper struct {
		Contentversion    string             `json:"contentVersion"`
		Orchestratedsteps []orchestratedstep `json:"orchestratedSteps"`
		Rolloutmetadata   rolloutmetadata    `json:"rolloutMetadata"`
	}
	type Plain RolloutSpecification
	var helper RolloutSpecificationHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.contentversion = helper.Contentversion
	plain.orchestratedsteps = helper.Orchestratedsteps
	plain.rolloutmetadata = helper.Rolloutmetadata
	if matched, _ := regexp.MatchString(`^([0-9]+\.)?([0-9]+\.)?([0-9]+\.)?([0-9]+){1}$`, string(plain.contentversion)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "contentversion", `^([0-9]+\.)?([0-9]+\.)?([0-9]+\.)?([0-9]+){1}$`)
	}
	*j = RolloutSpecification(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *RolloutSpecification) MarshalJSON() ([]byte, error) {
	type RolloutSpecificationMarshalHelper struct {
		Contentversion    string             `json:"contentVersion"`
		Orchestratedsteps []orchestratedstep `json:"orchestratedSteps"`
		Rolloutmetadata   rolloutmetadata    `json:"rolloutMetadata"`
	}
	helper := RolloutSpecificationMarshalHelper{
		Contentversion:    j.contentversion,
		Orchestratedsteps: j.orchestratedsteps,
		Rolloutmetadata:   j.rolloutmetadata,
	}
	return json.Marshal(helper)
}

// The details of applications to be deployed.
type applications struct {
	// The list of actions to be performed.
	actions []string `json:"actions" yaml:"actions" mapstructure:"actions"`

	// The details of the service resources across which the application has to be
	// deployed.
	applyacrossserviceresources applyacrossserviceresources `json:"applyAcrossServiceResources" yaml:"applyAcrossServiceResources" mapstructure:"applyAcrossServiceResources"`

	// The list of the application instance names..
	names []string `json:"names" yaml:"names" mapstructure:"names"`
}

type applicationsBuilder struct {
	actions []string

	applyacrossserviceresources applyacrossserviceresources

	names []string
}

func (b *applicationsBuilder) Build() *applications {
	return &applications{
		actions:                     b.actions,
		applyacrossserviceresources: b.applyacrossserviceresources,
		names:                       b.names,
	}
}

func (b *applicationsBuilder) WithActions(v []string) *applicationsBuilder {
	b.actions = v
	return b
}

func (b *applicationsBuilder) WithApplyAcrossServiceResources(v applyacrossserviceresources) *applicationsBuilder {
	b.applyacrossserviceresources = v
	return b
}

func (b *applicationsBuilder) WithNames(v []string) *applicationsBuilder {
	b.names = v
	return b
}

func (o *applications) Actions() []string {
	return o.actions
}

func (o *applications) ApplyAcrossServiceResources() applyacrossserviceresources {
	return o.applyacrossserviceresources
}

func (o *applications) Clone() *applicationsBuilder {
	return NewapplicationsBuilder(o)
}

func (o *applications) Names() []string {
	return o.names
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *applications) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["actions"]; raw != nil && !ok {
		return fmt.Errorf("field actions in applications: required")
	}
	if _, ok := raw["applyAcrossServiceResources"]; raw != nil && !ok {
		return fmt.Errorf("field applyAcrossServiceResources in applications: required")
	}
	if _, ok := raw["names"]; raw != nil && !ok {
		return fmt.Errorf("field names in applications: required")
	}
	type Plain applications
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = applications(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *applications) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["actions"]; raw != nil && !ok {
		return fmt.Errorf("field actions in applications: required")
	}
	if _, ok := raw["applyAcrossServiceResources"]; raw != nil && !ok {
		return fmt.Errorf("field applyAcrossServiceResources in applications: required")
	}
	if _, ok := raw["names"]; raw != nil && !ok {
		return fmt.Errorf("field names in applications: required")
	}
	type applicationsHelper struct {
		Actions                     []string                    `json:"actions"`
		Applyacrossserviceresources applyacrossserviceresources `json:"applyAcrossServiceResources"`
		Names                       []string                    `json:"names"`
	}
	type Plain applications
	var helper applicationsHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.actions = helper.Actions
	plain.applyacrossserviceresources = helper.Applyacrossserviceresources
	plain.names = helper.Names
	*j = applications(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *applications) MarshalJSON() ([]byte, error) {
	type applicationsMarshalHelper struct {
		Actions                     []string                    `json:"actions"`
		Applyacrossserviceresources applyacrossserviceresources `json:"applyAcrossServiceResources"`
		Names                       []string                    `json:"names"`
	}
	helper := applicationsMarshalHelper{
		Actions:                     j.actions,
		Applyacrossserviceresources: j.applyacrossserviceresources,
		Names:                       j.names,
	}
	return json.Marshal(helper)
}

// The details of the service resources across which the application has to be
// deployed.
type applyacrossserviceresources struct {
	// The service resource definition name.
	definitionname string `json:"definitionName" yaml:"definitionName" mapstructure:"definitionName"`

	// Indicates if the cluster has to be deployed before application deployment.
	deployarmresources *bool `json:"deployArmResources,omitempty,omitzero" yaml:"deployArmResources,omitempty" mapstructure:"deployArmResources,omitempty"`

	// The list of service resource instance names.
	names []string `json:"names" yaml:"names" mapstructure:"names"`
}

type applyacrossserviceresourcesBuilder struct {
	definitionname string

	deployarmresources *bool

	names []string
}

func (b *applyacrossserviceresourcesBuilder) Build() *applyacrossserviceresources {
	return &applyacrossserviceresources{
		definitionname:     b.definitionname,
		deployarmresources: b.deployarmresources,
		names:              b.names,
	}
}

func (b *applyacrossserviceresourcesBuilder) WithDefinitionName(v string) *applyacrossserviceresourcesBuilder {
	b.definitionname = v
	return b
}

func (b *applyacrossserviceresourcesBuilder) WithDeployArmResources(v *bool) *applyacrossserviceresourcesBuilder {
	b.deployarmresources = v
	return b
}

func (b *applyacrossserviceresourcesBuilder) WithNames(v []string) *applyacrossserviceresourcesBuilder {
	b.names = v
	return b
}

func (o *applyacrossserviceresources) Clone() *applyacrossserviceresourcesBuilder {
	return NewapplyacrossserviceresourcesBuilder(o)
}

func (o *applyacrossserviceresources) DefinitionName() string {
	return o.definitionname
}

func (o *applyacrossserviceresources) DeployArmResources() *bool {
	return o.deployarmresources
}

func (o *applyacrossserviceresources) Names() []string {
	return o.names
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *applyacrossserviceresources) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["definitionName"]; raw != nil && !ok {
		return fmt.Errorf("field definitionName in applyacrossserviceresources: required")
	}
	if _, ok := raw["names"]; raw != nil && !ok {
		return fmt.Errorf("field names in applyacrossserviceresources: required")
	}
	type applyacrossserviceresourcesHelper struct {
		Definitionname     string   `json:"definitionName"`
		Deployarmresources *bool    `json:"deployArmResources,omitempty"`
		Names              []string `json:"names"`
	}
	type Plain applyacrossserviceresources
	var helper applyacrossserviceresourcesHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.definitionname = helper.Definitionname
	plain.deployarmresources = helper.Deployarmresources
	plain.names = helper.Names
	*j = applyacrossserviceresources(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *applyacrossserviceresources) MarshalJSON() ([]byte, error) {
	type applyacrossserviceresourcesMarshalHelper struct {
		Definitionname     string   `json:"definitionName"`
		Deployarmresources *bool    `json:"deployArmResources,omitempty"`
		Names              []string `json:"names"`
	}
	helper := applyacrossserviceresourcesMarshalHelper{
		Definitionname:     j.definitionname,
		Deployarmresources: j.deployarmresources,
		Names:              j.names,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *applyacrossserviceresources) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["definitionName"]; raw != nil && !ok {
		return fmt.Errorf("field definitionName in applyacrossserviceresources: required")
	}
	if _, ok := raw["names"]; raw != nil && !ok {
		return fmt.Errorf("field names in applyacrossserviceresources: required")
	}
	type Plain applyacrossserviceresources
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = applyacrossserviceresources(plain)
	return nil
}

// The location of the build to use for this particular rollout.
type buildsource struct {
	// The parameters that define how to access and/or prepare the build from this
	// build source.
	parameters parameters `json:"parameters" yaml:"parameters" mapstructure:"parameters"`
}

type buildsourceBuilder struct {
	parameters parameters
}

func (b *buildsourceBuilder) Build() *buildsource {
	return &buildsource{
		parameters: b.parameters,
	}
}

func (b *buildsourceBuilder) WithParameters(v parameters) *buildsourceBuilder {
	b.parameters = v
	return b
}

func (o *buildsource) Clone() *buildsourceBuilder {
	return NewbuildsourceBuilder(o)
}

func (o *buildsource) Parameters() parameters {
	return o.parameters
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *buildsource) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["parameters"]; raw != nil && !ok {
		return fmt.Errorf("field parameters in buildsource: required")
	}
	type buildsourceHelper struct {
		Parameters parameters `json:"parameters"`
	}
	type Plain buildsource
	var helper buildsourceHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.parameters = helper.Parameters
	*j = buildsource(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *buildsource) MarshalJSON() ([]byte, error) {
	type buildsourceMarshalHelper struct {
		Parameters parameters `json:"parameters"`
	}
	helper := buildsourceMarshalHelper{
		Parameters: j.parameters,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *buildsource) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["parameters"]; raw != nil && !ok {
		return fmt.Errorf("field parameters in buildsource: required")
	}
	type Plain buildsource
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = buildsource(plain)
	return nil
}

// Option to use configuration specification file directly in rollout.
type configuration struct {
	// Service scope configuration setting
	servicescope *servicescope `json:"serviceScope,omitempty,omitzero" yaml:"serviceScope,omitempty" mapstructure:"serviceScope,omitempty"`
}

type configurationBuilder struct {
	servicescope *servicescope
}

func (b *configurationBuilder) Build() *configuration {
	return &configuration{
		servicescope: b.servicescope,
	}
}

func (b *configurationBuilder) WithServiceScope(v *servicescope) *configurationBuilder {
	b.servicescope = v
	return b
}

func (o *configuration) Clone() *configurationBuilder {
	return NewconfigurationBuilder(o)
}

func (o *configuration) ServiceScope() *servicescope {
	return o.servicescope
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *configuration) UnmarshalYAML(value *yaml.Node) error {
	type Plain configuration
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = configuration(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *configuration) UnmarshalJSON(value []byte) error {
	type configurationHelper struct {
		Servicescope *servicescope `json:"serviceScope,omitempty"`
	}
	type Plain configuration
	var helper configurationHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.servicescope = helper.Servicescope
	*j = configuration(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *configuration) MarshalJSON() ([]byte, error) {
	type configurationMarshalHelper struct {
		Servicescope *servicescope `json:"serviceScope,omitempty"`
	}
	helper := configurationMarshalHelper{
		Servicescope: j.servicescope,
	}
	return json.Marshal(helper)
}

// Email Notification definitions
type email struct {
	// Cc email addresses list separator with ',;'
	cc *string `json:"cc,omitempty,omitzero" yaml:"cc,omitempty" mapstructure:"cc,omitempty"`

	// Conditions of when to sending the email, default will send on all start, error,
	// complete events
	options *options `json:"options,omitempty,omitzero" yaml:"options,omitempty" mapstructure:"options,omitempty"`

	// To email addresses list separator with ',;'
	to string `json:"to" yaml:"to" mapstructure:"to"`
}

type emailBuilder struct {
	cc *string

	options *options

	to string
}

func (b *emailBuilder) Build() *email {
	return &email{
		cc:      b.cc,
		options: b.options,
		to:      b.to,
	}
}

func (b *emailBuilder) WithCc(v *string) *emailBuilder {
	b.cc = v
	return b
}

func (b *emailBuilder) WithOptions(v *options) *emailBuilder {
	b.options = v
	return b
}

func (b *emailBuilder) WithTo(v string) *emailBuilder {
	b.to = v
	return b
}

func (o *email) Cc() *string {
	return o.cc
}

func (o *email) Clone() *emailBuilder {
	return NewemailBuilder(o)
}

func (o *email) Options() *options {
	return o.options
}

func (o *email) To() string {
	return o.to
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *email) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in email: required")
	}
	type Plain email
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = email(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *email) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in email: required")
	}
	type emailHelper struct {
		Cc      *string  `json:"cc,omitempty"`
		Options *options `json:"options,omitempty"`
		To      string   `json:"to"`
	}
	type Plain email
	var helper emailHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.cc = helper.Cc
	plain.options = helper.Options
	plain.to = helper.To
	*j = email(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *email) MarshalJSON() ([]byte, error) {
	type emailMarshalHelper struct {
		Cc      *string  `json:"cc,omitempty"`
		Options *options `json:"options,omitempty"`
		To      string   `json:"to"`
	}
	helper := emailMarshalHelper{
		Cc:      j.cc,
		Options: j.options,
		To:      j.to,
	}
	return json.Marshal(helper)
}

// Incident notification definitions
type incident struct {
	// Conditions of when to create incidents, default will send on every error
	options *incidentoptions `json:"options,omitempty,omitzero" yaml:"options,omitempty" mapstructure:"options,omitempty"`

	// The incident properties
	properties properties `json:"properties" yaml:"properties" mapstructure:"properties"`

	// The incident provider type
	providertype string `json:"providerType" yaml:"providerType" mapstructure:"providerType"`
}

type incidentBuilder struct {
	options *incidentoptions

	properties properties

	providertype string
}

func (b *incidentBuilder) Build() *incident {
	return &incident{
		options:      b.options,
		properties:   b.properties,
		providertype: b.providertype,
	}
}

func (b *incidentBuilder) WithOptions(v *incidentoptions) *incidentBuilder {
	b.options = v
	return b
}

func (b *incidentBuilder) WithProperties(v properties) *incidentBuilder {
	b.properties = v
	return b
}

func (b *incidentBuilder) WithProviderType(v string) *incidentBuilder {
	b.providertype = v
	return b
}

func (o *incident) Clone() *incidentBuilder {
	return NewincidentBuilder(o)
}

func (o *incident) Options() *incidentoptions {
	return o.options
}

func (o *incident) Properties() properties {
	return o.properties
}

func (o *incident) ProviderType() string {
	return o.providertype
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *incident) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["properties"]; raw != nil && !ok {
		return fmt.Errorf("field properties in incident: required")
	}
	if _, ok := raw["providerType"]; raw != nil && !ok {
		return fmt.Errorf("field providerType in incident: required")
	}
	type Plain incident
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = incident(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *incident) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["properties"]; raw != nil && !ok {
		return fmt.Errorf("field properties in incident: required")
	}
	if _, ok := raw["providerType"]; raw != nil && !ok {
		return fmt.Errorf("field providerType in incident: required")
	}
	type incidentHelper struct {
		Options      *incidentoptions `json:"options,omitempty"`
		Properties   properties       `json:"properties"`
		Providertype string           `json:"providerType"`
	}
	type Plain incident
	var helper incidentHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.options = helper.Options
	plain.properties = helper.Properties
	plain.providertype = helper.Providertype
	*j = incident(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *incident) MarshalJSON() ([]byte, error) {
	type incidentMarshalHelper struct {
		Options      *incidentoptions `json:"options,omitempty"`
		Properties   properties       `json:"properties"`
		Providertype string           `json:"providerType"`
	}
	helper := incidentMarshalHelper{
		Options:      j.options,
		Properties:   j.properties,
		Providertype: j.providertype,
	}
	return json.Marshal(helper)
}

// Conditions of when to create incidents, default will send on every error
type incidentoptions struct {
	// when corresponds to the JSON schema field "when".
	when []string `json:"when,omitempty,omitzero" yaml:"when,omitempty" mapstructure:"when,omitempty"`
}

type incidentoptionsBuilder struct {
	when []string
}

func (b *incidentoptionsBuilder) Build() *incidentoptions {
	return &incidentoptions{
		when: b.when,
	}
}

func (b *incidentoptionsBuilder) WithWhen(v []string) *incidentoptionsBuilder {
	b.when = v
	return b
}

func (o *incidentoptions) Clone() *incidentoptionsBuilder {
	return NewincidentoptionsBuilder(o)
}

func (o *incidentoptions) When() []string {
	return o.when
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *incidentoptions) UnmarshalYAML(value *yaml.Node) error {
	type Plain incidentoptions
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = incidentoptions(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *incidentoptions) UnmarshalJSON(value []byte) error {
	type incidentoptionsHelper struct {
		When []string `json:"when,omitempty"`
	}
	type Plain incidentoptions
	var helper incidentoptionsHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.when = helper.When
	*j = incidentoptions(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *incidentoptions) MarshalJSON() ([]byte, error) {
	type incidentoptionsMarshalHelper struct {
		When []string `json:"when,omitempty"`
	}
	helper := incidentoptionsMarshalHelper{
		When: j.when,
	}
	return json.Marshal(helper)
}

// Notification definitions
type notification struct {
	// Email Notification definitions
	email *email `json:"email,omitempty,omitzero" yaml:"email,omitempty" mapstructure:"email,omitempty"`

	// Incident notification definitions
	incident *incident `json:"incident,omitempty,omitzero" yaml:"incident,omitempty" mapstructure:"incident,omitempty"`
}

type notificationBuilder struct {
	email *email

	incident *incident
}

func (b *notificationBuilder) Build() *notification {
	return &notification{
		email:    b.email,
		incident: b.incident,
	}
}

func (b *notificationBuilder) WithEmail(v *email) *notificationBuilder {
	b.email = v
	return b
}

func (b *notificationBuilder) WithIncident(v *incident) *notificationBuilder {
	b.incident = v
	return b
}

func (o *notification) Clone() *notificationBuilder {
	return NewnotificationBuilder(o)
}

func (o *notification) Email() *email {
	return o.email
}

func (o *notification) Incident() *incident {
	return o.incident
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *notification) UnmarshalYAML(value *yaml.Node) error {
	type Plain notification
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = notification(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *notification) UnmarshalJSON(value []byte) error {
	type notificationHelper struct {
		Email    *email    `json:"email,omitempty"`
		Incident *incident `json:"incident,omitempty"`
	}
	type Plain notification
	var helper notificationHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.email = helper.Email
	plain.incident = helper.Incident
	*j = notification(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *notification) MarshalJSON() ([]byte, error) {
	type notificationMarshalHelper struct {
		Email    *email    `json:"email,omitempty"`
		Incident *incident `json:"incident,omitempty"`
	}
	helper := notificationMarshalHelper{
		Email:    j.email,
		Incident: j.incident,
	}
	return json.Marshal(helper)
}

// Conditions of when to sending the email, default will send on all start, error,
// complete events
type options struct {
	// 'All': All rollout information, default behavior, SummaryOnly': Only has
	// summary table, no resource deployment details, Compact': Only show rows of
	// failed resource operations.
	verbosity *string `json:"verbosity,omitempty,omitzero" yaml:"verbosity,omitempty" mapstructure:"verbosity,omitempty"`

	// when corresponds to the JSON schema field "when".
	when []string `json:"when,omitempty,omitzero" yaml:"when,omitempty" mapstructure:"when,omitempty"`
}

type optionsBuilder struct {
	verbosity *string

	when []string
}

func (b *optionsBuilder) Build() *options {
	return &options{
		verbosity: b.verbosity,
		when:      b.when,
	}
}

func (b *optionsBuilder) WithVerbosity(v *string) *optionsBuilder {
	b.verbosity = v
	return b
}

func (b *optionsBuilder) WithWhen(v []string) *optionsBuilder {
	b.when = v
	return b
}

func (o *options) Clone() *optionsBuilder {
	return NewoptionsBuilder(o)
}

func (o *options) Verbosity() *string {
	return o.verbosity
}

func (o *options) When() []string {
	return o.when
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *options) UnmarshalYAML(value *yaml.Node) error {
	type Plain options
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.verbosity != nil {
		if matched, _ := regexp.MatchString(`(?i)(^All$|^SummaryOnly$|^Compact$)`, string(*plain.verbosity)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "verbosity", `(?i)(^All$|^SummaryOnly$|^Compact$)`)
		}
	}
	*j = options(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *options) UnmarshalJSON(value []byte) error {
	type optionsHelper struct {
		Verbosity *string  `json:"verbosity,omitempty"`
		When      []string `json:"when,omitempty"`
	}
	type Plain options
	var helper optionsHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.verbosity = helper.Verbosity
	plain.when = helper.When
	if plain.verbosity != nil {
		if matched, _ := regexp.MatchString(`(?i)(^All$|^SummaryOnly$|^Compact$)`, string(*plain.verbosity)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "verbosity", `(?i)(^All$|^SummaryOnly$|^Compact$)`)
		}
	}
	*j = options(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *options) MarshalJSON() ([]byte, error) {
	type optionsMarshalHelper struct {
		Verbosity *string  `json:"verbosity,omitempty"`
		When      []string `json:"when,omitempty"`
	}
	helper := optionsMarshalHelper{
		Verbosity: j.verbosity,
		When:      j.when,
	}
	return json.Marshal(helper)
}

// An individual deployment step in the rollout of an Azure service.
type orchestratedstep struct {
	// The actions that must take place as part of this step. The actions will be
	// executed in the order that they are declared. The action names must be unique.
	// If this is an Extension action, the name of the extension must exist in the
	// 'Extensions' block in  RolloutParameters.
	actions []string `json:"actions,omitempty,omitzero" yaml:"actions,omitempty" mapstructure:"actions,omitempty"`

	// The details of applications to be deployed.
	applications *applications `json:"applications,omitempty,omitzero" yaml:"applications,omitempty" mapstructure:"applications,omitempty"`

	// The names of the rollout steps that must be executed prior to the current step
	// being executed.
	dependson []string `json:"dependsOn,omitempty,omitzero" yaml:"dependsOn,omitempty" mapstructure:"dependsOn,omitempty"`

	// The name of the rollout step.
	name string `json:"name" yaml:"name" mapstructure:"name"`

	// The unique identifier of the target that is to be updated.
	targetname *string `json:"targetName,omitempty,omitzero" yaml:"targetName,omitempty" mapstructure:"targetName,omitempty"`

	// The type of the intended target of this rollout.
	targettype string `json:"targetType" yaml:"targetType" mapstructure:"targetType"`
}

type orchestratedstepBuilder struct {
	actions []string

	applications *applications

	dependson []string

	name string

	targetname *string

	targettype string
}

func (b *orchestratedstepBuilder) Build() *orchestratedstep {
	return &orchestratedstep{
		actions:      b.actions,
		applications: b.applications,
		dependson:    b.dependson,
		name:         b.name,
		targetname:   b.targetname,
		targettype:   b.targettype,
	}
}

func (b *orchestratedstepBuilder) WithActions(v []string) *orchestratedstepBuilder {
	b.actions = v
	return b
}

func (b *orchestratedstepBuilder) WithApplications(v *applications) *orchestratedstepBuilder {
	b.applications = v
	return b
}

func (b *orchestratedstepBuilder) WithDependsOn(v []string) *orchestratedstepBuilder {
	b.dependson = v
	return b
}

func (b *orchestratedstepBuilder) WithName(v string) *orchestratedstepBuilder {
	b.name = v
	return b
}

func (b *orchestratedstepBuilder) WithTargetName(v *string) *orchestratedstepBuilder {
	b.targetname = v
	return b
}

func (b *orchestratedstepBuilder) WithTargetType(v string) *orchestratedstepBuilder {
	b.targettype = v
	return b
}

func (o *orchestratedstep) Actions() []string {
	return o.actions
}

func (o *orchestratedstep) Applications() *applications {
	return o.applications
}

func (o *orchestratedstep) Clone() *orchestratedstepBuilder {
	return NeworchestratedstepBuilder(o)
}

func (o *orchestratedstep) DependsOn() []string {
	return o.dependson
}

func (o *orchestratedstep) Name() string {
	return o.name
}

func (o *orchestratedstep) TargetName() *string {
	return o.targetname
}

func (o *orchestratedstep) TargetType() string {
	return o.targettype
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *orchestratedstep) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in orchestratedstep: required")
	}
	if _, ok := raw["targetType"]; raw != nil && !ok {
		return fmt.Errorf("field targetType in orchestratedstep: required")
	}
	type orchestratedstepHelper struct {
		Actions      []string      `json:"actions,omitempty"`
		Applications *applications `json:"applications,omitempty"`
		Dependson    []string      `json:"dependsOn,omitempty"`
		Name         string        `json:"name"`
		Targetname   *string       `json:"targetName,omitempty"`
		Targettype   string        `json:"targetType"`
	}
	type Plain orchestratedstep
	var helper orchestratedstepHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.actions = helper.Actions
	plain.applications = helper.Applications
	plain.dependson = helper.Dependson
	plain.name = helper.Name
	plain.targetname = helper.Targetname
	plain.targettype = helper.Targettype
	if utf8.RuneCountInString(string(plain.name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if plain.targetname != nil && utf8.RuneCountInString(string(*plain.targetname)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "targetName", 1)
	}
	if matched, _ := regexp.MatchString(`(?i)(^ServiceResourceGroup$|^ServiceResource$|^Application$)`, string(plain.targettype)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "targettype", `(?i)(^ServiceResourceGroup$|^ServiceResource$|^Application$)`)
	}
	*j = orchestratedstep(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *orchestratedstep) MarshalJSON() ([]byte, error) {
	type orchestratedstepMarshalHelper struct {
		Actions      []string      `json:"actions,omitempty"`
		Applications *applications `json:"applications,omitempty"`
		Dependson    []string      `json:"dependsOn,omitempty"`
		Name         string        `json:"name"`
		Targetname   *string       `json:"targetName,omitempty"`
		Targettype   string        `json:"targetType"`
	}
	helper := orchestratedstepMarshalHelper{
		Actions:      j.actions,
		Applications: j.applications,
		Dependson:    j.dependson,
		Name:         j.name,
		Targetname:   j.targetname,
		Targettype:   j.targettype,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *orchestratedstep) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in orchestratedstep: required")
	}
	if _, ok := raw["targetType"]; raw != nil && !ok {
		return fmt.Errorf("field targetType in orchestratedstep: required")
	}
	type Plain orchestratedstep
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if plain.targetname != nil && utf8.RuneCountInString(string(*plain.targetname)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "targetName", 1)
	}
	if matched, _ := regexp.MatchString(`(?i)(^ServiceResourceGroup$|^ServiceResource$|^Application$)`, string(plain.targettype)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "targettype", `(?i)(^ServiceResourceGroup$|^ServiceResource$|^Application$)`)
	}
	*j = orchestratedstep(plain)
	return nil
}

// The parameters that define how to access and/or prepare the build from this
// build source.
type parameters struct {
	// The path relative to the Service Group Root which points to the file whose
	// contents represent the version of the build being deployed.
	versionfile string `json:"versionFile" yaml:"versionFile" mapstructure:"versionFile"`
}

type parametersBuilder struct {
	versionfile string
}

func (b *parametersBuilder) Build() *parameters {
	return &parameters{
		versionfile: b.versionfile,
	}
}

func (b *parametersBuilder) WithVersionFile(v string) *parametersBuilder {
	b.versionfile = v
	return b
}

func (o *parameters) Clone() *parametersBuilder {
	return NewparametersBuilder(o)
}

func (o *parameters) VersionFile() string {
	return o.versionfile
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *parameters) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["versionFile"]; raw != nil && !ok {
		return fmt.Errorf("field versionFile in parameters: required")
	}
	type parametersHelper struct {
		Versionfile string `json:"versionFile"`
	}
	type Plain parameters
	var helper parametersHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.versionfile = helper.Versionfile
	*j = parameters(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *parameters) MarshalJSON() ([]byte, error) {
	type parametersMarshalHelper struct {
		Versionfile string `json:"versionFile"`
	}
	helper := parametersMarshalHelper{
		Versionfile: j.versionfile,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *parameters) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["versionFile"]; raw != nil && !ok {
		return fmt.Errorf("field versionFile in parameters: required")
	}
	type Plain parameters
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = parameters(plain)
	return nil
}

// The incident properties
type properties struct {
	// The connector Id for ICM
	connectorid string `json:"connectorId" yaml:"connectorId" mapstructure:"connectorId"`

	// The incident correlation type.
	correlateby *string `json:"correlateBy,omitempty,omitzero" yaml:"correlateBy,omitempty" mapstructure:"correlateBy,omitempty"`

	// The environment of the incidents raising location.
	environment *string `json:"environment,omitempty,omitzero" yaml:"environment,omitempty" mapstructure:"environment,omitempty"`

	// The routing Id for ICM
	routingid string `json:"routingId" yaml:"routingId" mapstructure:"routingId"`
}

type propertiesBuilder struct {
	connectorid string

	correlateby *string

	environment *string

	routingid string
}

func (b *propertiesBuilder) Build() *properties {
	return &properties{
		connectorid: b.connectorid,
		correlateby: b.correlateby,
		environment: b.environment,
		routingid:   b.routingid,
	}
}

func (b *propertiesBuilder) WithConnectorId(v string) *propertiesBuilder {
	b.connectorid = v
	return b
}

func (b *propertiesBuilder) WithCorrelateBy(v *string) *propertiesBuilder {
	b.correlateby = v
	return b
}

func (b *propertiesBuilder) WithEnvironment(v *string) *propertiesBuilder {
	b.environment = v
	return b
}

func (b *propertiesBuilder) WithRoutingId(v string) *propertiesBuilder {
	b.routingid = v
	return b
}

func (o *properties) Clone() *propertiesBuilder {
	return NewpropertiesBuilder(o)
}

func (o *properties) ConnectorId() string {
	return o.connectorid
}

func (o *properties) CorrelateBy() *string {
	return o.correlateby
}

func (o *properties) Environment() *string {
	return o.environment
}

func (o *properties) RoutingId() string {
	return o.routingid
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *properties) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["connectorId"]; raw != nil && !ok {
		return fmt.Errorf("field connectorId in properties: required")
	}
	if _, ok := raw["routingId"]; raw != nil && !ok {
		return fmt.Errorf("field routingId in properties: required")
	}
	type Plain properties
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.correlateby != nil {
		if matched, _ := regexp.MatchString(`(?i)(^rollout$)`, string(*plain.correlateby)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "correlateby", `(?i)(^rollout$)`)
		}
	}
	if plain.environment != nil {
		if matched, _ := regexp.MatchString(`(?i)(^Dogfood$|^Int$|^Ppe$|^Prod$|^Staging$|^Test$)`, string(*plain.environment)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "environment", `(?i)(^Dogfood$|^Int$|^Ppe$|^Prod$|^Staging$|^Test$)`)
		}
	}
	*j = properties(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *properties) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connectorId"]; raw != nil && !ok {
		return fmt.Errorf("field connectorId in properties: required")
	}
	if _, ok := raw["routingId"]; raw != nil && !ok {
		return fmt.Errorf("field routingId in properties: required")
	}
	type propertiesHelper struct {
		Connectorid string  `json:"connectorId"`
		Correlateby *string `json:"correlateBy,omitempty"`
		Environment *string `json:"environment,omitempty"`
		Routingid   string  `json:"routingId"`
	}
	type Plain properties
	var helper propertiesHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.connectorid = helper.Connectorid
	plain.correlateby = helper.Correlateby
	plain.environment = helper.Environment
	plain.routingid = helper.Routingid
	if plain.correlateby != nil {
		if matched, _ := regexp.MatchString(`(?i)(^rollout$)`, string(*plain.correlateby)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "correlateby", `(?i)(^rollout$)`)
		}
	}
	if plain.environment != nil {
		if matched, _ := regexp.MatchString(`(?i)(^Dogfood$|^Int$|^Ppe$|^Prod$|^Staging$|^Test$)`, string(*plain.environment)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "environment", `(?i)(^Dogfood$|^Int$|^Ppe$|^Prod$|^Staging$|^Test$)`)
		}
	}
	*j = properties(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *properties) MarshalJSON() ([]byte, error) {
	type propertiesMarshalHelper struct {
		Connectorid string  `json:"connectorId"`
		Correlateby *string `json:"correlateBy,omitempty"`
		Environment *string `json:"environment,omitempty"`
		Routingid   string  `json:"routingId"`
	}
	helper := propertiesMarshalHelper{
		Connectorid: j.connectorid,
		Correlateby: j.correlateby,
		Environment: j.environment,
		Routingid:   j.routingid,
	}
	return json.Marshal(helper)
}

// The metadata associated with this particular rollout.
type rolloutmetadata struct {
	// The location of the build to use for this particular rollout.
	buildsource buildsource `json:"buildSource" yaml:"buildSource" mapstructure:"buildSource"`

	// Option to use configuration specification file directly in rollout.
	configuration *configuration `json:"configuration,omitempty,omitzero" yaml:"configuration,omitempty" mapstructure:"configuration,omitempty"`

	// The user-specified name of this particular rollout.
	name string `json:"name" yaml:"name" mapstructure:"name"`

	// Notification definitions
	notification *notification `json:"notification,omitempty,omitzero" yaml:"notification,omitempty" mapstructure:"notification,omitempty"`

	// The path relative to the Service Group Root that points to the parameter
	// replacements file.
	parameterreplacementspath *string `json:"parameterReplacementsPath,omitempty,omitzero" yaml:"parameterReplacementsPath,omitempty" mapstructure:"parameterReplacementsPath,omitempty"`

	// List of rollout policy references to use for the rollout.
	rolloutpolicyreferences []rolloutpolicyreference `json:"rolloutPolicyReferences,omitempty,omitzero" yaml:"rolloutPolicyReferences,omitempty" mapstructure:"rolloutPolicyReferences,omitempty"`

	// The scope of this particular rollout.
	rollouttype string `json:"rolloutType" yaml:"rolloutType" mapstructure:"rolloutType"`

	// The path relative to the Service Group Root that points to the service model of
	// the service that is being updated as part of this rollout.
	servicemodelpath string `json:"serviceModelPath" yaml:"serviceModelPath" mapstructure:"serviceModelPath"`
}

type rolloutmetadataBuilder struct {
	buildsource buildsource

	configuration *configuration

	name string

	notification *notification

	parameterreplacementspath *string

	rolloutpolicyreferences []rolloutpolicyreference

	rollouttype string

	servicemodelpath string
}

func (b *rolloutmetadataBuilder) Build() *rolloutmetadata {
	return &rolloutmetadata{
		buildsource:               b.buildsource,
		configuration:             b.configuration,
		name:                      b.name,
		notification:              b.notification,
		parameterreplacementspath: b.parameterreplacementspath,
		rolloutpolicyreferences:   b.rolloutpolicyreferences,
		rollouttype:               b.rollouttype,
		servicemodelpath:          b.servicemodelpath,
	}
}

func (b *rolloutmetadataBuilder) WithBuildSource(v buildsource) *rolloutmetadataBuilder {
	b.buildsource = v
	return b
}

func (b *rolloutmetadataBuilder) WithConfiguration(v *configuration) *rolloutmetadataBuilder {
	b.configuration = v
	return b
}

func (b *rolloutmetadataBuilder) WithName(v string) *rolloutmetadataBuilder {
	b.name = v
	return b
}

func (b *rolloutmetadataBuilder) WithNotification(v *notification) *rolloutmetadataBuilder {
	b.notification = v
	return b
}

func (b *rolloutmetadataBuilder) WithParameterReplacementsPath(v *string) *rolloutmetadataBuilder {
	b.parameterreplacementspath = v
	return b
}

func (b *rolloutmetadataBuilder) WithRolloutPolicyReferences(v []rolloutpolicyreference) *rolloutmetadataBuilder {
	b.rolloutpolicyreferences = v
	return b
}

func (b *rolloutmetadataBuilder) WithRolloutType(v string) *rolloutmetadataBuilder {
	b.rollouttype = v
	return b
}

func (b *rolloutmetadataBuilder) WithServiceModelPath(v string) *rolloutmetadataBuilder {
	b.servicemodelpath = v
	return b
}

func (o *rolloutmetadata) BuildSource() buildsource {
	return o.buildsource
}

func (o *rolloutmetadata) Clone() *rolloutmetadataBuilder {
	return NewrolloutmetadataBuilder(o)
}

func (o *rolloutmetadata) Configuration() *configuration {
	return o.configuration
}

func (o *rolloutmetadata) Name() string {
	return o.name
}

func (o *rolloutmetadata) Notification() *notification {
	return o.notification
}

func (o *rolloutmetadata) ParameterReplacementsPath() *string {
	return o.parameterreplacementspath
}

func (o *rolloutmetadata) RolloutPolicyReferences() []rolloutpolicyreference {
	return o.rolloutpolicyreferences
}

func (o *rolloutmetadata) RolloutType() string {
	return o.rollouttype
}

func (o *rolloutmetadata) ServiceModelPath() string {
	return o.servicemodelpath
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *rolloutmetadata) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["buildSource"]; raw != nil && !ok {
		return fmt.Errorf("field buildSource in rolloutmetadata: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in rolloutmetadata: required")
	}
	if _, ok := raw["rolloutType"]; raw != nil && !ok {
		return fmt.Errorf("field rolloutType in rolloutmetadata: required")
	}
	if _, ok := raw["serviceModelPath"]; raw != nil && !ok {
		return fmt.Errorf("field serviceModelPath in rolloutmetadata: required")
	}
	type Plain rolloutmetadata
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if matched, _ := regexp.MatchString(`(?i)(^Major$|^Minor$|^Hotfix$)`, string(plain.rollouttype)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "rollouttype", `(?i)(^Major$|^Minor$|^Hotfix$)`)
	}
	*j = rolloutmetadata(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *rolloutmetadata) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["buildSource"]; raw != nil && !ok {
		return fmt.Errorf("field buildSource in rolloutmetadata: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in rolloutmetadata: required")
	}
	if _, ok := raw["rolloutType"]; raw != nil && !ok {
		return fmt.Errorf("field rolloutType in rolloutmetadata: required")
	}
	if _, ok := raw["serviceModelPath"]; raw != nil && !ok {
		return fmt.Errorf("field serviceModelPath in rolloutmetadata: required")
	}
	type rolloutmetadataHelper struct {
		Buildsource               buildsource              `json:"buildSource"`
		Configuration             *configuration           `json:"configuration,omitempty"`
		Name                      string                   `json:"name"`
		Notification              *notification            `json:"notification,omitempty"`
		Parameterreplacementspath *string                  `json:"parameterReplacementsPath,omitempty"`
		Rolloutpolicyreferences   []rolloutpolicyreference `json:"rolloutPolicyReferences,omitempty"`
		Rollouttype               string                   `json:"rolloutType"`
		Servicemodelpath          string                   `json:"serviceModelPath"`
	}
	type Plain rolloutmetadata
	var helper rolloutmetadataHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.buildsource = helper.Buildsource
	plain.configuration = helper.Configuration
	plain.name = helper.Name
	plain.notification = helper.Notification
	plain.parameterreplacementspath = helper.Parameterreplacementspath
	plain.rolloutpolicyreferences = helper.Rolloutpolicyreferences
	plain.rollouttype = helper.Rollouttype
	plain.servicemodelpath = helper.Servicemodelpath
	if utf8.RuneCountInString(string(plain.name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if matched, _ := regexp.MatchString(`(?i)(^Major$|^Minor$|^Hotfix$)`, string(plain.rollouttype)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "rollouttype", `(?i)(^Major$|^Minor$|^Hotfix$)`)
	}
	*j = rolloutmetadata(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *rolloutmetadata) MarshalJSON() ([]byte, error) {
	type rolloutmetadataMarshalHelper struct {
		Buildsource               buildsource              `json:"buildSource"`
		Configuration             *configuration           `json:"configuration,omitempty"`
		Name                      string                   `json:"name"`
		Notification              *notification            `json:"notification,omitempty"`
		Parameterreplacementspath *string                  `json:"parameterReplacementsPath,omitempty"`
		Rolloutpolicyreferences   []rolloutpolicyreference `json:"rolloutPolicyReferences,omitempty"`
		Rollouttype               string                   `json:"rolloutType"`
		Servicemodelpath          string                   `json:"serviceModelPath"`
	}
	helper := rolloutmetadataMarshalHelper{
		Buildsource:               j.buildsource,
		Configuration:             j.configuration,
		Name:                      j.name,
		Notification:              j.notification,
		Parameterreplacementspath: j.parameterreplacementspath,
		Rolloutpolicyreferences:   j.rolloutpolicyreferences,
		Rollouttype:               j.rollouttype,
		Servicemodelpath:          j.servicemodelpath,
	}
	return json.Marshal(helper)
}

// Policy reference details.
type rolloutpolicyreference struct {
	// The name of the policy.
	name string `json:"name" yaml:"name" mapstructure:"name"`

	// The version of the policy to use. Specify '*' to use the latest registered
	// version of the policy.
	version string `json:"version" yaml:"version" mapstructure:"version"`
}

type rolloutpolicyreferenceBuilder struct {
	name string

	version string
}

func (b *rolloutpolicyreferenceBuilder) Build() *rolloutpolicyreference {
	return &rolloutpolicyreference{
		name:    b.name,
		version: b.version,
	}
}

func (b *rolloutpolicyreferenceBuilder) WithName(v string) *rolloutpolicyreferenceBuilder {
	b.name = v
	return b
}

func (b *rolloutpolicyreferenceBuilder) WithVersion(v string) *rolloutpolicyreferenceBuilder {
	b.version = v
	return b
}

func (o *rolloutpolicyreference) Clone() *rolloutpolicyreferenceBuilder {
	return NewrolloutpolicyreferenceBuilder(o)
}

func (o *rolloutpolicyreference) Name() string {
	return o.name
}

func (o *rolloutpolicyreference) Version() string {
	return o.version
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *rolloutpolicyreference) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in rolloutpolicyreference: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in rolloutpolicyreference: required")
	}
	type Plain rolloutpolicyreference
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = rolloutpolicyreference(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *rolloutpolicyreference) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in rolloutpolicyreference: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in rolloutpolicyreference: required")
	}
	type rolloutpolicyreferenceHelper struct {
		Name    string `json:"name"`
		Version string `json:"version"`
	}
	type Plain rolloutpolicyreference
	var helper rolloutpolicyreferenceHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	plain.version = helper.Version
	*j = rolloutpolicyreference(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *rolloutpolicyreference) MarshalJSON() ([]byte, error) {
	type rolloutpolicyreferenceMarshalHelper struct {
		Name    string `json:"name"`
		Version string `json:"version"`
	}
	helper := rolloutpolicyreferenceMarshalHelper{
		Name:    j.name,
		Version: j.version,
	}
	return json.Marshal(helper)
}

// Service scope configuration setting
type servicescope struct {
	// The path relative to the Service Group Root that points to the service scope
	// configuration specification.
	specpath *string `json:"specPath,omitempty,omitzero" yaml:"specPath,omitempty" mapstructure:"specPath,omitempty"`
}

type servicescopeBuilder struct {
	specpath *string
}

func (b *servicescopeBuilder) Build() *servicescope {
	return &servicescope{
		specpath: b.specpath,
	}
}

func (b *servicescopeBuilder) WithSpecPath(v *string) *servicescopeBuilder {
	b.specpath = v
	return b
}

func (o *servicescope) Clone() *servicescopeBuilder {
	return NewservicescopeBuilder(o)
}

func (o *servicescope) SpecPath() *string {
	return o.specpath
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *servicescope) UnmarshalJSON(value []byte) error {
	type servicescopeHelper struct {
		Specpath *string `json:"specPath,omitempty"`
	}
	type Plain servicescope
	var helper servicescopeHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.specpath = helper.Specpath
	*j = servicescope(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *servicescope) MarshalJSON() ([]byte, error) {
	type servicescopeMarshalHelper struct {
		Specpath *string `json:"specPath,omitempty"`
	}
	helper := servicescopeMarshalHelper{
		Specpath: j.specpath,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *servicescope) UnmarshalYAML(value *yaml.Node) error {
	type Plain servicescope
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = servicescope(plain)
	return nil
}
