// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "strings"

func NewStructWithConstraintsBuilder(o *StructWithConstraints) *StructWithConstraintsBuilder {
	if o == nil {
		return &StructWithConstraintsBuilder{}
	}
	return &StructWithConstraintsBuilder{
		prop: o.prop,
	}
}

type StructWithConstraints struct {
	// prop corresponds to the JSON schema field "prop".
	prop *float64 `json:"prop,omitempty,omitzero" yaml:"prop,omitempty" mapstructure:"prop,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type StructWithConstraintsBuilder struct {
	prop *float64
}

func (b *StructWithConstraintsBuilder) Build() *StructWithConstraints {
	return &StructWithConstraints{
		prop: b.prop,
	}
}

func (b *StructWithConstraintsBuilder) WithProp(v *float64) *StructWithConstraintsBuilder {
	b.prop = v
	return b
}

func (o *StructWithConstraints) Clone() *StructWithConstraintsBuilder {
	return NewStructWithConstraintsBuilder(o)
}

func (o *StructWithConstraints) Prop() *float64 {
	return o.prop
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StructWithConstraints) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type StructWithConstraintsHelper struct {
		Prop *float64 `json:"prop,omitempty,omitzero"`
	}
	type Plain StructWithConstraints
	var helper StructWithConstraintsHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.prop = helper.Prop
	if plain.prop != nil && 0 > *plain.prop {
		return fmt.Errorf("field %s: must be >= %v", "prop", 0)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	var additionalPropsRaw map[string]interface{}
	if err := mapstructure.Decode(raw, &additionalPropsRaw); err != nil {
		return err
	}
	plain.AdditionalProperties = func() interface{} {
		if additionalPropsRaw == nil {
			return nil
		}
		return additionalPropsRaw
	}()
	*j = StructWithConstraints(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *StructWithConstraints) MarshalJSON() ([]byte, error) {
	type StructWithConstraintsMarshalHelper struct {
		Prop *float64 `json:"prop,omitempty,omitzero"`
	}
	helper := StructWithConstraintsMarshalHelper{
		Prop: j.prop,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *StructWithConstraints) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type PlainRaw struct {
		Prop                 *float64
		AdditionalProperties interface{}
	}
	type Plain StructWithConstraints
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.prop = rawStruct.Prop
	plain.AdditionalProperties = rawStruct.AdditionalProperties
	plain = plain
	if plain.prop != nil && 0 > *plain.prop {
		return fmt.Errorf("field %s: must be >= %v", "prop", 0)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	var additionalPropsRaw map[string]interface{}
	if err := mapstructure.Decode(raw, &additionalPropsRaw); err != nil {
		return err
	}
	plain.AdditionalProperties = additionalPropsRaw
	*j = StructWithConstraints(plain)
	return nil
}
