// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "github.com/go-viper/mapstructure/v2"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "strings"

type GopkgYAMLv3AdditionalProperties struct {
	// bar corresponds to the JSON schema field "bar".
	bar *string `json:"bar,omitempty,omitzero" yaml:"bar,omitempty" mapstructure:"bar,omitempty"`

	// foo corresponds to the JSON schema field "foo".
	foo *string `json:"foo,omitempty,omitzero" yaml:"foo,omitempty" mapstructure:"foo,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type GopkgYAMLv3AdditionalPropertiesBuilder struct {
	bar *string

	foo *string
}

func (b *GopkgYAMLv3AdditionalPropertiesBuilder) Build() *GopkgYAMLv3AdditionalProperties {
	return &GopkgYAMLv3AdditionalProperties{
		bar: b.bar,
		foo: b.foo,
	}
}

func (b *GopkgYAMLv3AdditionalPropertiesBuilder) WithBar(v *string) *GopkgYAMLv3AdditionalPropertiesBuilder {
	b.bar = v
	return b
}

func (b *GopkgYAMLv3AdditionalPropertiesBuilder) WithFoo(v *string) *GopkgYAMLv3AdditionalPropertiesBuilder {
	b.foo = v
	return b
}

func (o *GopkgYAMLv3AdditionalProperties) Bar() *string {
	return o.bar
}

func (o *GopkgYAMLv3AdditionalProperties) Clone() *GopkgYAMLv3AdditionalPropertiesBuilder {
	return NewGopkgYAMLv3AdditionalPropertiesBuilder(o)
}

func (o *GopkgYAMLv3AdditionalProperties) Foo() *string {
	return o.foo
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GopkgYAMLv3AdditionalProperties) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type GopkgYAMLv3AdditionalPropertiesHelper struct {
		Bar *string `json:"bar,omitempty,omitzero"`
		Foo *string `json:"foo,omitempty,omitzero"`
	}
	type Plain GopkgYAMLv3AdditionalProperties
	var helper GopkgYAMLv3AdditionalPropertiesHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.bar = helper.Bar
	plain.foo = helper.Foo
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	var additionalPropsRaw map[string]interface{}
	if err := mapstructure.Decode(raw, &additionalPropsRaw); err != nil {
		return err
	}
	plain.AdditionalProperties = func() interface{} {
		if additionalPropsRaw == nil {
			return nil
		}
		return additionalPropsRaw
	}()
	*j = GopkgYAMLv3AdditionalProperties(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *GopkgYAMLv3AdditionalProperties) MarshalJSON() ([]byte, error) {
	type GopkgYAMLv3AdditionalPropertiesMarshalHelper struct {
		Bar *string `json:"bar,omitempty,omitzero"`
		Foo *string `json:"foo,omitempty,omitzero"`
	}
	helper := GopkgYAMLv3AdditionalPropertiesMarshalHelper{
		Bar: j.bar,
		Foo: j.foo,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *GopkgYAMLv3AdditionalProperties) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type PlainRaw struct {
		Bar                  *string
		Foo                  *string
		AdditionalProperties interface{}
	}
	type Plain GopkgYAMLv3AdditionalProperties
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.bar = rawStruct.Bar
	plain.foo = rawStruct.Foo
	plain.AdditionalProperties = rawStruct.AdditionalProperties
	plain = plain
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	var additionalPropsRaw map[string]interface{}
	if err := mapstructure.Decode(raw, &additionalPropsRaw); err != nil {
		return err
	}
	plain.AdditionalProperties = additionalPropsRaw
	*j = GopkgYAMLv3AdditionalProperties(plain)
	return nil
}

func NewGopkgYAMLv3AdditionalPropertiesBuilder(o *GopkgYAMLv3AdditionalProperties) *GopkgYAMLv3AdditionalPropertiesBuilder {
	if o == nil {
		return &GopkgYAMLv3AdditionalPropertiesBuilder{}
	}
	return &GopkgYAMLv3AdditionalPropertiesBuilder{
		bar: o.bar,
		foo: o.foo,
	}
}
