// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"

type RequiredFieldsJson struct {
	// myboolean corresponds to the JSON schema field "myBoolean".
	myboolean bool `json:"myBoolean" yaml:"myBoolean" mapstructure:"myBoolean"`

	// mybooleanarray corresponds to the JSON schema field "myBooleanArray".
	mybooleanarray []bool `json:"myBooleanArray" yaml:"myBooleanArray" mapstructure:"myBooleanArray"`

	// myinteger corresponds to the JSON schema field "myInteger".
	myinteger *int `json:"myInteger,omitempty,omitzero" yaml:"myInteger,omitempty" mapstructure:"myInteger,omitempty"`

	// myintegerarray corresponds to the JSON schema field "myIntegerArray".
	myintegerarray []int `json:"myIntegerArray,omitempty,omitzero" yaml:"myIntegerArray,omitempty" mapstructure:"myIntegerArray,omitempty"`

	// mynull corresponds to the JSON schema field "myNull".
	mynull interface{} `json:"myNull" yaml:"myNull" mapstructure:"myNull"`

	// mynullarray corresponds to the JSON schema field "myNullArray".
	mynullarray []interface{} `json:"myNullArray" yaml:"myNullArray" mapstructure:"myNullArray"`

	// mynumber corresponds to the JSON schema field "myNumber".
	mynumber float64 `json:"myNumber" yaml:"myNumber" mapstructure:"myNumber"`

	// mynumberarray corresponds to the JSON schema field "myNumberArray".
	mynumberarray []float64 `json:"myNumberArray" yaml:"myNumberArray" mapstructure:"myNumberArray"`

	// myobject corresponds to the JSON schema field "myObject".
	myobject RequiredFieldsJsonmyobject `json:"myObject" yaml:"myObject" mapstructure:"myObject"`

	// myobjectarray corresponds to the JSON schema field "myObjectArray".
	myobjectarray []RequiredFieldsJsonmyobjectarrayElem `json:"myObjectArray" yaml:"myObjectArray" mapstructure:"myObjectArray"`

	// mystring corresponds to the JSON schema field "myString".
	mystring string `json:"myString" yaml:"myString" mapstructure:"myString"`

	// mystringarray corresponds to the JSON schema field "myStringArray".
	mystringarray []string `json:"myStringArray" yaml:"myStringArray" mapstructure:"myStringArray"`
}

func (o *RequiredFieldsJson) MyBoolean() bool {
	return o.myboolean
}

func (o *RequiredFieldsJson) MyBooleanArray() []bool {
	return o.mybooleanarray
}

func (o *RequiredFieldsJson) MyInteger() *int {
	return o.myinteger
}

func (o *RequiredFieldsJson) MyIntegerArray() []int {
	return o.myintegerarray
}

func (o *RequiredFieldsJson) MyNull() interface{} {
	return o.mynull
}

func (o *RequiredFieldsJson) MyNullArray() []interface{} {
	return o.mynullarray
}

func (o *RequiredFieldsJson) MyNumber() float64 {
	return o.mynumber
}

func (o *RequiredFieldsJson) MyNumberArray() []float64 {
	return o.mynumberarray
}

func (o *RequiredFieldsJson) MyObject() RequiredFieldsJsonmyobject {
	return o.myobject
}

func (o *RequiredFieldsJson) MyObjectArray() []RequiredFieldsJsonmyobjectarrayElem {
	return o.myobjectarray
}

func (o *RequiredFieldsJson) MyString() string {
	return o.mystring
}

func (o *RequiredFieldsJson) MyStringArray() []string {
	return o.mystringarray
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RequiredFieldsJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myBoolean"]; raw != nil && !ok {
		return fmt.Errorf("field myBoolean in RequiredFieldsJson: required")
	}
	if _, ok := raw["myBooleanArray"]; raw != nil && !ok {
		return fmt.Errorf("field myBooleanArray in RequiredFieldsJson: required")
	}
	if _, ok := raw["myNull"]; raw != nil && !ok {
		return fmt.Errorf("field myNull in RequiredFieldsJson: required")
	}
	if _, ok := raw["myNullArray"]; raw != nil && !ok {
		return fmt.Errorf("field myNullArray in RequiredFieldsJson: required")
	}
	if _, ok := raw["myNumber"]; raw != nil && !ok {
		return fmt.Errorf("field myNumber in RequiredFieldsJson: required")
	}
	if _, ok := raw["myNumberArray"]; raw != nil && !ok {
		return fmt.Errorf("field myNumberArray in RequiredFieldsJson: required")
	}
	if _, ok := raw["myObject"]; raw != nil && !ok {
		return fmt.Errorf("field myObject in RequiredFieldsJson: required")
	}
	if _, ok := raw["myObjectArray"]; raw != nil && !ok {
		return fmt.Errorf("field myObjectArray in RequiredFieldsJson: required")
	}
	if _, ok := raw["myString"]; raw != nil && !ok {
		return fmt.Errorf("field myString in RequiredFieldsJson: required")
	}
	if _, ok := raw["myStringArray"]; raw != nil && !ok {
		return fmt.Errorf("field myStringArray in RequiredFieldsJson: required")
	}
	type RequiredFieldsJsonHelper struct {
		Myboolean      bool                                  `json:"myBoolean"`
		Mybooleanarray []bool                                `json:"myBooleanArray"`
		Myinteger      *int                                  `json:"myInteger",omitempty`
		Myintegerarray []int                                 `json:"myIntegerArray",omitempty`
		Mynull         interface{}                           `json:"myNull"`
		Mynullarray    []interface{}                         `json:"myNullArray"`
		Mynumber       float64                               `json:"myNumber"`
		Mynumberarray  []float64                             `json:"myNumberArray"`
		Myobject       RequiredFieldsJsonmyobject            `json:"myObject"`
		Myobjectarray  []RequiredFieldsJsonmyobjectarrayElem `json:"myObjectArray"`
		Mystring       string                                `json:"myString"`
		Mystringarray  []string                              `json:"myStringArray"`
	}
	type Plain RequiredFieldsJson
	var helper RequiredFieldsJsonHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myboolean = helper.Myboolean
	plain.mybooleanarray = helper.Mybooleanarray
	plain.myinteger = helper.Myinteger
	plain.myintegerarray = helper.Myintegerarray
	plain.mynull = helper.Mynull
	plain.mynullarray = helper.Mynullarray
	plain.mynumber = helper.Mynumber
	plain.mynumberarray = helper.Mynumberarray
	plain.myobject = helper.Myobject
	plain.myobjectarray = helper.Myobjectarray
	plain.mystring = helper.Mystring
	plain.mystringarray = helper.Mystringarray
	if plain.mynull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := range plain.mynullarray {
		if plain.mynullarray[i0] != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = RequiredFieldsJson(plain)
	return nil
}

type RequiredFieldsJsonmyobject struct {
	// mynestedobjectstring corresponds to the JSON schema field
	// "myNestedObjectString".
	mynestedobjectstring string `json:"myNestedObjectString" yaml:"myNestedObjectString" mapstructure:"myNestedObjectString"`
}

func (o *RequiredFieldsJsonmyobject) MyNestedObjectString() string {
	return o.mynestedobjectstring
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RequiredFieldsJsonmyobject) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myNestedObjectString"]; raw != nil && !ok {
		return fmt.Errorf("field myNestedObjectString in RequiredFieldsJsonmyobject: required")
	}
	type RequiredFieldsJsonmyobjectHelper struct {
		Mynestedobjectstring string `json:"myNestedObjectString"`
	}
	type Plain RequiredFieldsJsonmyobject
	var helper RequiredFieldsJsonmyobjectHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mynestedobjectstring = helper.Mynestedobjectstring
	*j = RequiredFieldsJsonmyobject(plain)
	return nil
}

type RequiredFieldsJsonmyobjectarrayElem struct {
	// mynestedobjectstring corresponds to the JSON schema field
	// "myNestedObjectString".
	mynestedobjectstring string `json:"myNestedObjectString" yaml:"myNestedObjectString" mapstructure:"myNestedObjectString"`
}

func (o *RequiredFieldsJsonmyobjectarrayElem) MyNestedObjectString() string {
	return o.mynestedobjectstring
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RequiredFieldsJsonmyobjectarrayElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myNestedObjectString"]; raw != nil && !ok {
		return fmt.Errorf("field myNestedObjectString in RequiredFieldsJsonmyobjectarrayElem: required")
	}
	type RequiredFieldsJsonmyobjectarrayElemHelper struct {
		Mynestedobjectstring string `json:"myNestedObjectString"`
	}
	type Plain RequiredFieldsJsonmyobjectarrayElem
	var helper RequiredFieldsJsonmyobjectarrayElemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mynestedobjectstring = helper.Mynestedobjectstring
	*j = RequiredFieldsJsonmyobjectarrayElem(plain)
	return nil
}
