// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// object with anyOf properties as root
type AnyOf3 struct {
	// bar corresponds to the JSON schema field "bar".
	bar *float64 `json:"bar,omitempty,omitzero" yaml:"bar,omitempty" mapstructure:"bar,omitempty"`

	// configurations corresponds to the JSON schema field "configurations".
	configurations []interface{} `json:"configurations,omitempty,omitzero" yaml:"configurations,omitempty" mapstructure:"configurations,omitempty"`

	// foo corresponds to the JSON schema field "foo".
	foo *string `json:"foo,omitempty,omitzero" yaml:"foo,omitempty" mapstructure:"foo,omitempty"`
}

type AnyOf3Builder struct {
	bar *float64

	configurations []interface{}

	foo *string
}

func (b *AnyOf3Builder) Build() *AnyOf3 {
	return &AnyOf3{
		bar:            b.bar,
		configurations: b.configurations,
		foo:            b.foo,
	}
}

func (b *AnyOf3Builder) WithBar(v *float64) *AnyOf3Builder {
	b.bar = v
	return b
}

func (b *AnyOf3Builder) WithConfigurations(v []interface{}) *AnyOf3Builder {
	b.configurations = v
	return b
}

func (b *AnyOf3Builder) WithFoo(v *string) *AnyOf3Builder {
	b.foo = v
	return b
}

type AnyOf3_0 struct {
	// foo corresponds to the JSON schema field "foo".
	foo string `json:"foo" yaml:"foo" mapstructure:"foo"`
}

type AnyOf3_0Builder struct {
	foo string
}

func (b *AnyOf3_0Builder) Build() *AnyOf3_0 {
	return &AnyOf3_0{
		foo: b.foo,
	}
}

func (b *AnyOf3_0Builder) WithFoo(v string) *AnyOf3_0Builder {
	b.foo = v
	return b
}

func (o *AnyOf3_0) Clone() *AnyOf3_0Builder {
	return NewAnyOf3_0Builder(o)
}

func (o *AnyOf3_0) Foo() string {
	return o.foo
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf3_0) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AnyOf3_0: required")
	}
	type Plain AnyOf3_0
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf3_0(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf3_0) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AnyOf3_0: required")
	}
	type AnyOf3_0Helper struct {
		Foo string `json:"foo"`
	}
	type Plain AnyOf3_0
	var helper AnyOf3_0Helper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.foo = helper.Foo
	*j = AnyOf3_0(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AnyOf3_0) MarshalJSON() ([]byte, error) {
	type AnyOf3_0MarshalHelper struct {
		Foo string `json:"foo"`
	}
	helper := AnyOf3_0MarshalHelper{
		Foo: j.foo,
	}
	return json.Marshal(helper)
}

type AnyOf3_1 struct {
	// bar corresponds to the JSON schema field "bar".
	bar float64 `json:"bar" yaml:"bar" mapstructure:"bar"`
}

type AnyOf3_1Builder struct {
	bar float64
}

func (b *AnyOf3_1Builder) Build() *AnyOf3_1 {
	return &AnyOf3_1{
		bar: b.bar,
	}
}

func (b *AnyOf3_1Builder) WithBar(v float64) *AnyOf3_1Builder {
	b.bar = v
	return b
}

func (o *AnyOf3_1) Bar() float64 {
	return o.bar
}

func (o *AnyOf3_1) Clone() *AnyOf3_1Builder {
	return NewAnyOf3_1Builder(o)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf3_1) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AnyOf3_1: required")
	}
	type Plain AnyOf3_1
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf3_1(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf3_1) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AnyOf3_1: required")
	}
	type AnyOf3_1Helper struct {
		Bar float64 `json:"bar"`
	}
	type Plain AnyOf3_1
	var helper AnyOf3_1Helper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.bar = helper.Bar
	*j = AnyOf3_1(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AnyOf3_1) MarshalJSON() ([]byte, error) {
	type AnyOf3_1MarshalHelper struct {
		Bar float64 `json:"bar"`
	}
	helper := AnyOf3_1MarshalHelper{
		Bar: j.bar,
	}
	return json.Marshal(helper)
}

type AnyOf3_2 struct {
	// configurations corresponds to the JSON schema field "configurations".
	configurations []interface{} `json:"configurations,omitempty,omitzero" yaml:"configurations,omitempty" mapstructure:"configurations,omitempty"`
}

type AnyOf3_2Builder struct {
	configurations []interface{}
}

func (b *AnyOf3_2Builder) Build() *AnyOf3_2 {
	return &AnyOf3_2{
		configurations: b.configurations,
	}
}

func (b *AnyOf3_2Builder) WithConfigurations(v []interface{}) *AnyOf3_2Builder {
	b.configurations = v
	return b
}

func (o *AnyOf3_2) Clone() *AnyOf3_2Builder {
	return NewAnyOf3_2Builder(o)
}

func (o *AnyOf3_2) Configurations() []interface{} {
	return o.configurations
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf3_2) UnmarshalJSON(value []byte) error {
	type AnyOf3_2Helper struct {
		Configurations []interface{} `json:"configurations,omitempty"`
	}
	type Plain AnyOf3_2
	var helper AnyOf3_2Helper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.configurations = helper.Configurations
	*j = AnyOf3_2(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AnyOf3_2) MarshalJSON() ([]byte, error) {
	type AnyOf3_2MarshalHelper struct {
		Configurations []interface{} `json:"configurations,omitempty"`
	}
	helper := AnyOf3_2MarshalHelper{
		Configurations: j.configurations,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf3_2) UnmarshalYAML(value *yaml.Node) error {
	type Plain AnyOf3_2
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf3_2(plain)
	return nil
}

func (o *AnyOf3) Bar() *float64 {
	return o.bar
}

func (o *AnyOf3) Clone() *AnyOf3Builder {
	return NewAnyOf3Builder(o)
}

func (o *AnyOf3) Configurations() []interface{} {
	return o.configurations
}

func (o *AnyOf3) Foo() *string {
	return o.foo
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf3) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf3_0 AnyOf3_0
	var anyOf3_1 AnyOf3_1
	var anyOf3_2 AnyOf3_2
	var errs []error
	if err := anyOf3_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf3_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf3_2.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 3 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type AnyOf3Helper struct {
		Bar            *float64      `json:"bar,omitempty"`
		Configurations []interface{} `json:"configurations,omitempty"`
		Foo            *string       `json:"foo,omitempty"`
	}
	type Plain AnyOf3
	var helper AnyOf3Helper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.bar = helper.Bar
	plain.configurations = helper.Configurations
	plain.foo = helper.Foo
	*j = AnyOf3(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AnyOf3) MarshalJSON() ([]byte, error) {
	type AnyOf3MarshalHelper struct {
		Bar            *float64      `json:"bar,omitempty"`
		Configurations []interface{} `json:"configurations,omitempty"`
		Foo            *string       `json:"foo,omitempty"`
	}
	helper := AnyOf3MarshalHelper{
		Bar:            j.bar,
		Configurations: j.configurations,
		Foo:            j.foo,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf3) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var anyOf3_0 AnyOf3_0
	var anyOf3_1 AnyOf3_1
	var anyOf3_2 AnyOf3_2
	var errs []error
	if err := anyOf3_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf3_1.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf3_2.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 3 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOf3
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf3(plain)
	return nil
}

func NewAnyOf3Builder(o *AnyOf3) *AnyOf3Builder {
	if o == nil {
		return &AnyOf3Builder{}
	}
	return &AnyOf3Builder{
		bar:            o.bar,
		configurations: o.configurations,
		foo:            o.foo,
	}
}

func NewAnyOf3_0Builder(o *AnyOf3_0) *AnyOf3_0Builder {
	if o == nil {
		return &AnyOf3_0Builder{}
	}
	return &AnyOf3_0Builder{
		foo: o.foo,
	}
}

func NewAnyOf3_1Builder(o *AnyOf3_1) *AnyOf3_1Builder {
	if o == nil {
		return &AnyOf3_1Builder{}
	}
	return &AnyOf3_1Builder{
		bar: o.bar,
	}
}

func NewAnyOf3_2Builder(o *AnyOf3_2) *AnyOf3_2Builder {
	if o == nil {
		return &AnyOf3_2Builder{}
	}
	return &AnyOf3_2Builder{
		configurations: o.configurations,
	}
}
