// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type AnyOf7 struct {
	// bar corresponds to the JSON schema field "bar".
	bar []*AnyOf7barElem `json:"bar" yaml:"bar" mapstructure:"bar"`

	// baz corresponds to the JSON schema field "baz".
	baz []*AnyOf7bazElem `json:"baz,omitempty,omitzero" yaml:"baz,omitempty" mapstructure:"baz,omitempty"`

	// foo corresponds to the JSON schema field "foo".
	foo *AnyOf7foo `json:"foo" yaml:"foo" mapstructure:"foo"`
}

type AnyOf7Builder struct {
	bar []*AnyOf7barElem

	baz []*AnyOf7bazElem

	foo *AnyOf7foo
}

func (b *AnyOf7Builder) Build() *AnyOf7 {
	return &AnyOf7{
		bar: b.bar,
		baz: b.baz,
		foo: b.foo,
	}
}

func (b *AnyOf7Builder) WithBar(v []*AnyOf7barElem) *AnyOf7Builder {
	b.bar = v
	return b
}

func (b *AnyOf7Builder) WithBaz(v []*AnyOf7bazElem) *AnyOf7Builder {
	b.baz = v
	return b
}

func (b *AnyOf7Builder) WithFoo(v *AnyOf7foo) *AnyOf7Builder {
	b.foo = v
	return b
}

func (o *AnyOf7) Bar() []*AnyOf7barElem {
	return o.bar
}

func (o *AnyOf7) Baz() []*AnyOf7bazElem {
	return o.baz
}

func (o *AnyOf7) Clone() *AnyOf7Builder {
	return NewAnyOf7Builder(o)
}

func (o *AnyOf7) Foo() *AnyOf7foo {
	return o.foo
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AnyOf7: required")
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AnyOf7: required")
	}
	type AnyOf7Helper struct {
		Bar []*AnyOf7barElem `json:"bar"`
		Baz []*AnyOf7bazElem `json:"baz,omitempty"`
		Foo *AnyOf7foo       `json:"foo"`
	}
	type Plain AnyOf7
	var helper AnyOf7Helper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.bar = helper.Bar
	plain.baz = helper.Baz
	plain.foo = helper.Foo
	*j = AnyOf7(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AnyOf7) MarshalJSON() ([]byte, error) {
	type AnyOf7MarshalHelper struct {
		Bar []*AnyOf7barElem `json:"bar"`
		Baz []*AnyOf7bazElem `json:"baz,omitempty"`
		Foo *AnyOf7foo       `json:"foo"`
	}
	helper := AnyOf7MarshalHelper{
		Bar: j.bar,
		Baz: j.baz,
		Foo: j.foo,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf7) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AnyOf7: required")
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AnyOf7: required")
	}
	type Plain AnyOf7
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf7(plain)
	return nil
}

type AnyOf7barElem struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type AnyOf7barElemBuilder struct {
	name *string
}

func (b *AnyOf7barElemBuilder) Build() *AnyOf7barElem {
	return &AnyOf7barElem{
		name: b.name,
	}
}

func (b *AnyOf7barElemBuilder) WithName(v *string) *AnyOf7barElemBuilder {
	b.name = v
	return b
}

func (o *AnyOf7barElem) Clone() *AnyOf7barElemBuilder {
	return NewAnyOf7barElemBuilder(o)
}

func (o *AnyOf7barElem) Name() *string {
	return o.name
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf7barElem) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var anyOf7barElem_0 AnyOf7barElem_0
	var errs []error
	if err := anyOf7barElem_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOf7barElem
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf7barElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7barElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf7barElem_0 AnyOf7barElem_0
	var errs []error
	if err := anyOf7barElem_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type AnyOf7barElemHelper struct {
		Name *string `json:"name,omitempty"`
	}
	type Plain AnyOf7barElem
	var helper AnyOf7barElemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = AnyOf7barElem(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AnyOf7barElem) MarshalJSON() ([]byte, error) {
	type AnyOf7barElemMarshalHelper struct {
		Name *string `json:"name,omitempty"`
	}
	helper := AnyOf7barElemMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}

type AnyOf7bazElem struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type AnyOf7bazElemBuilder struct {
	name *string
}

func (b *AnyOf7bazElemBuilder) Build() *AnyOf7bazElem {
	return &AnyOf7bazElem{
		name: b.name,
	}
}

func (b *AnyOf7bazElemBuilder) WithName(v *string) *AnyOf7bazElemBuilder {
	b.name = v
	return b
}

func (o *AnyOf7bazElem) Clone() *AnyOf7bazElemBuilder {
	return NewAnyOf7bazElemBuilder(o)
}

func (o *AnyOf7bazElem) Name() *string {
	return o.name
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7bazElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf7bazElem_0 AnyOf7bazElem_0
	var errs []error
	if err := anyOf7bazElem_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type AnyOf7bazElemHelper struct {
		Name *string `json:"name,omitempty"`
	}
	type Plain AnyOf7bazElem
	var helper AnyOf7bazElemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = AnyOf7bazElem(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AnyOf7bazElem) MarshalJSON() ([]byte, error) {
	type AnyOf7bazElemMarshalHelper struct {
		Name *string `json:"name,omitempty"`
	}
	helper := AnyOf7bazElemMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf7bazElem) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var anyOf7bazElem_0 AnyOf7bazElem_0
	var errs []error
	if err := anyOf7bazElem_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOf7bazElem
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf7bazElem(plain)
	return nil
}

type AnyOf7foo struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type AnyOf7fooBuilder struct {
	name *string
}

func (b *AnyOf7fooBuilder) Build() *AnyOf7foo {
	return &AnyOf7foo{
		name: b.name,
	}
}

func (b *AnyOf7fooBuilder) WithName(v *string) *AnyOf7fooBuilder {
	b.name = v
	return b
}

func (o *AnyOf7foo) Clone() *AnyOf7fooBuilder {
	return NewAnyOf7fooBuilder(o)
}

func (o *AnyOf7foo) Name() *string {
	return o.name
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7foo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf7foo_0 AnyOf7foo_0
	var errs []error
	if err := anyOf7foo_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type AnyOf7fooHelper struct {
		Name *string `json:"name,omitempty"`
	}
	type Plain AnyOf7foo
	var helper AnyOf7fooHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = AnyOf7foo(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AnyOf7foo) MarshalJSON() ([]byte, error) {
	type AnyOf7fooMarshalHelper struct {
		Name *string `json:"name,omitempty"`
	}
	helper := AnyOf7fooMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf7foo) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var anyOf7foo_0 AnyOf7foo_0
	var errs []error
	if err := anyOf7foo_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOf7foo
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf7foo(plain)
	return nil
}

type Item struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type ItemBuilder struct {
	name *string
}

func (b *ItemBuilder) Build() *Item {
	return &Item{
		name: b.name,
	}
}

func (b *ItemBuilder) WithName(v *string) *ItemBuilder {
	b.name = v
	return b
}

func (o *Item) Clone() *ItemBuilder {
	return NewItemBuilder(o)
}

type AnyOf7bazElem_0 = Item

type AnyOf7barElem_0 = Item

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Item) UnmarshalYAML(value *yaml.Node) error {
	type Plain Item
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Item(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Item) UnmarshalJSON(value []byte) error {
	type ItemHelper struct {
		Name *string `json:"name,omitempty"`
	}
	type Plain Item
	var helper ItemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = Item(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Item) MarshalJSON() ([]byte, error) {
	type ItemMarshalHelper struct {
		Name *string `json:"name,omitempty"`
	}
	helper := ItemMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}

func NewAnyOf7Builder(o *AnyOf7) *AnyOf7Builder {
	if o == nil {
		return &AnyOf7Builder{}
	}
	return &AnyOf7Builder{
		bar: o.bar,
		baz: o.baz,
		foo: o.foo,
	}
}

func NewAnyOf7barElemBuilder(o *AnyOf7barElem) *AnyOf7barElemBuilder {
	if o == nil {
		return &AnyOf7barElemBuilder{}
	}
	return &AnyOf7barElemBuilder{
		name: o.name,
	}
}

func NewAnyOf7bazElemBuilder(o *AnyOf7bazElem) *AnyOf7bazElemBuilder {
	if o == nil {
		return &AnyOf7bazElemBuilder{}
	}
	return &AnyOf7bazElemBuilder{
		name: o.name,
	}
}

func NewAnyOf7fooBuilder(o *AnyOf7foo) *AnyOf7fooBuilder {
	if o == nil {
		return &AnyOf7fooBuilder{}
	}
	return &AnyOf7fooBuilder{
		name: o.name,
	}
}

func NewItemBuilder(o *Item) *ItemBuilder {
	if o == nil {
		return &ItemBuilder{}
	}
	return &ItemBuilder{
		name: o.name,
	}
}

type AnyOf7foo_0 = Item

func (o *Item) Name() *string {
	return o.name
}
