// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"

type AnyOf7Json struct {
	// bar corresponds to the JSON schema field "bar".
	bar []*AnyOf7JsonbarElem `json:"bar" yaml:"bar" mapstructure:"bar"`

	// baz corresponds to the JSON schema field "baz".
	baz []*AnyOf7JsonbazElem `json:"baz,omitempty,omitzero" yaml:"baz,omitempty" mapstructure:"baz,omitempty"`

	// foo corresponds to the JSON schema field "foo".
	foo *AnyOf7Jsonfoo `json:"foo" yaml:"foo" mapstructure:"foo"`
}

func (o *AnyOf7Json) Bar() []*AnyOf7JsonbarElem {
	return o.bar
}

func (o *AnyOf7Json) Baz() []*AnyOf7JsonbazElem {
	return o.baz
}

func (o *AnyOf7Json) Foo() *AnyOf7Jsonfoo {
	return o.foo
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AnyOf7Json: required")
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AnyOf7Json: required")
	}
	type AnyOf7JsonHelper struct {
		Bar []*AnyOf7JsonbarElem `json:"bar"`
		Baz []*AnyOf7JsonbazElem `json:"baz",omitempty`
		Foo *AnyOf7Jsonfoo       `json:"foo"`
	}
	type Plain AnyOf7Json
	var helper AnyOf7JsonHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.bar = helper.Bar
	plain.baz = helper.Baz
	plain.foo = helper.Foo
	*j = AnyOf7Json(plain)
	return nil
}

type AnyOf7JsonbarElem struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

func (o *AnyOf7JsonbarElem) Name() *string {
	return o.name
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7JsonbarElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf7JsonbarElem_0 AnyOf7JsonbarElem_0
	var errs []error
	if err := anyOf7JsonbarElem_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type AnyOf7JsonbarElemHelper struct {
		Name *string `json:"name",omitempty`
	}
	type Plain AnyOf7JsonbarElem
	var helper AnyOf7JsonbarElemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = AnyOf7JsonbarElem(plain)
	return nil
}

type AnyOf7JsonbazElem struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

func (o *AnyOf7JsonbazElem) Name() *string {
	return o.name
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7JsonbazElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf7JsonbazElem_0 AnyOf7JsonbazElem_0
	var errs []error
	if err := anyOf7JsonbazElem_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type AnyOf7JsonbazElemHelper struct {
		Name *string `json:"name",omitempty`
	}
	type Plain AnyOf7JsonbazElem
	var helper AnyOf7JsonbazElemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = AnyOf7JsonbazElem(plain)
	return nil
}

type AnyOf7Jsonfoo struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

func (o *AnyOf7Jsonfoo) Name() *string {
	return o.name
}

type AnyOf7JsonbazElem_0 = Item

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7Jsonfoo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf7Jsonfoo_0 AnyOf7Jsonfoo_0
	var errs []error
	if err := anyOf7Jsonfoo_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type AnyOf7JsonfooHelper struct {
		Name *string `json:"name",omitempty`
	}
	type Plain AnyOf7Jsonfoo
	var helper AnyOf7JsonfooHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = AnyOf7Jsonfoo(plain)
	return nil
}

type AnyOf7Jsonfoo_0 = Item

type Item struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type AnyOf7JsonbarElem_0 = Item

func (o *Item) Name() *string {
	return o.name
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Item) UnmarshalJSON(value []byte) error {
	type ItemHelper struct {
		Name *string `json:"name",omitempty`
	}
	type Plain Item
	var helper ItemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	*j = Item(plain)
	return nil
}
