// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

type BoolThing *bool

type FloatThing *float64

type IntegerThing *int

func NewNullableTypeBuilder(o *NullableType) *NullableTypeBuilder {
	if o == nil {
		return &NullableTypeBuilder{}
	}
	return &NullableTypeBuilder{
		myinlinestringvalue: o.myinlinestringvalue,
		mystringvalue:       o.mystringvalue,
	}
}

type NullableType struct {
	// myinlinestringvalue corresponds to the JSON schema field "MyInlineStringValue".
	myinlinestringvalue NullableTypemyinlinestringvalue `json:"MyInlineStringValue,omitempty,omitzero" yaml:"MyInlineStringValue,omitempty" mapstructure:"MyInlineStringValue,omitempty"`

	// mystringvalue corresponds to the JSON schema field "MyStringValue".
	mystringvalue StringThing `json:"MyStringValue,omitempty,omitzero" yaml:"MyStringValue,omitempty" mapstructure:"MyStringValue,omitempty"`
}

type NullableTypeBuilder struct {
	myinlinestringvalue NullableTypemyinlinestringvalue

	mystringvalue StringThing
}

func (b *NullableTypeBuilder) Build() *NullableType {
	return &NullableType{
		myinlinestringvalue: b.myinlinestringvalue,
		mystringvalue:       b.mystringvalue,
	}
}

func (b *NullableTypeBuilder) WithMyInlineStringValue(v NullableTypemyinlinestringvalue) *NullableTypeBuilder {
	b.myinlinestringvalue = v
	return b
}

func (b *NullableTypeBuilder) WithMyStringValue(v StringThing) *NullableTypeBuilder {
	b.mystringvalue = v
	return b
}

func (o *NullableType) MyInlineStringValue() NullableTypemyinlinestringvalue {
	return o.myinlinestringvalue
}

func (o *NullableType) MyStringValue() StringThing {
	return o.mystringvalue
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NullableType) UnmarshalJSON(value []byte) error {
	type NullableTypeHelper struct {
		Myinlinestringvalue NullableTypemyinlinestringvalue `json:"MyInlineStringValue",omitempty`
		Mystringvalue       StringThing                     `json:"MyStringValue",omitempty`
	}
	type Plain NullableType
	var helper NullableTypeHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myinlinestringvalue = helper.Myinlinestringvalue
	plain.mystringvalue = helper.Mystringvalue
	*j = NullableType(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *NullableType) MarshalJSON() ([]byte, error) {
	type NullableTypeMarshalHelper struct {
		Myinlinestringvalue NullableTypemyinlinestringvalue `json:"MyInlineStringValue",omitempty`
		Mystringvalue       StringThing                     `json:"MyStringValue",omitempty`
	}
	helper := NullableTypeMarshalHelper{
		Myinlinestringvalue: j.myinlinestringvalue,
		Mystringvalue:       j.mystringvalue,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NullableType) UnmarshalYAML(value *yaml.Node) error {
	type Plain NullableType
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = NullableType(plain)
	return nil
}

type NullableTypemyinlinestringvalue *string

type StringThing *string
