// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import other "github.com/kainwinterheart/go-jsonschema/tests/helpers/other"
import yaml "gopkg.in/yaml.v3"

type Schema struct {
	// definotherschema corresponds to the JSON schema field "defInOtherSchema".
	definotherschema *other.Thing `json:"defInOtherSchema,omitempty,omitzero" yaml:"defInOtherSchema,omitempty" mapstructure:"defInOtherSchema,omitempty"`

	// definsameschema corresponds to the JSON schema field "defInSameSchema".
	definsameschema *Thing `json:"defInSameSchema,omitempty,omitzero" yaml:"defInSameSchema,omitempty" mapstructure:"defInSameSchema,omitempty"`
}

func (o *Schema) DefInOtherSchema() *other.Thing {
	return o.definotherschema
}

func (o *Schema) DefInSameSchema() *Thing {
	return o.definsameschema
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Schema) UnmarshalJSON(value []byte) error {
	type SchemaHelper struct {
		Definotherschema *other.Thing `json:"defInOtherSchema",omitempty`
		Definsameschema  *Thing       `json:"defInSameSchema",omitempty`
	}
	type Plain Schema
	var helper SchemaHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.definotherschema = helper.Definotherschema
	plain.definsameschema = helper.Definsameschema
	*j = Schema(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Schema) MarshalJSON() ([]byte, error) {
	type SchemaMarshalHelper struct {
		Definotherschema *other.Thing `json:"defInOtherSchema",omitempty`
		Definsameschema  *Thing       `json:"defInSameSchema",omitempty`
	}
	helper := SchemaMarshalHelper{
		Definotherschema: j.definotherschema,
		Definsameschema:  j.definsameschema,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Schema) UnmarshalYAML(value *yaml.Node) error {
	type Plain Schema
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Schema(plain)
	return nil
}

type Thing struct {
	// s corresponds to the JSON schema field "s".
	s *string `json:"s,omitempty,omitzero" yaml:"s,omitempty" mapstructure:"s,omitempty"`
}

func (o *Thing) S() *string {
	return o.s
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Thing) UnmarshalJSON(value []byte) error {
	type ThingHelper struct {
		S *string `json:"s",omitempty`
	}
	type Plain Thing
	var helper ThingHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.s = helper.S
	*j = Thing(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Thing) MarshalJSON() ([]byte, error) {
	type ThingMarshalHelper struct {
		S *string `json:"s",omitempty`
	}
	helper := ThingMarshalHelper{
		S: j.s,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Thing) UnmarshalYAML(value *yaml.Node) error {
	type Plain Thing
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Thing(plain)
	return nil
}
