// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type Bar struct {
	// reftofoo corresponds to the JSON schema field "refToFoo".
	reftofoo *Foo `json:"refToFoo,omitempty,omitzero" yaml:"refToFoo,omitempty" mapstructure:"refToFoo,omitempty"`
}

type BarBuilder struct {
	reftofoo *Foo
}

func (b *BarBuilder) Build() *Bar {
	return &Bar{
		reftofoo: b.reftofoo,
	}
}

func (b *BarBuilder) WithRefToFoo(v *Foo) *BarBuilder {
	b.reftofoo = v
	return b
}

func (o *Bar) Clone() *BarBuilder {
	return NewBarBuilder(o)
}

func (o *Bar) RefToFoo() *Foo {
	return o.reftofoo
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Bar) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Reftofoo *Foo
	}
	type Plain Bar
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.reftofoo = rawStruct.Reftofoo
	plain = plain
	*j = Bar(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Bar) UnmarshalJSON(value []byte) error {
	type BarHelper struct {
		Reftofoo *Foo `json:"refToFoo,omitempty,omitzero"`
	}
	type Plain Bar
	var helper BarHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.reftofoo = helper.Reftofoo
	*j = Bar(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Bar) MarshalJSON() ([]byte, error) {
	type BarMarshalHelper struct {
		Reftofoo *Foo `json:"refToFoo,omitempty,omitzero"`
	}
	helper := BarMarshalHelper{
		Reftofoo: j.reftofoo,
	}
	return json.Marshal(helper)
}

type CyclicAndRequired1 struct {
	// a corresponds to the JSON schema field "a".
	a *Foo `json:"a,omitempty,omitzero" yaml:"a,omitempty" mapstructure:"a,omitempty"`
}

type CyclicAndRequired1Builder struct {
	a *Foo
}

func (b *CyclicAndRequired1Builder) Build() *CyclicAndRequired1 {
	return &CyclicAndRequired1{
		a: b.a,
	}
}

func (b *CyclicAndRequired1Builder) WithA(v *Foo) *CyclicAndRequired1Builder {
	b.a = v
	return b
}

func (o *CyclicAndRequired1) A() *Foo {
	return o.a
}

func (o *CyclicAndRequired1) Clone() *CyclicAndRequired1Builder {
	return NewCyclicAndRequired1Builder(o)
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CyclicAndRequired1) UnmarshalJSON(value []byte) error {
	type CyclicAndRequired1Helper struct {
		A *Foo `json:"a,omitempty,omitzero"`
	}
	type Plain CyclicAndRequired1
	var helper CyclicAndRequired1Helper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.a = helper.A
	*j = CyclicAndRequired1(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *CyclicAndRequired1) MarshalJSON() ([]byte, error) {
	type CyclicAndRequired1MarshalHelper struct {
		A *Foo `json:"a,omitempty,omitzero"`
	}
	helper := CyclicAndRequired1MarshalHelper{
		A: j.a,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *CyclicAndRequired1) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		A *Foo
	}
	type Plain CyclicAndRequired1
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.a = rawStruct.A
	plain = plain
	*j = CyclicAndRequired1(plain)
	return nil
}

type Foo struct {
	// reftobar corresponds to the JSON schema field "refToBar".
	reftobar Bar `json:"refToBar" yaml:"refToBar" mapstructure:"refToBar"`
}

type FooBuilder struct {
	reftobar Bar
}

func (b *FooBuilder) Build() *Foo {
	return &Foo{
		reftobar: b.reftobar,
	}
}

func (b *FooBuilder) WithRefToBar(v Bar) *FooBuilder {
	b.reftobar = v
	return b
}

func (o *Foo) Clone() *FooBuilder {
	return NewFooBuilder(o)
}

func (o *Foo) RefToBar() Bar {
	return o.reftobar
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Foo) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["refToBar"]; raw != nil && !ok {
		return fmt.Errorf("field refToBar in Foo: required")
	}
	type PlainRaw struct {
		Reftobar Bar
	}
	type Plain Foo
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.reftobar = rawStruct.Reftobar
	plain = plain
	*j = Foo(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Foo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["refToBar"]; raw != nil && !ok {
		return fmt.Errorf("field refToBar in Foo: required")
	}
	type FooHelper struct {
		Reftobar Bar `json:"refToBar"`
	}
	type Plain Foo
	var helper FooHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.reftobar = helper.Reftobar
	*j = Foo(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Foo) MarshalJSON() ([]byte, error) {
	type FooMarshalHelper struct {
		Reftobar Bar `json:"refToBar"`
	}
	helper := FooMarshalHelper{
		Reftobar: j.reftobar,
	}
	return json.Marshal(helper)
}

func NewBarBuilder(o *Bar) *BarBuilder {
	if o == nil {
		return &BarBuilder{}
	}
	return &BarBuilder{
		reftofoo: o.reftofoo,
	}
}

func NewCyclicAndRequired1Builder(o *CyclicAndRequired1) *CyclicAndRequired1Builder {
	if o == nil {
		return &CyclicAndRequired1Builder{}
	}
	return &CyclicAndRequired1Builder{
		a: o.a,
	}
}

func NewFooBuilder(o *Foo) *FooBuilder {
	if o == nil {
		return &FooBuilder{}
	}
	return &FooBuilder{
		reftobar: o.reftobar,
	}
}
