// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type ExclusiveMaximum struct {
	// myinteger corresponds to the JSON schema field "myInteger".
	myinteger int `json:"myInteger" yaml:"myInteger" mapstructure:"myInteger"`

	// mynullableinteger corresponds to the JSON schema field "myNullableInteger".
	mynullableinteger *int `json:"myNullableInteger,omitempty,omitzero" yaml:"myNullableInteger,omitempty" mapstructure:"myNullableInteger,omitempty"`

	// mynullablenumber corresponds to the JSON schema field "myNullableNumber".
	mynullablenumber *float64 `json:"myNullableNumber,omitempty,omitzero" yaml:"myNullableNumber,omitempty" mapstructure:"myNullableNumber,omitempty"`

	// mynumber corresponds to the JSON schema field "myNumber".
	mynumber float64 `json:"myNumber" yaml:"myNumber" mapstructure:"myNumber"`
}

type ExclusiveMaximumBuilder struct {
	myinteger int

	mynullableinteger *int

	mynullablenumber *float64

	mynumber float64
}

func (b *ExclusiveMaximumBuilder) Build() *ExclusiveMaximum {
	return &ExclusiveMaximum{
		myinteger:         b.myinteger,
		mynullableinteger: b.mynullableinteger,
		mynullablenumber:  b.mynullablenumber,
		mynumber:          b.mynumber,
	}
}

func (b *ExclusiveMaximumBuilder) WithMyInteger(v int) *ExclusiveMaximumBuilder {
	b.myinteger = v
	return b
}

func (b *ExclusiveMaximumBuilder) WithMyNullableInteger(v *int) *ExclusiveMaximumBuilder {
	b.mynullableinteger = v
	return b
}

func (b *ExclusiveMaximumBuilder) WithMyNullableNumber(v *float64) *ExclusiveMaximumBuilder {
	b.mynullablenumber = v
	return b
}

func (b *ExclusiveMaximumBuilder) WithMyNumber(v float64) *ExclusiveMaximumBuilder {
	b.mynumber = v
	return b
}

func (o *ExclusiveMaximum) Clone() *ExclusiveMaximumBuilder {
	return NewExclusiveMaximumBuilder(o)
}

func (o *ExclusiveMaximum) MyInteger() int {
	return o.myinteger
}

func (o *ExclusiveMaximum) MyNullableInteger() *int {
	return o.mynullableinteger
}

func (o *ExclusiveMaximum) MyNullableNumber() *float64 {
	return o.mynullablenumber
}

func (o *ExclusiveMaximum) MyNumber() float64 {
	return o.mynumber
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExclusiveMaximum) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myInteger"]; raw != nil && !ok {
		return fmt.Errorf("field myInteger in ExclusiveMaximum: required")
	}
	if _, ok := raw["myNumber"]; raw != nil && !ok {
		return fmt.Errorf("field myNumber in ExclusiveMaximum: required")
	}
	type ExclusiveMaximumHelper struct {
		Myinteger         int      `json:"myInteger"`
		Mynullableinteger *int     `json:"myNullableInteger",omitempty`
		Mynullablenumber  *float64 `json:"myNullableNumber",omitempty`
		Mynumber          float64  `json:"myNumber"`
	}
	type Plain ExclusiveMaximum
	var helper ExclusiveMaximumHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myinteger = helper.Myinteger
	plain.mynullableinteger = helper.Mynullableinteger
	plain.mynullablenumber = helper.Mynullablenumber
	plain.mynumber = helper.Mynumber
	if 2 <= plain.myinteger {
		return fmt.Errorf("field %s: must be < %v", "myInteger", 2)
	}
	if plain.mynullableinteger != nil && 2 <= *plain.mynullableinteger {
		return fmt.Errorf("field %s: must be < %v", "myNullableInteger", 2)
	}
	if plain.mynullablenumber != nil && 1.2 <= *plain.mynullablenumber {
		return fmt.Errorf("field %s: must be < %v", "myNullableNumber", 1.2)
	}
	if 1.2 <= plain.mynumber {
		return fmt.Errorf("field %s: must be < %v", "myNumber", 1.2)
	}
	*j = ExclusiveMaximum(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *ExclusiveMaximum) MarshalJSON() ([]byte, error) {
	type ExclusiveMaximumMarshalHelper struct {
		Myinteger         int      `json:"myInteger"`
		Mynullableinteger *int     `json:"myNullableInteger",omitempty`
		Mynullablenumber  *float64 `json:"myNullableNumber",omitempty`
		Mynumber          float64  `json:"myNumber"`
	}
	helper := ExclusiveMaximumMarshalHelper{
		Myinteger:         j.myinteger,
		Mynullableinteger: j.mynullableinteger,
		Mynullablenumber:  j.mynullablenumber,
		Mynumber:          j.mynumber,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ExclusiveMaximum) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["myInteger"]; raw != nil && !ok {
		return fmt.Errorf("field myInteger in ExclusiveMaximum: required")
	}
	if _, ok := raw["myNumber"]; raw != nil && !ok {
		return fmt.Errorf("field myNumber in ExclusiveMaximum: required")
	}
	type Plain ExclusiveMaximum
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if 2 <= plain.myinteger {
		return fmt.Errorf("field %s: must be < %v", "myInteger", 2)
	}
	if plain.mynullableinteger != nil && 2 <= *plain.mynullableinteger {
		return fmt.Errorf("field %s: must be < %v", "myNullableInteger", 2)
	}
	if plain.mynullablenumber != nil && 1.2 <= *plain.mynullablenumber {
		return fmt.Errorf("field %s: must be < %v", "myNullableNumber", 1.2)
	}
	if 1.2 <= plain.mynumber {
		return fmt.Errorf("field %s: must be < %v", "myNumber", 1.2)
	}
	*j = ExclusiveMaximum(plain)
	return nil
}

func NewExclusiveMaximumBuilder(o *ExclusiveMaximum) *ExclusiveMaximumBuilder {
	if o == nil {
		return &ExclusiveMaximumBuilder{}
	}
	return &ExclusiveMaximumBuilder{
		myinteger:         o.myinteger,
		mynullableinteger: o.mynullableinteger,
		mynullablenumber:  o.mynullablenumber,
		mynumber:          o.mynumber,
	}
}
