// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type ExclusiveMaximumOld struct {
	// myinteger corresponds to the JSON schema field "myInteger".
	myinteger int `json:"myInteger" yaml:"myInteger" mapstructure:"myInteger"`

	// mynullableinteger corresponds to the JSON schema field "myNullableInteger".
	mynullableinteger *int `json:"myNullableInteger,omitempty,omitzero" yaml:"myNullableInteger,omitempty" mapstructure:"myNullableInteger,omitempty"`

	// mynullablenumber corresponds to the JSON schema field "myNullableNumber".
	mynullablenumber interface{} `json:"myNullableNumber,omitempty,omitzero" yaml:"myNullableNumber,omitempty" mapstructure:"myNullableNumber,omitempty"`

	// mynumber corresponds to the JSON schema field "myNumber".
	mynumber float64 `json:"myNumber" yaml:"myNumber" mapstructure:"myNumber"`
}

func (o *ExclusiveMaximumOld) MyInteger() int {
	return o.myinteger
}

func (o *ExclusiveMaximumOld) MyNullableInteger() *int {
	return o.mynullableinteger
}

func (o *ExclusiveMaximumOld) MyNullableNumber() interface{} {
	return o.mynullablenumber
}

func (o *ExclusiveMaximumOld) MyNumber() float64 {
	return o.mynumber
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExclusiveMaximumOld) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myInteger"]; raw != nil && !ok {
		return fmt.Errorf("field myInteger in ExclusiveMaximumOld: required")
	}
	if _, ok := raw["myNumber"]; raw != nil && !ok {
		return fmt.Errorf("field myNumber in ExclusiveMaximumOld: required")
	}
	type ExclusiveMaximumOldHelper struct {
		Myinteger         int         `json:"myInteger"`
		Mynullableinteger *int        `json:"myNullableInteger",omitempty`
		Mynullablenumber  interface{} `json:"myNullableNumber",omitempty`
		Mynumber          float64     `json:"myNumber"`
	}
	type Plain ExclusiveMaximumOld
	var helper ExclusiveMaximumOldHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myinteger = helper.Myinteger
	plain.mynullableinteger = helper.Mynullableinteger
	plain.mynullablenumber = helper.Mynullablenumber
	plain.mynumber = helper.Mynumber
	if 2 <= plain.myinteger {
		return fmt.Errorf("field %s: must be < %v", "myInteger", 2)
	}
	if plain.mynullableinteger != nil && 2 <= *plain.mynullableinteger {
		return fmt.Errorf("field %s: must be < %v", "myNullableInteger", 2)
	}
	if 1.2 <= plain.mynumber {
		return fmt.Errorf("field %s: must be < %v", "myNumber", 1.2)
	}
	*j = ExclusiveMaximumOld(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *ExclusiveMaximumOld) MarshalJSON() ([]byte, error) {
	type ExclusiveMaximumOldMarshalHelper struct {
		Myinteger         int         `json:"myInteger"`
		Mynullableinteger *int        `json:"myNullableInteger",omitempty`
		Mynullablenumber  interface{} `json:"myNullableNumber",omitempty`
		Mynumber          float64     `json:"myNumber"`
	}
	helper := ExclusiveMaximumOldMarshalHelper{
		Myinteger:         j.myinteger,
		Mynullableinteger: j.mynullableinteger,
		Mynullablenumber:  j.mynullablenumber,
		Mynumber:          j.mynumber,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ExclusiveMaximumOld) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["myInteger"]; raw != nil && !ok {
		return fmt.Errorf("field myInteger in ExclusiveMaximumOld: required")
	}
	if _, ok := raw["myNumber"]; raw != nil && !ok {
		return fmt.Errorf("field myNumber in ExclusiveMaximumOld: required")
	}
	type Plain ExclusiveMaximumOld
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if 2 <= plain.myinteger {
		return fmt.Errorf("field %s: must be < %v", "myInteger", 2)
	}
	if plain.mynullableinteger != nil && 2 <= *plain.mynullableinteger {
		return fmt.Errorf("field %s: must be < %v", "myNullableInteger", 2)
	}
	if 1.2 <= plain.mynumber {
		return fmt.Errorf("field %s: must be < %v", "myNumber", 1.2)
	}
	*j = ExclusiveMaximumOld(plain)
	return nil
}
