// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

func NewRefExternalFileBuilder(o *RefExternalFile) *RefExternalFileBuilder {
	if o == nil {
		return &RefExternalFileBuilder{}
	}
	return &RefExternalFileBuilder{
		myexternalthing:        o.myexternalthing,
		someotherexternalthing: o.someotherexternalthing,
	}
}

func NewYamlStructNameFromFileBuilder(o *YamlStructNameFromFile) *YamlStructNameFromFileBuilder {
	if o == nil {
		return &YamlStructNameFromFileBuilder{}
	}
	return &YamlStructNameFromFileBuilder{
		foo: o.foo,
	}
}

type RefExternalFile struct {
	// myexternalthing corresponds to the JSON schema field "myExternalThing".
	myexternalthing *YamlStructNameFromFile `json:"myExternalThing,omitempty,omitzero" yaml:"myExternalThing,omitempty" mapstructure:"myExternalThing,omitempty"`

	// someotherexternalthing corresponds to the JSON schema field
	// "someOtherExternalThing".
	someotherexternalthing *YamlStructNameFromFile `json:"someOtherExternalThing,omitempty,omitzero" yaml:"someOtherExternalThing,omitempty" mapstructure:"someOtherExternalThing,omitempty"`
}

type RefExternalFileBuilder struct {
	myexternalthing *YamlStructNameFromFile

	someotherexternalthing *YamlStructNameFromFile
}

func (b *RefExternalFileBuilder) Build() *RefExternalFile {
	return &RefExternalFile{
		myexternalthing:        b.myexternalthing,
		someotherexternalthing: b.someotherexternalthing,
	}
}

func (b *RefExternalFileBuilder) WithMyExternalThing(v *YamlStructNameFromFile) *RefExternalFileBuilder {
	b.myexternalthing = v
	return b
}

func (b *RefExternalFileBuilder) WithSomeOtherExternalThing(v *YamlStructNameFromFile) *RefExternalFileBuilder {
	b.someotherexternalthing = v
	return b
}

func (o *RefExternalFile) Clone() *RefExternalFileBuilder {
	return NewRefExternalFileBuilder(o)
}

func (o *RefExternalFile) MyExternalThing() *YamlStructNameFromFile {
	return o.myexternalthing
}

func (o *RefExternalFile) SomeOtherExternalThing() *YamlStructNameFromFile {
	return o.someotherexternalthing
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RefExternalFile) UnmarshalJSON(value []byte) error {
	type RefExternalFileHelper struct {
		Myexternalthing        *YamlStructNameFromFile `json:"myExternalThing,omitempty,omitzero"`
		Someotherexternalthing *YamlStructNameFromFile `json:"someOtherExternalThing,omitempty,omitzero"`
	}
	type Plain RefExternalFile
	var helper RefExternalFileHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myexternalthing = helper.Myexternalthing
	plain.someotherexternalthing = helper.Someotherexternalthing
	*j = RefExternalFile(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *RefExternalFile) MarshalJSON() ([]byte, error) {
	type RefExternalFileMarshalHelper struct {
		Myexternalthing        *YamlStructNameFromFile `json:"myExternalThing,omitempty,omitzero"`
		Someotherexternalthing *YamlStructNameFromFile `json:"someOtherExternalThing,omitempty,omitzero"`
	}
	helper := RefExternalFileMarshalHelper{
		Myexternalthing:        j.myexternalthing,
		Someotherexternalthing: j.someotherexternalthing,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RefExternalFile) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Myexternalthing        *YamlStructNameFromFile
		Someotherexternalthing *YamlStructNameFromFile
	}
	type Plain RefExternalFile
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.myexternalthing = rawStruct.Myexternalthing
	plain.someotherexternalthing = rawStruct.Someotherexternalthing
	plain = plain
	*j = RefExternalFile(plain)
	return nil
}

type YamlStructNameFromFile struct {
	// foo corresponds to the JSON schema field "foo".
	foo *string `json:"foo,omitempty,omitzero" yaml:"foo,omitempty" mapstructure:"foo,omitempty"`
}

type YamlStructNameFromFileBuilder struct {
	foo *string
}

func (b *YamlStructNameFromFileBuilder) Build() *YamlStructNameFromFile {
	return &YamlStructNameFromFile{
		foo: b.foo,
	}
}

func (b *YamlStructNameFromFileBuilder) WithFoo(v *string) *YamlStructNameFromFileBuilder {
	b.foo = v
	return b
}

func (o *YamlStructNameFromFile) Clone() *YamlStructNameFromFileBuilder {
	return NewYamlStructNameFromFileBuilder(o)
}

func (o *YamlStructNameFromFile) Foo() *string {
	return o.foo
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *YamlStructNameFromFile) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Foo *string
	}
	type Plain YamlStructNameFromFile
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.foo = rawStruct.Foo
	plain = plain
	*j = YamlStructNameFromFile(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *YamlStructNameFromFile) UnmarshalJSON(value []byte) error {
	type YamlStructNameFromFileHelper struct {
		Foo *string `json:"foo,omitempty,omitzero"`
	}
	type Plain YamlStructNameFromFile
	var helper YamlStructNameFromFileHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.foo = helper.Foo
	*j = YamlStructNameFromFile(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *YamlStructNameFromFile) MarshalJSON() ([]byte, error) {
	type YamlStructNameFromFileMarshalHelper struct {
		Foo *string `json:"foo,omitempty,omitzero"`
	}
	helper := YamlStructNameFromFileMarshalHelper{
		Foo: j.foo,
	}
	return json.Marshal(helper)
}
