// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"

type Agreement struct {
	// atype corresponds to the JSON schema field "@type".
	atype string `json:"@type" yaml:"@type" mapstructure:"@type"`

	// permission corresponds to the JSON schema field "permission".
	permission *string `json:"permission,omitempty,omitzero" yaml:"permission,omitempty" mapstructure:"permission,omitempty"`

	// prohibition corresponds to the JSON schema field "prohibition".
	prohibition *float64 `json:"prohibition,omitempty,omitzero" yaml:"prohibition,omitempty" mapstructure:"prohibition,omitempty"`
}

type Agreement_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Agreement_0) UnmarshalJSON(value []byte) error {
	type Plain Agreement_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Agreement_0(plain)
	return nil
}

type Agreement_1 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Agreement_1) UnmarshalJSON(value []byte) error {
	type Plain Agreement_1
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Agreement_1(plain)
	return nil
}

func (o *Agreement) AType() string {
	return o.atype
}

func (o *Agreement) Permission() *string {
	return o.permission
}

func (o *Agreement) Prohibition() *float64 {
	return o.prohibition
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Agreement) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var agreement_0 Agreement_0
	var agreement_1 Agreement_1
	var errs []error
	if err := agreement_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := agreement_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 2 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type AgreementHelper struct {
		Atype       string   `json:"@type"`
		Permission  *string  `json:"permission",omitempty`
		Prohibition *float64 `json:"prohibition",omitempty`
	}
	type Plain Agreement
	var helper AgreementHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.atype = helper.Atype
	plain.permission = helper.Permission
	plain.prohibition = helper.Prohibition
	*j = Agreement(plain)
	return nil
}

type CommonType struct {
	// permission corresponds to the JSON schema field "permission".
	permission *string `json:"permission,omitempty,omitzero" yaml:"permission,omitempty" mapstructure:"permission,omitempty"`

	// prohibition corresponds to the JSON schema field "prohibition".
	prohibition *float64 `json:"prohibition,omitempty,omitzero" yaml:"prohibition,omitempty" mapstructure:"prohibition,omitempty"`
}

func (o *CommonType) Permission() *string {
	return o.permission
}

func (o *CommonType) Prohibition() *float64 {
	return o.prohibition
}
