// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type AllOf3 struct {
	// bar corresponds to the JSON schema field "bar".
	bar float64 `json:"bar" yaml:"bar" mapstructure:"bar"`

	// configurations corresponds to the JSON schema field "configurations".
	configurations []interface{} `json:"configurations,omitempty,omitzero" yaml:"configurations,omitempty" mapstructure:"configurations,omitempty"`

	// foo corresponds to the JSON schema field "foo".
	foo string `json:"foo" yaml:"foo" mapstructure:"foo"`
}

type AllOf3Builder struct {
	bar float64

	configurations []interface{}

	foo string
}

func (b *AllOf3Builder) Build() *AllOf3 {
	return &AllOf3{
		bar:            b.bar,
		configurations: b.configurations,
		foo:            b.foo,
	}
}

func (b *AllOf3Builder) WithBar(v float64) *AllOf3Builder {
	b.bar = v
	return b
}

func (b *AllOf3Builder) WithConfigurations(v []interface{}) *AllOf3Builder {
	b.configurations = v
	return b
}

func (b *AllOf3Builder) WithFoo(v string) *AllOf3Builder {
	b.foo = v
	return b
}

func (o *AllOf3) Bar() float64 {
	return o.bar
}

func (o *AllOf3) Clone() *AllOf3Builder {
	return NewAllOf3Builder(o)
}

func (o *AllOf3) Configurations() []interface{} {
	return o.configurations
}

func (o *AllOf3) Foo() string {
	return o.foo
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AllOf3) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AllOf3: required")
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AllOf3: required")
	}
	type AllOf3Helper struct {
		Bar            float64       `json:"bar"`
		Configurations []interface{} `json:"configurations",omitempty`
		Foo            string        `json:"foo"`
	}
	type Plain AllOf3
	var helper AllOf3Helper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.bar = helper.Bar
	plain.configurations = helper.Configurations
	plain.foo = helper.Foo
	*j = AllOf3(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AllOf3) MarshalJSON() ([]byte, error) {
	type AllOf3MarshalHelper struct {
		Bar            float64       `json:"bar"`
		Configurations []interface{} `json:"configurations",omitempty`
		Foo            string        `json:"foo"`
	}
	helper := AllOf3MarshalHelper{
		Bar:            j.bar,
		Configurations: j.configurations,
		Foo:            j.foo,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AllOf3) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AllOf3: required")
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AllOf3: required")
	}
	type Plain AllOf3
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AllOf3(plain)
	return nil
}

func NewAllOf3Builder(o *AllOf3) *AllOf3Builder {
	if o == nil {
		return &AllOf3Builder{}
	}
	return &AllOf3Builder{
		bar:            o.bar,
		configurations: o.configurations,
		foo:            o.foo,
	}
}
