// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"

// The server's response to a tool call
type CallToolResult struct {
	// content corresponds to the JSON schema field "content".
	content []CallToolResultcontentElem `json:"content,omitempty,omitzero" yaml:"content,omitempty" mapstructure:"content,omitempty"`
}

func (o *CallToolResult) Content() []CallToolResultcontentElem {
	return o.content
}

// Text provided to or from an LLM.
type CallToolResultcontentElem struct {
	// The text content of the message.
	text string `json:"text" yaml:"text" mapstructure:"text"`
}

func (o *CallToolResultcontentElem) Text() string {
	return o.text
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CallToolResultcontentElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in CallToolResultcontentElem: required")
	}
	type CallToolResultcontentElemHelper struct {
		Text string `json:"text"`
	}
	type Plain CallToolResultcontentElem
	var helper CallToolResultcontentElemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.text = helper.Text
	*j = CallToolResultcontentElem(plain)
	return nil
}

// Text provided to or from an LLM.
type TextContent struct {
	// The text content of the message.
	text string `json:"text" yaml:"text" mapstructure:"text"`
}

func (o *TextContent) Text() string {
	return o.text
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TextContent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in TextContent: required")
	}
	type TextContentHelper struct {
		Text string `json:"text"`
	}
	type Plain TextContent
	var helper TextContentHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.text = helper.Text
	*j = TextContent(plain)
	return nil
}
