// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type AllOf2 struct {
	// configurations corresponds to the JSON schema field "configurations".
	configurations []AllOf2configurationsElem `json:"configurations,omitempty,omitzero" yaml:"configurations,omitempty" mapstructure:"configurations,omitempty"`
}

type AllOf2Builder struct {
	configurations []AllOf2configurationsElem
}

func (b *AllOf2Builder) Build() *AllOf2 {
	return &AllOf2{
		configurations: b.configurations,
	}
}

func (b *AllOf2Builder) WithConfigurations(v []AllOf2configurationsElem) *AllOf2Builder {
	b.configurations = v
	return b
}

func (o *AllOf2) Clone() *AllOf2Builder {
	return NewAllOf2Builder(o)
}

func (o *AllOf2) Configurations() []AllOf2configurationsElem {
	return o.configurations
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AllOf2) UnmarshalJSON(value []byte) error {
	type AllOf2Helper struct {
		Configurations []AllOf2configurationsElem `json:"configurations",omitempty`
	}
	type Plain AllOf2
	var helper AllOf2Helper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.configurations = helper.Configurations
	*j = AllOf2(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AllOf2) MarshalJSON() ([]byte, error) {
	type AllOf2MarshalHelper struct {
		Configurations []AllOf2configurationsElem `json:"configurations",omitempty`
	}
	helper := AllOf2MarshalHelper{
		Configurations: j.configurations,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AllOf2) UnmarshalYAML(value *yaml.Node) error {
	type Plain AllOf2
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AllOf2(plain)
	return nil
}

type AllOf2configurationsElem struct {
	// bar corresponds to the JSON schema field "bar".
	bar float64 `json:"bar" yaml:"bar" mapstructure:"bar"`

	// baz corresponds to the JSON schema field "baz".
	baz *bool `json:"baz,omitempty,omitzero" yaml:"baz,omitempty" mapstructure:"baz,omitempty"`

	// foo corresponds to the JSON schema field "foo".
	foo string `json:"foo" yaml:"foo" mapstructure:"foo"`
}

type AllOf2configurationsElemBuilder struct {
	bar float64

	baz *bool

	foo string
}

func (b *AllOf2configurationsElemBuilder) Build() *AllOf2configurationsElem {
	return &AllOf2configurationsElem{
		bar: b.bar,
		baz: b.baz,
		foo: b.foo,
	}
}

func (b *AllOf2configurationsElemBuilder) WithBar(v float64) *AllOf2configurationsElemBuilder {
	b.bar = v
	return b
}

func (b *AllOf2configurationsElemBuilder) WithBaz(v *bool) *AllOf2configurationsElemBuilder {
	b.baz = v
	return b
}

func (b *AllOf2configurationsElemBuilder) WithFoo(v string) *AllOf2configurationsElemBuilder {
	b.foo = v
	return b
}

func (o *AllOf2configurationsElem) Bar() float64 {
	return o.bar
}

func (o *AllOf2configurationsElem) Baz() *bool {
	return o.baz
}

func (o *AllOf2configurationsElem) Clone() *AllOf2configurationsElemBuilder {
	return NewAllOf2configurationsElemBuilder(o)
}

func (o *AllOf2configurationsElem) Foo() string {
	return o.foo
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AllOf2configurationsElem) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AllOf2configurationsElem: required")
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AllOf2configurationsElem: required")
	}
	type Plain AllOf2configurationsElem
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AllOf2configurationsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AllOf2configurationsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AllOf2configurationsElem: required")
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in AllOf2configurationsElem: required")
	}
	type AllOf2configurationsElemHelper struct {
		Bar float64 `json:"bar"`
		Baz *bool   `json:"baz",omitempty`
		Foo string  `json:"foo"`
	}
	type Plain AllOf2configurationsElem
	var helper AllOf2configurationsElemHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.bar = helper.Bar
	plain.baz = helper.Baz
	plain.foo = helper.Foo
	*j = AllOf2configurationsElem(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *AllOf2configurationsElem) MarshalJSON() ([]byte, error) {
	type AllOf2configurationsElemMarshalHelper struct {
		Bar float64 `json:"bar"`
		Baz *bool   `json:"baz",omitempty`
		Foo string  `json:"foo"`
	}
	helper := AllOf2configurationsElemMarshalHelper{
		Bar: j.bar,
		Baz: j.baz,
		Foo: j.foo,
	}
	return json.Marshal(helper)
}

type Bar struct {
	// bar corresponds to the JSON schema field "bar".
	bar float64 `json:"bar" yaml:"bar" mapstructure:"bar"`
}

type BarBuilder struct {
	bar float64
}

func (b *BarBuilder) Build() *Bar {
	return &Bar{
		bar: b.bar,
	}
}

func (b *BarBuilder) WithBar(v float64) *BarBuilder {
	b.bar = v
	return b
}

func (o *Bar) Bar() float64 {
	return o.bar
}

func (o *Bar) Clone() *BarBuilder {
	return NewBarBuilder(o)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Bar) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in Bar: required")
	}
	type Plain Bar
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Bar(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Bar) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in Bar: required")
	}
	type BarHelper struct {
		Bar float64 `json:"bar"`
	}
	type Plain Bar
	var helper BarHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.bar = helper.Bar
	*j = Bar(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Bar) MarshalJSON() ([]byte, error) {
	type BarMarshalHelper struct {
		Bar float64 `json:"bar"`
	}
	helper := BarMarshalHelper{
		Bar: j.bar,
	}
	return json.Marshal(helper)
}

type Baz struct {
	// baz corresponds to the JSON schema field "baz".
	baz *bool `json:"baz,omitempty,omitzero" yaml:"baz,omitempty" mapstructure:"baz,omitempty"`
}

type BazBuilder struct {
	baz *bool
}

func (b *BazBuilder) Build() *Baz {
	return &Baz{
		baz: b.baz,
	}
}

func (b *BazBuilder) WithBaz(v *bool) *BazBuilder {
	b.baz = v
	return b
}

func (o *Baz) Baz() *bool {
	return o.baz
}

func (o *Baz) Clone() *BazBuilder {
	return NewBazBuilder(o)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Baz) UnmarshalYAML(value *yaml.Node) error {
	type Plain Baz
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Baz(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Baz) UnmarshalJSON(value []byte) error {
	type BazHelper struct {
		Baz *bool `json:"baz",omitempty`
	}
	type Plain Baz
	var helper BazHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.baz = helper.Baz
	*j = Baz(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Baz) MarshalJSON() ([]byte, error) {
	type BazMarshalHelper struct {
		Baz *bool `json:"baz",omitempty`
	}
	helper := BazMarshalHelper{
		Baz: j.baz,
	}
	return json.Marshal(helper)
}

type Foo struct {
	// foo corresponds to the JSON schema field "foo".
	foo string `json:"foo" yaml:"foo" mapstructure:"foo"`
}

type FooBuilder struct {
	foo string
}

func (b *FooBuilder) Build() *Foo {
	return &Foo{
		foo: b.foo,
	}
}

func (b *FooBuilder) WithFoo(v string) *FooBuilder {
	b.foo = v
	return b
}

func (o *Foo) Clone() *FooBuilder {
	return NewFooBuilder(o)
}

func (o *Foo) Foo() string {
	return o.foo
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Foo) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in Foo: required")
	}
	type Plain Foo
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Foo(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Foo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in Foo: required")
	}
	type FooHelper struct {
		Foo string `json:"foo"`
	}
	type Plain Foo
	var helper FooHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.foo = helper.Foo
	*j = Foo(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Foo) MarshalJSON() ([]byte, error) {
	type FooMarshalHelper struct {
		Foo string `json:"foo"`
	}
	helper := FooMarshalHelper{
		Foo: j.foo,
	}
	return json.Marshal(helper)
}

func NewAllOf2Builder(o *AllOf2) *AllOf2Builder {
	if o == nil {
		return &AllOf2Builder{}
	}
	return &AllOf2Builder{
		configurations: o.configurations,
	}
}

func NewAllOf2configurationsElemBuilder(o *AllOf2configurationsElem) *AllOf2configurationsElemBuilder {
	if o == nil {
		return &AllOf2configurationsElemBuilder{}
	}
	return &AllOf2configurationsElemBuilder{
		bar: o.bar,
		baz: o.baz,
		foo: o.foo,
	}
}

func NewBarBuilder(o *Bar) *BarBuilder {
	if o == nil {
		return &BarBuilder{}
	}
	return &BarBuilder{
		bar: o.bar,
	}
}

func NewBazBuilder(o *Baz) *BazBuilder {
	if o == nil {
		return &BazBuilder{}
	}
	return &BazBuilder{
		baz: o.baz,
	}
}

func NewFooBuilder(o *Foo) *FooBuilder {
	if o == nil {
		return &FooBuilder{}
	}
	return &FooBuilder{
		foo: o.foo,
	}
}
