// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

type Capitalization struct {
	// html corresponds to the JSON schema field "html".
	html *string `json:"html,omitempty,omitzero" yaml:"html,omitempty" mapstructure:"html,omitempty"`

	// htmlsomethingelse corresponds to the JSON schema field "htmlSomethingElse".
	htmlsomethingelse *string `json:"htmlSomethingElse,omitempty,omitzero" yaml:"htmlSomethingElse,omitempty" mapstructure:"htmlSomethingElse,omitempty"`

	// html_2 corresponds to the JSON schema field "html__".
	html_2 *string `json:"html__,omitempty,omitzero" yaml:"html__,omitempty" mapstructure:"html__,omitempty"`

	// htmlsomething corresponds to the JSON schema field "html_something".
	htmlsomething *string `json:"html_something,omitempty,omitzero" yaml:"html_something,omitempty" mapstructure:"html_something,omitempty"`

	// id corresponds to the JSON schema field "id".
	id *string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// idsomethingelse corresponds to the JSON schema field "idSomethingElse".
	idsomethingelse *string `json:"idSomethingElse,omitempty,omitzero" yaml:"idSomethingElse,omitempty" mapstructure:"idSomethingElse,omitempty"`

	// id_2 corresponds to the JSON schema field "id__".
	id_2 *string `json:"id__,omitempty,omitzero" yaml:"id__,omitempty" mapstructure:"id__,omitempty"`

	// idsomething corresponds to the JSON schema field "id_something".
	idsomething *string `json:"id_something,omitempty,omitzero" yaml:"id_something,omitempty" mapstructure:"id_something,omitempty"`

	// url corresponds to the JSON schema field "url".
	url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`

	// urlsomethingelse corresponds to the JSON schema field "urlSomethingElse".
	urlsomethingelse *string `json:"urlSomethingElse,omitempty,omitzero" yaml:"urlSomethingElse,omitempty" mapstructure:"urlSomethingElse,omitempty"`

	// url_2 corresponds to the JSON schema field "url__".
	url_2 *string `json:"url__,omitempty,omitzero" yaml:"url__,omitempty" mapstructure:"url__,omitempty"`

	// urlsomething corresponds to the JSON schema field "url_something".
	urlsomething *string `json:"url_something,omitempty,omitzero" yaml:"url_something,omitempty" mapstructure:"url_something,omitempty"`

	// aアトリビュート corresponds to the JSON schema field "アトリビュート".
	aアトリビュート *string `json:"アトリビュート,omitempty,omitzero" yaml:"アトリビュート,omitempty" mapstructure:"アトリビュート,omitempty"`

	// a属性 corresponds to the JSON schema field "属性".
	a属性 *string `json:"属性,omitempty,omitzero" yaml:"属性,omitempty" mapstructure:"属性,omitempty"`

	// a屬性 corresponds to the JSON schema field "屬性".
	a屬性 *string `json:"屬性,omitempty,omitzero" yaml:"屬性,omitempty" mapstructure:"屬性,omitempty"`

	// a속성 corresponds to the JSON schema field "속성".
	a속성 *string `json:"속성,omitempty,omitzero" yaml:"속성,omitempty" mapstructure:"속성,omitempty"`
}

type CapitalizationBuilder struct {
	html *string

	htmlsomethingelse *string

	html_2 *string

	htmlsomething *string

	id *string

	idsomethingelse *string

	id_2 *string

	idsomething *string

	url *string

	urlsomethingelse *string

	url_2 *string

	urlsomething *string

	aアトリビュート *string

	a属性 *string

	a屬性 *string

	a속성 *string
}

func (b *CapitalizationBuilder) Build() *Capitalization {
	return &Capitalization{
		html:              b.html,
		htmlsomethingelse: b.htmlsomethingelse,
		html_2:            b.html_2,
		htmlsomething:     b.htmlsomething,
		id:                b.id,
		idsomethingelse:   b.idsomethingelse,
		id_2:              b.id_2,
		idsomething:       b.idsomething,
		url:               b.url,
		urlsomethingelse:  b.urlsomethingelse,
		url_2:             b.url_2,
		urlsomething:      b.urlsomething,
		aアトリビュート:          b.aアトリビュート,
		a属性:               b.a属性,
		a屬性:               b.a屬性,
		a속성:               b.a속성,
	}
}

func (b *CapitalizationBuilder) WithAアトリビュート(v *string) *CapitalizationBuilder {
	b.aアトリビュート = v
	return b
}

func (b *CapitalizationBuilder) WithA属性(v *string) *CapitalizationBuilder {
	b.a属性 = v
	return b
}

func (b *CapitalizationBuilder) WithA屬性(v *string) *CapitalizationBuilder {
	b.a屬性 = v
	return b
}

func (b *CapitalizationBuilder) WithA속성(v *string) *CapitalizationBuilder {
	b.a속성 = v
	return b
}

func (b *CapitalizationBuilder) WithHtMl(v *string) *CapitalizationBuilder {
	b.html = v
	return b
}

func (b *CapitalizationBuilder) WithHtMlSomething(v *string) *CapitalizationBuilder {
	b.htmlsomething = v
	return b
}

func (b *CapitalizationBuilder) WithHtMlSomethingElse(v *string) *CapitalizationBuilder {
	b.htmlsomethingelse = v
	return b
}

func (b *CapitalizationBuilder) WithID(v *string) *CapitalizationBuilder {
	b.id = v
	return b
}

func (b *CapitalizationBuilder) WithIDSomething(v *string) *CapitalizationBuilder {
	b.idsomething = v
	return b
}

func (b *CapitalizationBuilder) WithIDSomethingElse(v *string) *CapitalizationBuilder {
	b.idsomethingelse = v
	return b
}

func (b *CapitalizationBuilder) WithURL(v *string) *CapitalizationBuilder {
	b.url = v
	return b
}

func (b *CapitalizationBuilder) WithURLSomething(v *string) *CapitalizationBuilder {
	b.urlsomething = v
	return b
}

func (b *CapitalizationBuilder) WithURLSomethingElse(v *string) *CapitalizationBuilder {
	b.urlsomethingelse = v
	return b
}

func (o *Capitalization) Aアトリビュート() *string {
	return o.aアトリビュート
}

func (o *Capitalization) A属性() *string {
	return o.a属性
}

func (o *Capitalization) A屬性() *string {
	return o.a屬性
}

func (o *Capitalization) A속성() *string {
	return o.a속성
}

func (o *Capitalization) Clone() *CapitalizationBuilder {
	return NewCapitalizationBuilder(o)
}

func (o *Capitalization) HtMl() *string {
	return o.html
}

func (o *Capitalization) HtMlSomething() *string {
	return o.htmlsomething
}

func (o *Capitalization) HtMlSomethingElse() *string {
	return o.htmlsomethingelse
}

func (o *Capitalization) ID() *string {
	return o.id
}

func (o *Capitalization) IDSomething() *string {
	return o.idsomething
}

func (o *Capitalization) IDSomethingElse() *string {
	return o.idsomethingelse
}

func (o *Capitalization) URL() *string {
	return o.url
}

func (o *Capitalization) URLSomething() *string {
	return o.urlsomething
}

func (o *Capitalization) URLSomethingElse() *string {
	return o.urlsomethingelse
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Capitalization) UnmarshalJSON(value []byte) error {
	type CapitalizationHelper struct {
		Html              *string `json:"html",omitempty`
		Htmlsomethingelse *string `json:"htmlSomethingElse",omitempty`
		Html_2            *string `json:"html__",omitempty`
		Htmlsomething     *string `json:"html_something",omitempty`
		Id                *string `json:"id",omitempty`
		Idsomethingelse   *string `json:"idSomethingElse",omitempty`
		Id_2              *string `json:"id__",omitempty`
		Idsomething       *string `json:"id_something",omitempty`
		Url               *string `json:"url",omitempty`
		Urlsomethingelse  *string `json:"urlSomethingElse",omitempty`
		Url_2             *string `json:"url__",omitempty`
		Urlsomething      *string `json:"url_something",omitempty`
		Aアトリビュート          *string `json:"アトリビュート",omitempty`
		A属性               *string `json:"属性",omitempty`
		A屬性               *string `json:"屬性",omitempty`
		A속성               *string `json:"속성",omitempty`
	}
	type Plain Capitalization
	var helper CapitalizationHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.html = helper.Html
	plain.htmlsomethingelse = helper.Htmlsomethingelse
	plain.html_2 = helper.Html_2
	plain.htmlsomething = helper.Htmlsomething
	plain.id = helper.Id
	plain.idsomethingelse = helper.Idsomethingelse
	plain.id_2 = helper.Id_2
	plain.idsomething = helper.Idsomething
	plain.url = helper.Url
	plain.urlsomethingelse = helper.Urlsomethingelse
	plain.url_2 = helper.Url_2
	plain.urlsomething = helper.Urlsomething
	plain.aアトリビュート = helper.Aアトリビュート
	plain.a属性 = helper.A属性
	plain.a屬性 = helper.A屬性
	plain.a속성 = helper.A속성
	*j = Capitalization(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Capitalization) MarshalJSON() ([]byte, error) {
	type CapitalizationMarshalHelper struct {
		Html              *string `json:"html",omitempty`
		Htmlsomethingelse *string `json:"htmlSomethingElse",omitempty`
		Html_2            *string `json:"html__",omitempty`
		Htmlsomething     *string `json:"html_something",omitempty`
		Id                *string `json:"id",omitempty`
		Idsomethingelse   *string `json:"idSomethingElse",omitempty`
		Id_2              *string `json:"id__",omitempty`
		Idsomething       *string `json:"id_something",omitempty`
		Url               *string `json:"url",omitempty`
		Urlsomethingelse  *string `json:"urlSomethingElse",omitempty`
		Url_2             *string `json:"url__",omitempty`
		Urlsomething      *string `json:"url_something",omitempty`
		Aアトリビュート          *string `json:"アトリビュート",omitempty`
		A属性               *string `json:"属性",omitempty`
		A屬性               *string `json:"屬性",omitempty`
		A속성               *string `json:"속성",omitempty`
	}
	helper := CapitalizationMarshalHelper{
		Html:              j.html,
		Htmlsomethingelse: j.htmlsomethingelse,
		Html_2:            j.html_2,
		Htmlsomething:     j.htmlsomething,
		Id:                j.id,
		Idsomethingelse:   j.idsomethingelse,
		Id_2:              j.id_2,
		Idsomething:       j.idsomething,
		Url:               j.url,
		Urlsomethingelse:  j.urlsomethingelse,
		Url_2:             j.url_2,
		Urlsomething:      j.urlsomething,
		Aアトリビュート:          j.aアトリビュート,
		A属性:               j.a属性,
		A屬性:               j.a屬性,
		A속성:               j.a속성,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Capitalization) UnmarshalYAML(value *yaml.Node) error {
	type Plain Capitalization
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Capitalization(plain)
	return nil
}

func NewCapitalizationBuilder(o *Capitalization) *CapitalizationBuilder {
	if o == nil {
		return &CapitalizationBuilder{}
	}
	return &CapitalizationBuilder{
		html:              o.html,
		htmlsomethingelse: o.htmlsomethingelse,
		html_2:            o.html_2,
		htmlsomething:     o.htmlsomething,
		id:                o.id,
		idsomethingelse:   o.idsomethingelse,
		id_2:              o.id_2,
		idsomething:       o.idsomething,
		url:               o.url,
		urlsomethingelse:  o.urlsomethingelse,
		url_2:             o.url_2,
		urlsomething:      o.urlsomething,
		aアトリビュート:          o.aアトリビュート,
		a属性:               o.a属性,
		a屬性:               o.a屬性,
		a속성:               o.a속성,
	}
}
