// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "github.com/go-viper/mapstructure/v2"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "strings"

type ArrayAdditionalProperties struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ArrayAdditionalPropertiesBuilder struct {
	name *string
}

func (b *ArrayAdditionalPropertiesBuilder) Build() *ArrayAdditionalProperties {
	return &ArrayAdditionalProperties{
		name: b.name,
	}
}

func (b *ArrayAdditionalPropertiesBuilder) WithName(v *string) *ArrayAdditionalPropertiesBuilder {
	b.name = v
	return b
}

func (o *ArrayAdditionalProperties) Clone() *ArrayAdditionalPropertiesBuilder {
	return NewArrayAdditionalPropertiesBuilder(o)
}

func (o *ArrayAdditionalProperties) Name() *string {
	return o.name
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArrayAdditionalProperties) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type ArrayAdditionalPropertiesHelper struct {
		Name *string `json:"name,omitempty,omitzero"`
	}
	type Plain ArrayAdditionalProperties
	var helper ArrayAdditionalPropertiesHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	var additionalPropsRaw map[string]interface{}
	if err := mapstructure.Decode(raw, &additionalPropsRaw); err != nil {
		return err
	}
	plain.AdditionalProperties = func() interface{} {
		if additionalPropsRaw == nil {
			return nil
		}
		return additionalPropsRaw
	}()
	*j = ArrayAdditionalProperties(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *ArrayAdditionalProperties) MarshalJSON() ([]byte, error) {
	type ArrayAdditionalPropertiesMarshalHelper struct {
		Name *string `json:"name,omitempty,omitzero"`
	}
	helper := ArrayAdditionalPropertiesMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ArrayAdditionalProperties) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type PlainRaw struct {
		Name                 *string
		AdditionalProperties interface{}
	}
	type Plain ArrayAdditionalProperties
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.name = rawStruct.Name
	plain.AdditionalProperties = rawStruct.AdditionalProperties
	plain = plain
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	var additionalPropsRaw map[string]interface{}
	if err := mapstructure.Decode(raw, &additionalPropsRaw); err != nil {
		return err
	}
	plain.AdditionalProperties = additionalPropsRaw
	*j = ArrayAdditionalProperties(plain)
	return nil
}

func NewArrayAdditionalPropertiesBuilder(o *ArrayAdditionalProperties) *ArrayAdditionalPropertiesBuilder {
	if o == nil {
		return &ArrayAdditionalPropertiesBuilder{}
	}
	return &ArrayAdditionalPropertiesBuilder{
		name: o.name,
	}
}
