// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "github.com/go-viper/mapstructure/v2"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "strings"

type IntAdditionalProperties struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type IntAdditionalPropertiesBuilder struct {
	name *string
}

func (b *IntAdditionalPropertiesBuilder) Build() *IntAdditionalProperties {
	return &IntAdditionalProperties{
		name: b.name,
	}
}

func (b *IntAdditionalPropertiesBuilder) WithName(v *string) *IntAdditionalPropertiesBuilder {
	b.name = v
	return b
}

func (o *IntAdditionalProperties) Clone() *IntAdditionalPropertiesBuilder {
	return NewIntAdditionalPropertiesBuilder(o)
}

func (o *IntAdditionalProperties) Name() *string {
	return o.name
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IntAdditionalProperties) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type IntAdditionalPropertiesHelper struct {
		Name *string `json:"name,omitempty,omitzero"`
	}
	type Plain IntAdditionalProperties
	var helper IntAdditionalPropertiesHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.name = helper.Name
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	var additionalPropsRaw map[string]interface{}
	if err := mapstructure.Decode(raw, &additionalPropsRaw); err != nil {
		return err
	}
	plain.AdditionalProperties = func() interface{} {
		if additionalPropsRaw == nil {
			return nil
		}
		return additionalPropsRaw
	}()
	*j = IntAdditionalProperties(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *IntAdditionalProperties) MarshalJSON() ([]byte, error) {
	type IntAdditionalPropertiesMarshalHelper struct {
		Name *string `json:"name,omitempty,omitzero"`
	}
	helper := IntAdditionalPropertiesMarshalHelper{
		Name: j.name,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *IntAdditionalProperties) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type PlainRaw struct {
		Name                 *string
		AdditionalProperties interface{}
	}
	type Plain IntAdditionalProperties
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.name = rawStruct.Name
	plain.AdditionalProperties = rawStruct.AdditionalProperties
	plain = plain
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	var additionalPropsRaw map[string]interface{}
	if err := mapstructure.Decode(raw, &additionalPropsRaw); err != nil {
		return err
	}
	plain.AdditionalProperties = additionalPropsRaw
	*j = IntAdditionalProperties(plain)
	return nil
}

func NewIntAdditionalPropertiesBuilder(o *IntAdditionalProperties) *IntAdditionalPropertiesBuilder {
	if o == nil {
		return &IntAdditionalPropertiesBuilder{}
	}
	return &IntAdditionalPropertiesBuilder{
		name: o.name,
	}
}
