// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type NumberAdditionalPropertiesJson struct {
	// name corresponds to the JSON schema field "name".
	name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	AdditionalProperties map[string]float64 `mapstructure:",remain"`
}

func (o *NumberAdditionalPropertiesJson) Name() *string {
	return o.name
}
