// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "math"

type MultipleOf struct {
	// myinteger corresponds to the JSON schema field "myInteger".
	myinteger int `json:"myInteger" yaml:"myInteger" mapstructure:"myInteger"`

	// mynullableinteger corresponds to the JSON schema field "myNullableInteger".
	mynullableinteger *int `json:"myNullableInteger,omitempty,omitzero" yaml:"myNullableInteger,omitempty" mapstructure:"myNullableInteger,omitempty"`

	// mynullablenumber corresponds to the JSON schema field "myNullableNumber".
	mynullablenumber *float64 `json:"myNullableNumber,omitempty,omitzero" yaml:"myNullableNumber,omitempty" mapstructure:"myNullableNumber,omitempty"`

	// mynumber corresponds to the JSON schema field "myNumber".
	mynumber float64 `json:"myNumber" yaml:"myNumber" mapstructure:"myNumber"`
}

type MultipleOfBuilder struct {
	myinteger int

	mynullableinteger *int

	mynullablenumber *float64

	mynumber float64
}

func (b *MultipleOfBuilder) Build() *MultipleOf {
	return &MultipleOf{
		myinteger:         b.myinteger,
		mynullableinteger: b.mynullableinteger,
		mynullablenumber:  b.mynullablenumber,
		mynumber:          b.mynumber,
	}
}

func (b *MultipleOfBuilder) WithMyInteger(v int) *MultipleOfBuilder {
	b.myinteger = v
	return b
}

func (b *MultipleOfBuilder) WithMyNullableInteger(v *int) *MultipleOfBuilder {
	b.mynullableinteger = v
	return b
}

func (b *MultipleOfBuilder) WithMyNullableNumber(v *float64) *MultipleOfBuilder {
	b.mynullablenumber = v
	return b
}

func (b *MultipleOfBuilder) WithMyNumber(v float64) *MultipleOfBuilder {
	b.mynumber = v
	return b
}

func (o *MultipleOf) Clone() *MultipleOfBuilder {
	return NewMultipleOfBuilder(o)
}

func (o *MultipleOf) MyInteger() int {
	return o.myinteger
}

func (o *MultipleOf) MyNullableInteger() *int {
	return o.mynullableinteger
}

func (o *MultipleOf) MyNullableNumber() *float64 {
	return o.mynullablenumber
}

func (o *MultipleOf) MyNumber() float64 {
	return o.mynumber
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MultipleOf) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myInteger"]; raw != nil && !ok {
		return fmt.Errorf("field myInteger in MultipleOf: required")
	}
	if _, ok := raw["myNumber"]; raw != nil && !ok {
		return fmt.Errorf("field myNumber in MultipleOf: required")
	}
	type MultipleOfHelper struct {
		Myinteger         int      `json:"myInteger"`
		Mynullableinteger *int     `json:"myNullableInteger",omitempty`
		Mynullablenumber  *float64 `json:"myNullableNumber",omitempty`
		Mynumber          float64  `json:"myNumber"`
	}
	type Plain MultipleOf
	var helper MultipleOfHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.myinteger = helper.Myinteger
	plain.mynullableinteger = helper.Mynullableinteger
	plain.mynullablenumber = helper.Mynullablenumber
	plain.mynumber = helper.Mynumber
	if plain.myinteger%2 != 0 {
		return fmt.Errorf("field %s: must be a multiple of %v", "myInteger", 2.000000)
	}
	if plain.mynullableinteger != nil && *plain.mynullableinteger%2 != 0 {
		return fmt.Errorf("field %s: must be a multiple of %v", "myNullableInteger", 2.000000)
	}
	if plain.mynullablenumber != nil {
		remainder := math.Mod(*plain.mynullablenumber, 0.2)
		if !(math.Abs(remainder) < 1e-10 || math.Abs(remainder-0.2) < 1e-10) {
			return fmt.Errorf("field %s: must be a multiple of %v", "myNullableNumber", 0.200000)
		}
	}
	{
		remainder := math.Mod(plain.mynumber, 0.2)
		if !(math.Abs(remainder) < 1e-10 || math.Abs(remainder-0.2) < 1e-10) {
			return fmt.Errorf("field %s: must be a multiple of %v", "myNumber", 0.200000)
		}
	}
	*j = MultipleOf(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *MultipleOf) MarshalJSON() ([]byte, error) {
	type MultipleOfMarshalHelper struct {
		Myinteger         int      `json:"myInteger"`
		Mynullableinteger *int     `json:"myNullableInteger",omitempty`
		Mynullablenumber  *float64 `json:"myNullableNumber",omitempty`
		Mynumber          float64  `json:"myNumber"`
	}
	helper := MultipleOfMarshalHelper{
		Myinteger:         j.myinteger,
		Mynullableinteger: j.mynullableinteger,
		Mynullablenumber:  j.mynullablenumber,
		Mynumber:          j.mynumber,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *MultipleOf) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["myInteger"]; raw != nil && !ok {
		return fmt.Errorf("field myInteger in MultipleOf: required")
	}
	if _, ok := raw["myNumber"]; raw != nil && !ok {
		return fmt.Errorf("field myNumber in MultipleOf: required")
	}
	type Plain MultipleOf
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.myinteger%2 != 0 {
		return fmt.Errorf("field %s: must be a multiple of %v", "myInteger", 2.000000)
	}
	if plain.mynullableinteger != nil && *plain.mynullableinteger%2 != 0 {
		return fmt.Errorf("field %s: must be a multiple of %v", "myNullableInteger", 2.000000)
	}
	if plain.mynullablenumber != nil {
		remainder := math.Mod(*plain.mynullablenumber, 0.2)
		if !(math.Abs(remainder) < 1e-10 || math.Abs(remainder-0.2) < 1e-10) {
			return fmt.Errorf("field %s: must be a multiple of %v", "myNullableNumber", 0.200000)
		}
	}
	{
		remainder := math.Mod(plain.mynumber, 0.2)
		if !(math.Abs(remainder) < 1e-10 || math.Abs(remainder-0.2) < 1e-10) {
			return fmt.Errorf("field %s: must be a multiple of %v", "myNumber", 0.200000)
		}
	}
	*j = MultipleOf(plain)
	return nil
}

func NewMultipleOfBuilder(o *MultipleOf) *MultipleOfBuilder {
	if o == nil {
		return &MultipleOfBuilder{}
	}
	return &MultipleOfBuilder{
		myinteger:         o.myinteger,
		mynullableinteger: o.mynullableinteger,
		mynullablenumber:  o.mynullablenumber,
		mynumber:          o.mynumber,
	}
}
