// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"

type MinMaxItemsJson struct {
	// mynestedarray corresponds to the JSON schema field "myNestedArray".
	mynestedarray [][]interface{} `json:"myNestedArray,omitempty,omitzero" yaml:"myNestedArray,omitempty" mapstructure:"myNestedArray,omitempty"`

	// mystringarray corresponds to the JSON schema field "myStringArray".
	mystringarray []string `json:"myStringArray,omitempty,omitzero" yaml:"myStringArray,omitempty" mapstructure:"myStringArray,omitempty"`
}

func (o *MinMaxItemsJson) MyNestedArray() [][]interface{} {
	return o.mynestedarray
}

func (o *MinMaxItemsJson) MyStringArray() []string {
	return o.mystringarray
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MinMaxItemsJson) UnmarshalJSON(value []byte) error {
	type MinMaxItemsJsonHelper struct {
		Mynestedarray [][]interface{} `json:"myNestedArray",omitempty`
		Mystringarray []string        `json:"myStringArray",omitempty`
	}
	type Plain MinMaxItemsJson
	var helper MinMaxItemsJsonHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.mynestedarray = helper.Mynestedarray
	plain.mystringarray = helper.Mystringarray
	if plain.mynestedarray != nil && len(plain.mynestedarray) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "myNestedArray", 1)
	}
	if len(plain.mynestedarray) > 5 {
		return fmt.Errorf("field %s length: must be <= %d", "myNestedArray", 5)
	}
	for i1 := range plain.mynestedarray {
		if plain.mynestedarray[i1] != nil && len(plain.mynestedarray[i1]) < 1 {
			return fmt.Errorf("field %s length: must be >= %d", fmt.Sprintf("myNestedArray[%d]", i1), 1)
		}
		if len(plain.mynestedarray[i1]) > 5 {
			return fmt.Errorf("field %s length: must be <= %d", fmt.Sprintf("myNestedArray[%d]", i1), 5)
		}
	}
	if plain.mystringarray != nil && len(plain.mystringarray) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "myStringArray", 1)
	}
	if len(plain.mystringarray) > 3 {
		return fmt.Errorf("field %s length: must be <= %d", "myStringArray", 3)
	}
	*j = MinMaxItemsJson(plain)
	return nil
}
