// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

type MapJson struct {
	// mymap corresponds to the JSON schema field "myMap".
	mymap MapJsonmymap `json:"myMap,omitempty,omitzero" yaml:"myMap,omitempty" mapstructure:"myMap,omitempty"`
}

func (o *MapJson) MyMap() MapJsonmymap {
	return o.mymap
}

type MapJsonmymap map[string]float64
