// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

type CaseDupes struct {
	// somefield corresponds to the JSON schema field "SomeField".
	somefield *string `json:"SomeField,omitempty,omitzero" yaml:"SomeField,omitempty" mapstructure:"SomeField,omitempty"`

	// somefield_2 corresponds to the JSON schema field "someField".
	somefield_2 *string `json:"someField,omitempty,omitzero" yaml:"someField,omitempty" mapstructure:"someField,omitempty"`

	// somefield_3 corresponds to the JSON schema field "some_Field".
	somefield_3 *string `json:"some_Field,omitempty,omitzero" yaml:"some_Field,omitempty" mapstructure:"some_Field,omitempty"`

	// somefield_4 corresponds to the JSON schema field "some_field".
	somefield_4 *string `json:"some_field,omitempty,omitzero" yaml:"some_field,omitempty" mapstructure:"some_field,omitempty"`

	// somefield_5 corresponds to the JSON schema field "somefield".
	somefield_5 *string `json:"somefield,omitempty,omitzero" yaml:"somefield,omitempty" mapstructure:"somefield,omitempty"`
}

type CaseDupesBuilder struct {
	somefield *string

	somefield_2 *string

	somefield_3 *string

	somefield_4 *string

	somefield_5 *string
}

func (b *CaseDupesBuilder) Build() *CaseDupes {
	return &CaseDupes{
		somefield:   b.somefield,
		somefield_2: b.somefield_2,
		somefield_3: b.somefield_3,
		somefield_4: b.somefield_4,
		somefield_5: b.somefield_5,
	}
}

func (b *CaseDupesBuilder) WithSomeField(v *string) *CaseDupesBuilder {
	b.somefield = v
	return b
}

func (b *CaseDupesBuilder) WithSomefield(v *string) *CaseDupesBuilder {
	b.somefield_5 = v
	return b
}

func (o *CaseDupes) Clone() *CaseDupesBuilder {
	return NewCaseDupesBuilder(o)
}

func (o *CaseDupes) SomeField() *string {
	return o.somefield
}

func (o *CaseDupes) Somefield() *string {
	return o.somefield_5
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CaseDupes) UnmarshalJSON(value []byte) error {
	type CaseDupesHelper struct {
		Somefield   *string `json:"SomeField",omitempty`
		Somefield_2 *string `json:"someField",omitempty`
		Somefield_3 *string `json:"some_Field",omitempty`
		Somefield_4 *string `json:"some_field",omitempty`
		Somefield_5 *string `json:"somefield",omitempty`
	}
	type Plain CaseDupes
	var helper CaseDupesHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.somefield = helper.Somefield
	plain.somefield_2 = helper.Somefield_2
	plain.somefield_3 = helper.Somefield_3
	plain.somefield_4 = helper.Somefield_4
	plain.somefield_5 = helper.Somefield_5
	*j = CaseDupes(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *CaseDupes) MarshalJSON() ([]byte, error) {
	type CaseDupesMarshalHelper struct {
		Somefield   *string `json:"SomeField",omitempty`
		Somefield_2 *string `json:"someField",omitempty`
		Somefield_3 *string `json:"some_Field",omitempty`
		Somefield_4 *string `json:"some_field",omitempty`
		Somefield_5 *string `json:"somefield",omitempty`
	}
	helper := CaseDupesMarshalHelper{
		Somefield:   j.somefield,
		Somefield_2: j.somefield_2,
		Somefield_3: j.somefield_3,
		Somefield_4: j.somefield_4,
		Somefield_5: j.somefield_5,
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *CaseDupes) UnmarshalYAML(value *yaml.Node) error {
	type Plain CaseDupes
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = CaseDupes(plain)
	return nil
}

func NewCaseDupesBuilder(o *CaseDupes) *CaseDupesBuilder {
	if o == nil {
		return &CaseDupesBuilder{}
	}
	return &CaseDupesBuilder{
		somefield:   o.somefield,
		somefield_2: o.somefield_2,
		somefield_3: o.somefield_3,
		somefield_4: o.somefield_4,
		somefield_5: o.somefield_5,
	}
}
