// Code generated by github.com/kainwinterheart/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "github.com/benbjohnson/immutable"
import yaml "gopkg.in/yaml.v3"

func NewThingBuilder(o *Thing) *ThingBuilder {
	if o == nil {
		return &ThingBuilder{}
	}
	return &ThingBuilder{
		values: o.values,
	}
}

type Thing struct {
	// values corresponds to the JSON schema field "values".
	values *immutable.List[Value] `json:"values,omitempty,omitzero" yaml:"values,omitempty" mapstructure:"values,omitempty"`
}

type ThingBuilder struct {
	values *immutable.List[Value]
}

func (b *ThingBuilder) Build() *Thing {
	return &Thing{
		values: b.values,
	}
}

func (b *ThingBuilder) WithValues(v *immutable.List[Value]) *ThingBuilder {
	b.values = v
	return b
}

func (o *Thing) Clone() *ThingBuilder {
	return NewThingBuilder(o)
}

func (o *Thing) Values() *immutable.List[Value] {
	return o.values
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Thing) UnmarshalJSON(value []byte) error {
	type ThingHelper struct {
		Values []Value `json:"values,omitempty"`
	}
	type Plain Thing
	var helper ThingHelper
	if err := json.Unmarshal(value, &helper); err != nil {
		return err
	}
	var plain Plain
	plain.values = func() *immutable.List[Value] {
		if helper.Values == nil {
			return nil
		}
		l := make([]Value, 0, len(helper.Values))
		for _, v := range helper.Values {
			l = append(l, (Value)(v))
		}
		return immutable.NewList(l...)
	}()
	*j = Thing(plain)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (j *Thing) MarshalJSON() ([]byte, error) {
	type ThingMarshalHelper struct {
		Values []Value `json:"values,omitempty"`
	}
	helper := ThingMarshalHelper{
		Values: func() []Value {
			if j.values == nil {
				return nil
			}
			lst := (*immutable.List[Value])(j.values)
			l := make([]Value, lst.Len())
			for i := 0; i < lst.Len(); i++ {
				__elem := lst.Get(i)
				l[i] = __elem
			}
			return l
		}(),
	}
	return json.Marshal(helper)
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Thing) UnmarshalYAML(value *yaml.Node) error {
	type PlainRaw struct {
		Values []Value
	}
	type Plain Thing
	var rawStruct PlainRaw
	if err := value.Decode(&rawStruct); err != nil {
		return err
	}
	var plain Plain
	plain.values = func() *immutable.List[Value] {
		if rawStruct.Values == nil {
			return nil
		}
		l := make([]Value, 0, len(rawStruct.Values))
		for _, v := range rawStruct.Values {
			l = append(l, (Value)(v))
		}
		return immutable.NewList(l...)
	}()
	plain = plain
	*j = Thing(plain)
	return nil
}

type Value float64

type AllOf = Thing
